1단계 - HTTP 웹 서버 구현
NewKrew2021/jwp-was-kakao pull request #1
Opened 2020-11-21 10:45 UTC by dongjoon1251

2020-11-23 09:35 UTC, ljh131 reviewed
제가 리뷰어가 아닌데 실수로 리뷰 했습니다😄 
몇 가지 의견 남겼으니 참고해주시면 감사하겠습니다.

2020-11-23 09:35 UTC, ljh131 commented on src/main/java/webserver/FileController.java
> +            return Response.error();
에러 스트링을 각 컨트롤러에서 만들지 않고,, 에러 객체를 정의해서 로직에서 던지고 메인 핸들러에서 이를 받아서 에러 응답을 내려주는식의 처리는 어떨까요?

2020-11-23 09:35 UTC, ljh131 commented on src/main/java/webserver/Router.java
> +    private static final String USER_PATH = "/user";
라우터에서 컨트롤러 별로 라우팅되는 경로를 알고있기보다는, 컨트롤러 공통 인터페이스를 만들고 각 컨트롤러가 이를 구현해 라우터는 그 인터페이스로 라우팅 테이블을 알아오는 방식은 어떨까요? 조금 더 복잡하겠지만 확장성에서 더 좋을 것 같습니다.

2020-11-23 09:35 UTC, ljh131 commented on src/main/java/webserver/UserController.java
> +    private Handlebars handlebars;
템플릿엔진은 이 컨트롤러에서만 쓰는 것 보단 공용으로 쓸 수 있게 하면 좋을 것 같습니다.

2020-11-23 09:35 UTC, ljh131 commented on src/main/java/webserver/UserController.java
> +            return Response.file(handlebars.compile("user/list").apply(new UsersDto(userService.findAll())).getBytes(), ContentType.HTML);
그리고 여기서 템플릿을 읽어와 응답으로 바꾸는 부분을 직접 사용하기보단 컨트롤러의 수퍼 클래스 혹은 다른 곳에서 해주면 좋을 것 같습니다.

2020-11-23 09:35 UTC, ljh131 commented on src/main/java/webserver/request/RequestHeader.java
> +        return lines.stream()
헤더는 매번 파싱하기보다는 요청이 오면 1회 파싱해두고 map에 k,v 형태로 저장해두면 효율적일 것 같습니다.

2020-11-23 09:35 UTC, ljh131 commented on src/main/java/webserver/request/RequestPath.java
> +    private static final String STATIC_PATH_PREFIX = "./static";
요구사항에 path가 `./css/style` 이렇게 나와있긴 하던데요,

http path는 /로 시작해야 되는 것으로 알고있습니다. 참고삼아 커멘트 남깁니다.

```
     request-line   = method SP request-target SP HTTP-version CRLF
```
https://tools.ietf.org/html/rfc7230#section-3.1.1

```
     request-target = origin-form
                    / absolute-form
                    / authority-form
                    / asterisk-form

     origin-form    = absolute-path [ "?" query ]
```
https://tools.ietf.org/html/rfc7230#section-5.3.1

```
     absolute-path = 1*( "/" segment )
```
https://tools.ietf.org/html/rfc7230#section-2.7

segment 역시 링크에서 타고 가면 됩니다.

위 문법인 augmented bnf에 의하면 `/ 세그먼트`가 1회 이상 반복입니다.
https://tools.ietf.org/html/rfc5234#section-3.6

2020-11-23 09:35 UTC, ljh131 commented on src/main/java/webserver/request/RequestReader.java
> +            return "";
바디 읽는게 실패해서 ""를 리턴하면 로직에서 잘못 처리할 수도 있고 여러모로 그냥 에러를 리턴하는게 더 정확할 것 같습니다.

2020-11-23 09:35 UTC, ljh131 commented on src/main/java/webserver/response/ResponseHeader.java
> +    private void setContentLength(int contentLength) {
content-length, content-type 들은 어차피 같은 http 헤더이니 http 헤더를 `setHeader(name, value)`로 설정해서 map에 k,v로 저장하면 더 generic할 것 같습니다. 그리고 setContentLength가 필요하다면, 그 메서드를 호출하면 되고요

2020-11-23 09:35 UTC, ljh131 commented on src/main/java/webserver/response/ResponseHeader.java
> +                Optional.ofNullable(protocol).map(protocol -> String.format("%s %s \r\n", protocol.getMessage(), status.getMessage())).orElse(""),
이 부분이 응답으로 내려줄 스트링을 만드는 부분 같은데요, 뭔가 잘못된 상황에서 orElse로 ""를 내주게 되면 http 프로토콜상 적절치 않으니 에러를 내는게 좋을 것 같습니다.
좀 더 우아하게 처리하려면 미리 정의된 '500 internal server error'을 응답 스트링으로 만들어 이를 응답을 내주는 방식도 있을 것 같습니다.

2020-11-23 09:35 UTC, ljh131 commented on src/main/java/webserver/request/RequestHeader.java
> +                .filter(line -> line.contains("Cookie"))
로그인 여부는 비지니스 로직에 가까운 부분일 것 같아서 응답 파싱하는 곳 보다는 다른 곳에 있으면 좋을 것 같습니다.

2020-11-23 09:35 UTC, ljh131 commented on src/main/java/webserver/request/RequestHeader.java
> +                .filter(line -> line.contains("Content-Length"))
`x-custom-header: Content-Length`같은 헤더가 있으면 문제될 것 같습니다.
그리고 헤더 이름은 case insensitive 하게 처리하는게 좋을 것 같습니다.

2020-11-23 09:35 UTC, ljh131 commented on src/main/java/webserver/FileController.java
> +    private Response getFileResponse(RequestPath path, ContentType css) {
css라는 이름은 잘못 적으신 것 같습니다.

2020-11-23 15:24 UTC, htrucci commented on src/main/java/model/UsersDto.java
> +    }
순번을 주기 위한 로직으로 보이는데요.
DTO의 역할이 아니라고 생각됩니다. 
별도의 요구사항이 없으므로 view에서 처리하거나 service 혹은, database 로직에 있어야 할 것으로 생각됩니다.

2020-11-23 15:27 UTC, htrucci commented on src/main/java/utils/RequestParser.java
> +    }
value가 없으면 오류가 발생할 것 같습니다.

2020-11-23 15:41 UTC, htrucci commented on src/main/java/webserver/UserController.java
> +    private static final String USER_LIST_PATH = "/user/list";
UserController에서는 path마다 /user 가 반복되므로 별도 상수로 두고 아래에서도 활용헀으면 좋겠습니다.

2020-11-23 15:43 UTC, htrucci commented on src/main/java/webserver/UserController.java
> +            if ("GET".equals(method)) {
HttpMethod.GET.matches(method) 
위와 같이 구현해도 되고 HttpMethod를 별도 Enum으로 만들던가하여 String Equals를 isXX 등으로
변경하면 좋을 것 같습니다.

2020-11-23 15:48 UTC, htrucci commented on src/main/java/webserver/UserController.java
> +            return Response.redirectWithCookie(request, "logined=true", "/index.html");
쿠키처리에 대한 부분은 어플리케이션 전반에 걸쳐 반복적으로 사용될 주제이므로
"logined=false" 값을 직접 넘기지 않고 별도의 유틸 등을 만들어 조작하면 더 깔끔해지지 않을까요?

2020-11-23 15:56 UTC, htrucci commented on src/main/java/webserver/request/RequestReader.java
> +            }
아래와 같이 줄여도 문제가 없을까요?
`while (!ObjectUtils.isEmpty(line)) { 
}`

2020-11-23 16:02 UTC, htrucci commented on src/main/java/utils/RequestParser.java
> +    }
상수명이 길어서 조금 읽기 어려운 것 같기도 하고..

2020-11-23 16:10 UTC, htrucci commented on src/test/java/service/UserServiceTest.java
> +        User expectedUser = new User("javajigi", "password", "%EB%B0%95%EC%9E%AC%EC%84%B1", "javajigi%40slipp.net");
@BeforeAll 어노테이션을 사용하여 반복적인 Database.addUser를 줄일 수 있을 것 같습니다

2020-11-23 16:12 UTC, htrucci commented on src/main/java/webserver/UserController.java
> +        loader.setSuffix(".html");
어플리케이션 전반적으로 사용되는 상수일 것 같습니다

2020-11-23 16:22 UTC, htrucci requested changes
안녕하세요~! 아직 이전 과정을 진행하고 있는지라,, 리뷰가 조금 늦었습니다 ^^;; 그 사이 ljh131 님이 좋은 코멘트를 많이 남겨주셨네요 ㅎㅎ 저도 몇가지 고민해본 의견 추가하여 Requeste changes로 요청드립니다. 확인 부탁드립니다~!

2020-11-25 04:54 UTC, dongjoon1251 commented on src/main/java/webserver/UserController.java
> +            if ("GET".equals(method)) {
HttpMethod 사용해서 수정하겠습니다.

2020-11-25 04:55 UTC, dongjoon1251 commented on src/main/java/webserver/UserController.java
> +    private static final String USER_LIST_PATH = "/user/list";
Router에서 USER_PATH로 만들어서 적용했습니다.

2020-11-25 05:13 UTC, dongjoon1251 commented on src/main/java/webserver/UserController.java
> +        loader.setSuffix(".html");
TemplateUtils로 분리했습니다.

2020-11-25 05:14 UTC, dongjoon1251 commented on src/main/java/model/UsersDto.java
> +    }
리스트 출력부분 때문에 넣었었는데 다른 방식으로 구현하고 DTO의 인덱스는 제거했습니다.

2020-11-25 05:32 UTC, dongjoon1251 commented on src/main/java/webserver/UserController.java
> +            return Response.redirectWithCookie(request, "logined=true", "/index.html");
Cookie 클래스로 분리했습니다.

2020-11-25 05:51 UTC, dongjoon1251 commented on src/main/java/utils/RequestParser.java
> +    }
메소드로 key, value  가져오는 부분 분리하고 params length에 따라서 오류가 나게 하거나 빈값을 리턴하게 수정했습니다.

2020-11-25 05:55 UTC, dongjoon1251 commented on src/main/java/webserver/request/RequestHeader.java
> +                .filter(line -> line.contains("Cookie"))
쿠키 포함 여부 판단하는 메소드로 수정하고 로그인 확인 메소드는 UserController로 이동했습니다.

2020-11-25 05:56 UTC, dongjoon1251 commented on src/main/java/webserver/UserController.java
> +    private Handlebars handlebars;
TemplateUtils로 분리했습니다.

2020-11-25 05:57 UTC, dongjoon1251 commented on src/main/java/webserver/Router.java
> +    private static final String USER_PATH = "/user";
다음 단계 미션에 포함되는 리팩토링이라 다음 단계에서 말씀해주신 부분 적용 고려해보겠습니다.

2020-11-25 06:00 UTC, dongjoon1251 commented on src/main/java/webserver/UserController.java
> +            return Response.file(handlebars.compile("user/list").apply(new UsersDto(userService.findAll())).getBytes(), ContentType.HTML);
컨트롤러 관련 리팩토링이 다음 미션에 포함되어 있어서 다음 미션에서 진행하겠습니다.

2020-11-25 06:01 UTC, dongjoon1251 commented on src/main/java/webserver/request/RequestPath.java
> +    private static final String STATIC_PATH_PREFIX = "./static";
해당 부분은 URL의 path를 확인하는 부분이 아니라 파일 경로에 대한 Prefix라서 혼동을 드렸던 것 갔습니다.

2020-11-25 06:48 UTC, dongjoon1251 commented on src/main/java/webserver/request/RequestHeader.java
> +                .filter(line -> line.contains("Content-Length"))
특정 키값에 대한 확인을 startWith로 변경해보겠습니다.

2020-11-25 06:52 UTC, dongjoon1251 commented on src/main/java/webserver/FileController.java
> +            return Response.error();
RuntimeException을 던지도록 수정했습니다.

2020-11-25 06:53 UTC, dongjoon1251 commented on src/main/java/webserver/request/RequestReader.java
> +            return "";
에러를 RuntimeException으로 던지도록 수정했습니다.

2020-11-25 06:55 UTC, dongjoon1251 commented on src/main/java/webserver/response/ResponseHeader.java
> +                Optional.ofNullable(protocol).map(protocol -> String.format("%s %s \r\n", protocol.getMessage(), status.getMessage())).orElse(""),
HttpProtocol과 상태는 항상 있어야 하는 부분이라 없을 경우에 RuntimeException이 나도록 수정했습니다.

2020-11-26 06:05 UTC, merged

2020-11-26 06:07 UTC, htrucci commented
오잉 왜 코멘트가 없어졌지;;
@dongjoon1251 
머지했습니다. 보고 많이 배우게 되네요. 다음 단계도 화이팅입니다~!