feat: 1단계 - HTTP 웹 서버 구현
NewKrew2021/jwp-was-kakao pull request #11
Opened 2020-12-08 08:41 UTC by htrucci

2020-12-08 13:48 UTC, limmmee-bonjour requested changes
@htrucci 안녕하세요 :) 리뷰어로 지정된 벨입니다!
HTTP 웹 서버 구현해주시느라 고생 많으셨습니다.
전체적으로 구조화 및 일급 컬렉션 정의가 잘 되어있어서 어렵지 않게 코드리뷰를 할 수 있었습니다. 👍 

다만, 요구사항의 몇가지 부분 확인이 필요할 것 같습니다. 이 부분 확인 부탁드리고요.
요구사항 5 : 로그인 성공시 Cookie에  logined=true 셋팅하기
요구사항 6 : http://localhost:8080/user/list 로 접근 

추가적으로 제가 생각하는 구조와 소소한 코드수정에 대해 의견 남겼어요.
제 의견이 무조건 맞는것이 전혀 아니니 의문점이 생기는 부분에 대해서는 대화를 통해서 더 많은 의견 나누면 좋을 것 같아요. 제가 잘못 이해한 부분이 있다면 언제든 슬랙으로 DM 주셔요!

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/model/User.java
>      public User(String userId, String password, String name, String email) {
User 객체 생성시 기본적인 validation 체크(ex.빈값)는 해주는게 어떨까요?

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/service/UserService.java
> +    public boolean loginProcess(String userId, String password) {
보통 boolean 리턴타입의 메서드명을 명명할 때 prefix로 is or has를 사용하는데요. 이런 방법으로 바꾸어보는 건 어떨까요? 
만약 loginProcess가 의도한 메서드명이라면 동사+명사의 형태로 processLogin이 좋을 것 같습니다.

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/RequestHandler.java
> +            RequestMappingHandler requestMappingHandler = new RequestMappingHandler();
RequestMappingHandler는 static 메소드를 가지고 있는 클래스인 것 같은데 객체를 생성하는 이유가 있나요?
(아래에서는 static 메소드를 바로 사용하고 있네요~)
만약, 유틸리티성 클래스가 될거라면 생성자 호출시 에러를 낼 수 있도록 추가해주는 게 좋을 것 같습니다
```
private RequestMappingHandler() { 
     throw new IllegalStateException("Utility class"); 
}
```

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/RequestMappingHandler.java
> +        }else{
```
Arrays.asList(STATIC_RESOURCE_PATH_SUFFIX).contains(request.getPath())
```
해당 구문은 의도한 걸까요? 매핑되는 path가 없을듯 합니다~
의도한 ~.css , ~.js path는 else 구문을 탈 것 같네요. 
해당 구문을 없애거나 path의 postfix를 가져와서 비교를 하는 방법으로 수정이 필요해보입니다.

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/controller/HttpController.java
> +        return FileIoUtils.loadFileFromClasspath(RequestMappingHandler.TEMPLATES_RESOURCE_PATH_PREFIX + viewName);
TEMPLATES_RESOURCE_PATH_PREFIX 상수는 RequestMappingHandler 에서는 사용하지 않는 것 같은데, 
HttpController 가 아닌 RequestMappingHandler에 위치하는 이유가 있을까요?

추가로 저도 어떤것이 옳으냐 라고 물어봤을때, 정확한 답을 내리지는 못하겠지만 의견 드립니다 :)
setView 메서드는 Controller에 존재해야하는 메서드일까요?
HttpResponse 생성시 body를 만들기 위해 사용되어지는 것 같은데, 오히려 해당 부분을 정적팩토리 메소드로 구현하는건 어떨까요?
```
public static HttpResponse ofHttpResponseView(ResponseHeader header, String viewName) throws IOException, URISyntaxException {
    return new HttpResponse(header, FileIoUtils.loadFileFromClasspath(RequestMappingHandler.TEMPLATES_RESOURCE_PATH_PREFIX + viewName));
}
```
setView를 옮기면 Controller를 인터페이스화 할 수 있고 그렇게 되면 좀 더 유연한 구조가 될 듯 합니다.

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/controller/MainController.java
> +            responseHeader.addHeader("Content-Type", ContentType.HTML.toString());
해당 코드는 ResponseHeader.setContentType 코드와 중복되는 코드 같은데, 해당 메서드를 사용하는건 어떨까요~?

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/controller/StaticResourceController.java
> +        if(httpRequest.getPath().endsWith(".css")){
위에 드린 의견과 마찬가지로 ResponseHeader.setContentType 코드와 중복되는 코드같습니다.

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/controller/UserController.java
> +        }else if(httpRequest.getPath().endsWith(USER_LIST_HTML)){
[요구사항 6 - http://localhost:8080/user/list 로 접근] 해당 하는 누락된 것 같습니다.  
user/list 접근 시 정상적인 페이지가 호출되지 않네요. 이부분 확인 부탁드립니다.

추가로, 요청 Path가 .html인 경우 UserController에서가 아닌 RequestMappingHandler에서 byPass 해주는건 어떨까요?
(.html 호출의 경우 기존 staticResource와 같은 형태로 보여지네요.)

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/controller/UserController.java
> +            }
1. User 생성시 get 형식으로 호출하게되면 의도치않은 형태로 동작하게됩니다 (endsWith로 체킹하기 때문에)
```
http://localhost:8080/user/create?userId=javajigi&password=password&name=%EB%B0%95%EC%9E%AC%EC%84%B1&email=javajigi%40slipp.net
```
path 매핑시 postfix 와 parameter를 제외한 순수(?) path로 비교해야할 듯 하네요.

2. GET, POST method에 따라 User 객체를 각각 생성하고 있는데,
결국에는 실제 둘다 requestBody의 queryString을 가져오고 있습니다. 
중복되는 동일한 코드로 보여집니다. 확인 부탁드려요 :)

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/controller/UserController.java
> +            UserService userService = new UserService();
UserService 객체를 재생성하여 사용하는 이유가 있을까요~?

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/http/HttpRequest.java
> +    }
Protocol Key를 가진 HttpHeader를 가져오는 부분은 성격상 HttpRequest가 아닌 HttpHeader에 있어야 맞을 것 같은데, 어떻게 생각하시나요~?
추가적으로 "Protocol" String 값도 상수화 하고요.  
Protocol이라는 String key 값은 HttpHeader 에서만 알고있어야할 키 값으로 보여집니다~
(method, path, host 등등도 동일해요 :) )
```
 public String getProtocol() {
    return httpHeader.getProtocolHttpHeader();
}
```

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/http/HttpResponse.java
> +    public HttpResponse(byte[] body) {
다양한 생성자가 존재하는데요. 생성자보다는 정적 팩토리 메서드를 사용하는게 어떨까요?
개인적으로 정적 팩토리 메서드를 사용하는 이유는,
네이밍을 정의할 수 있기때문에 의미있는 네이밍을 가질 수 있습니다.
생성자를 캡슐화하여 목적성을 가진 정적 팩토리 메소드만 오픈할 수 있습니다.

이펙티브자바 규칙1 또는 [해당 글](https://velog.io/@ljinsk3/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C)을 읽어보시면 좋을 것 같습니다 :)

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/http/RequestBody.java
> +    public QueryString queryString;
1. body는 사용되어지지 않는 것으로 보여지고 queryString으로 대체할 수 있는 값으로 보여지는데, 삭제하는 것이 어떨까요?
2. QueryString 또한 private final 처리하는게 좋을 것 같습니다 :)

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/http/ResponseBody.java
> +public class ResponseBody {
현재 사용되어지지 않는 클래스로 보여지네요 삭제하면 좋을것 같아요~

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/http/ResponseHeader.java
> +    public void addHeader(String key, String value) {
addHeader를 셋팅하는 부분이 Controller 여기저기에 산재해 있는 것 같은데요~
ResponseHeader 생성시 정적팩토리 메서드를 사용해 셋팅해주는 방법은 어떨까요~?

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/main/java/webserver/controller/UserController.java
> +                responseHeader.setLoginCookie(httpRequest, true);
[요구사항 5 - 로그인 성공시 Cookie 에  logined=true 셋팅하기]
id / password가 일치하는 경우에도 cookie 값이 logined=true로 셋팅되지 않는 것 같습니다~
이부분 확인 부탁드려요 :)!

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/test/java/webserver/user/UserServiceTest.java
> +package webserver.user;
테스트 클래스의 경우 클래스(User) 패키지와 구조를 맞추는 것이 좋을 것 같습니다 :)

2020-12-08 13:48 UTC, limmmee-bonjour commented on src/test/resources-test/GET_HTML_LOGIN_FALSE
> +GET /index.html HTTP/1.1
테스트시 샘플 HTTP를 만들어서 테스트하는 방법 좋네요 👍

2020-12-08 13:48 UTC, limmmee-bonjour commented on README.md
> +STEP1 요구사항
어디가 적절할지 몰라 여기에 코멘트 남겨요 :)
모든 커밋을 한번에 하기보다는 task를 나누어서 커밋하는게 좋을 것 같아요 !
작업했던 과정이나 공통된 작업들을 묶을 수 있어요~

2020-12-10 06:36 UTC, htrucci commented on src/main/java/model/User.java
>      public User(String userId, String password, String name, String email) {
생성자에 빈값 유효성체크 추가하였습니다~!

2020-12-10 06:38 UTC, htrucci commented on src/main/java/service/UserService.java
> +    public boolean loginProcess(String userId, String password) {
좀 더 명확한 의미로 변경하였습니다 (isValidUserByLogin)

2020-12-10 06:57 UTC, htrucci commented on src/main/java/webserver/RequestMappingHandler.java
> +        }else{
제가 검증을 제대로 못했네요;;

2020-12-10 14:39 UTC, htrucci commented on src/main/java/webserver/controller/UserController.java
> +            }
둘 다 구현하는 것으로 잘못이해하여 수정하였습니다

2020-12-10 14:40 UTC, htrucci commented on src/main/java/webserver/controller/UserController.java
> +            UserService userService = new UserService();
잘못된 코드가 맞습니다 ^^;;

2020-12-10 14:45 UTC, htrucci commented on src/main/java/webserver/http/HttpRequest.java
> +    }
HttpServletRequest 에서 다 제공하던 기억으로 참고하긴 했는데요 
(https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html)

편의상 HttpRequest로 꺼내놓은거고 말씀하신대로 Protocol은 HttpHeader에 있어야 할 것 같네요.
또 상수화 하였습니다.

2020-12-10 16:05 UTC, htrucci commented on src/main/java/webserver/http/RequestBody.java
> +    public QueryString queryString;
body 날 것의 데이터를 쓸때도 있을 것 같아서 유지하였습니다.

2020-12-10 17:09 UTC, htrucci commented on src/main/java/webserver/controller/UserController.java
> +                responseHeader.setLoginCookie(httpRequest, true);
해당 쿠키가 첫번째일째만 셋팅이 되고있어서 제가 되는 것으로 인식했나봐요 ^^;;
수정하여 확인하였습니다

2020-12-10 17:11 UTC, htrucci commented on README.md
> +STEP1 요구사항
조언해주신 내용 참고하겠습니다~!

2020-12-11 05:16 UTC, htrucci commented
리뷰를 세심하게 해주셔서 많은 도움이 되었습니다  ㅠㅠ
정적팩토리 메서드에 대해 정확히 인식 못하고 있었는데 확실히 인식이 되었네요.

2020-12-14 11:52 UTC, merged

2020-12-14 11:52 UTC, limmmee-bonjour commented
안녕하세요! 
리뷰 주셨는데, 제가 일이있어 리뷰가 늦어졌네요ㅠ_ㅠ 죄송합니다!
수정하여 반영해주신 부분 잘 보았습니다.
1단계는 이 정도로 마무리하면 될 것 같아 머지하도록 하겠습니다. 
그럼 2단계도 화이팅입니다!

(다만, 2단계 작업시 요구사항6번 "user/list 접근하도록 한다" 도 같이 반영하면 좋을것 같습니다 (현재는 user/list.html으로 접근됩니다))