[step3] 🚀 3단계 - 세션 구현하기
NewKrew2021/jwp-was-kakao pull request #15
Opened 2020-12-10 14:59 UTC by karian7

[3단계](https://edu.nextstep.camp/s/6czWWFk0/ls/GamsmLRX) 구현입니다.

구현 내용에 특별한건 없고 구현할 때 마지막 부분은 [클린코드 동기들과 함께 몹코딩](https://nextstep-members.slack.com/archives/C01DFPK1UJY/p1607522816443100)으로 구현해 봤습니다. 😀 

잘 부탁드립니다~ 🙇

2020-12-12 12:57 UTC, dongjoon1251 requested changes
테스트 코드도 자세히 작성해주시고 요구사항도 잘 정리해주셨네요 💯 
쿠키 설정 하는 부분 코멘트 드렸습니다. 
그리고 이전에 SEE_OHTER로 사용하셨던 것 같은데요. 저도 구현할때 적용하려고 보다보니 302는 Found로 표현되는 것 같습니다. 같이 확인 부탁드려요!

2020-12-12 12:57 UTC, dongjoon1251 commented on src/main/java/webserver/http/HttpRequest.java
>      public Cookies getCookies() {
cookie를 처음에 파싱할 때 필드에 저장해두면 null체크 상관없이 바로 리턴해줄 수 있지 않을까요? :)

2020-12-14 12:10 UTC, karian7 commented
> 그리고 이전에 SEE_OHTER로 사용하셨던 것 같은데요. 저도 구현할때 적용하려고 보다보니 302는 Found로 표현되는 것 같습니다. 같이 확인 부탁드려요!

헉 그렇네요. 옆에 Status Value 를 `302 Found` 로 해놓고선.ㅎㅎ e2d49af7edfb99269af9adc042724613434bd059 에서 수정하였습니다.

2020-12-14 12:26 UTC, karian7 commented on src/main/java/webserver/http/HttpRequest.java
>      public Cookies getCookies() {
할때 Request Line 파싱 -> 헤더 파싱 -> 바디 파싱 의 절차로 진행되고 있어서 헤더 파싱하여 저장 하는 단계에 같이 설정하도록 바꿨습니다.

17faaeb 에서 수정하였습니다 😀

2020-12-15 08:24 UTC, merged

2020-12-15 08:25 UTC, dongjoon1251 commented
마지막 단계까지 마무리 잘해주셨네요 ㅎㅎ
제가 미션을 먼저 수행해보지 못한 부분도 있고, 
피드백을 드리는 기준이 되는 설계가 없어서 좀더 다양한 피드백을 드리지 못해서 죄송합니다. 
고생하셨습니다!