2단계 - HTTP 웹 서버 리팩토링
NewKrew2021/jwp-was-kakao pull request #16
Opened 2020-12-12 12:44 UTC by dongjoon1251

2020-12-14 15:05 UTC, htrucci commented on src/main/java/controller/Controller.java
> +
2단계 요건중 아래와 같이 추상화하는 부분이 있는데 빠진 것 같네요~!
void service(HttpRequest request, HttpResponse response);

2020-12-14 15:23 UTC, htrucci commented on src/main/java/webserver/request/HttpRequest.java
> +    public String getParam(String key) {
가능하다면 표준?으로 사용되는 getParameter로 명확히 명명하는 것은 어떨까요?

2020-12-14 15:37 UTC, htrucci commented on src/main/java/controller/LoginController.java
> +    private String getCookieValue(boolean loginSuccess) {
Boolean.toString 으로 바로 리턴해도 되지 않을까 싶은데요.
getCookieValue 명칭이 조금 모호하다는 생각이 듭니다. 
좀 더 명확한 명칭을 쓰는게 좋을 것 같아요~!

2020-12-14 15:56 UTC, htrucci commented on src/main/java/controller/UserController.java
> +import static controller.LoginController.LOGIN_COOKIE_KEY;
개인적으로는 상수를 import하여 쓸때 static import하지 않고 
LoginController.LOGIN_COOKIE_KEY 와 같이 prefix를 붙여 사용하는데요.
Prefix로 인해 길어지긴 하지만 어디서 온 상수인지 가독이 쉬워서 유지보수하기 더 좋은 요소인 것 같아요.

LOGIN_COOKIE_KEY가 여러군데서 쓰일 가능성이 있기 때문에 쿠키키 상수를 가지는 별도의 constants클래스로 분리하고 
예로 Constants.LOGIN_COOKIE_KEY 와 같이 쓰는게 좋지않을지 개인적인 의견드립니다~

2020-12-14 15:58 UTC, htrucci commented on src/main/java/controller/LoginController.java
> +        if (loginSuccess) {
삼항 연산자를 쓰면 더 깔끔할 것 같네요~!
return loginSuccess ? "/index.html" : "/user/login_failed.html";

2020-12-14 16:08 UTC, htrucci commented on src/main/java/controller/UserController.java
> +        userService.addUser(new User(request.getParam("userId"), request.getParam("password"), request.getParam("name"), request.getParam("email")));
User객체 생성하는 부분은 분리하는게 보기 편한 부분도 있을 것 같아요~!
User user = new User(request.getParam("userId"), request.getParam("password"), request.getParam("name"), request.getParam("email"))

2020-12-14 16:14 UTC, htrucci commented on src/main/java/controller/UserController.java
> +    private boolean isLogined(HttpRequest request) {
컨트롤러가 늘어난다고 하면 isLogined가 중복으로 발생할 것이어서,,
HttpRequest 로 옮겨저서 request.isLogined() 하면 되지않을까 생각이 들면서 
HttpRequest가 담당하는게 맞나 헷갈리는 부분이 있는데요. 혹시 의견이 있다면 피드백 부탁드립니다~!

2020-12-14 16:30 UTC, htrucci commented on src/main/java/webserver/response/HttpResponse.java
> +        this.header.setLocation("http://" + request.getHeader().getHost() + path);
찾아보니 풀path는 필요없을 것 같은데, 이유가 있을지 궁금합니다~

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location]

2020-12-14 16:43 UTC, htrucci commented on src/main/java/controller/UserController.java
> +    }
/user/list.html 호출시 showUsers를 타지 않는 것 같은데요. 
확인 부탁드립니다~
(templates) 는 전역적 템플릿 설정 경로이니 상수화하는 것이 어떨까요?

2020-12-14 17:01 UTC, htrucci commented on src/main/java/exception/ExceptionHandler.java
> +}
👍 👍 👍 👍 👍 
궁금해서 테스트를 해봤는데, 제가 방법이 틀렸을수도 있는데,, 
HttpResponse.error() 전에 소켓이 닫혀서 500으로 응답을 못하네요.

2020-12-14 17:02 UTC, htrucci commented on src/main/java/model/Model.java
> +}
👍 👍 👍 👍 👍

2020-12-14 17:19 UTC, htrucci commented on src/main/java/utils/io/IOUtils.java
> +            throw new FileReadException();
예외처리를 추가해주셨네요!
테스트 코드를 작성하셔도 좋을 듯 합니다! 👍

2020-12-14 17:51 UTC, htrucci commented on src/main/java/utils/template/TemplateUtils.java
> -    private static final String PREFIX = "/templates";
전역적인 templates경로가 바뀌면 viewPath를 다 바꿔줘야해서
PREFIX는 다시 와도 괜찮지 않을까 싶습니다.

2020-12-14 18:35 UTC, htrucci commented on src/main/java/webserver/Cookie.java
> +    public static Cookie fromRequest(String line) {
명확한 의미라서 좋긴하지만 정적 팩토리 메서드 컨벤션을 따라 그냥 from 혹은 of로 둬도 괜찮을 것 같아요~!

2020-12-14 18:38 UTC, htrucci commented on src/main/java/webserver/Cookie.java
> +        return new Cookie(tokens[0].trim(), tokens[1].trim(), null);
로그인 쿠키설정시 Path를 /로 설정하는 부분이 리팩토링 과정에서 누락되었네요~!

2020-12-14 18:57 UTC, htrucci commented on src/main/java/webserver/Dispatcher.java
> +        if (method.getParameterCount() == 3) {
컨트롤러에 선언된 parameterCount로 체크하기에는 잠재적 위험이 있어보이네요.
parameterClassType을 읽어오거나 해서 매칭하여 model을 넘겨주는 것이 좀 더 안전할 것 같습니다~!

2020-12-14 18:58 UTC, htrucci commented on src/main/java/webserver/FileController.java
> -public class FileController {
구조가 분리되면서 컨트롤러를 없앴네요 👍

2020-12-14 19:04 UTC, htrucci commented on src/main/java/webserver/WebServer.java
> +    private static final int DEFAULT_PORT = 8081;
8080포트가 요구사항에 있는데 포트가 달라졌네요~!

2020-12-14 19:14 UTC, htrucci commented on src/main/java/controller/UserController.java
> +        userService.addUser(new User(request.getParam("userId"), request.getParam("password"), request.getParam("name"), request.getParam("email")));
빈값으로 생성이 가능하여, User 데이터 검증이 추가되면 좋을 것 같아요~!

2020-12-14 19:23 UTC, htrucci commented on src/main/java/webserver/request/HttpRequest.java
> +    private Map<String, String> bodyParams;
queryString이 모두 파싱되어 parameterMap으로 들어오니 body는 빼도 되지 않을까 싶어요!

2020-12-14 19:31 UTC, htrucci commented on src/main/java/webserver/request/RequestBuilder.java
> +}
HttpRequest를 만들때만 사용하는 클래스이다 보니 
내부 클래스로 포함시켜서 정말 Builder패턴의 Builder가 되었어도 괜찮았을 것 같아요~!
혹시 안티패턴이면 말씀해주세요~

2020-12-14 19:41 UTC, htrucci commented on src/main/java/webserver/requestmapping/RequestMapping.java
> +                Arrays.asList("addUser", "addUser")));
addUser가 두개 들어가는건 필요한 부분인가요?

2020-12-14 19:50 UTC, htrucci commented on src/main/java/webserver/requestmapping/RequestMapping.java
> +    }
실제 RequsetMappingHandler와 비슷하게 잘 짜셨는데 메서드명 변경시 잠재적 오류가 있을 것 같네요 ㅠㅠ

힌트요건에 하나의 컨트롤러 인터페이스를 상속받아 3가지 컨트롤러로 분리하도록 구현하도록 되어있긴한데,,
힌트 내용과 같이 동일한 메서드를 사용하여 맵핑이 필요없다면 아래와 같이 선언 및 추가가 가능하여 구조적으로 더 좋을 것 같습니다.

USER_CREATE(Method.GET, "/user/create", CreateUserController.class)
USER_LOGIN(Method.POST, "/user/login", LoginController.class)
USER_LIST(Method.GET, "/user/list", ListUserController.class)

2020-12-14 19:51 UTC, htrucci commented on src/main/java/webserver/response/ResponseHeader.java
> +        headers.add(String.format("Content-Length: %d\r\n", contentLength));
String.format을 활용한 부분이 좋은 것 같습니다~! 👍

2020-12-14 20:00 UTC, htrucci commented on src/test/java/webserver/request/RequestBuilderTest.java
> +
step2 힌트내용과 같이 요청 내용을 파일로 만들어놓고 읽어서 쓰면 테스트 코드 활용성이 더 높아질 것 같아요~!

`InputStream in = new FileInputStream(new File(testDirectory + "Http_POST2.txt"));
  HttpRequest request = new HttpRequest(in);`

2020-12-15 00:27 UTC, htrucci requested changes
안녕하세요~
2단계 구현하느라 고생하셨습니다~! 역할분리 및 mvc구조화가 아주 잘 되었네요! 👍
몇가지 의견 확인해주시고 다시 리뷰 요청 부탁드립니다~!

2020-12-15 08:51 UTC, dongjoon1251 commented on src/main/java/controller/Controller.java
> +
음 말씀해주신 부분은 2단계 요건은 아니고 힌트라서 맞추진 않았습니다.
Controller 인터페이스를 구현하고(사실 구현한다기 보단 @Controller 느낌으로 붙였는데 어노테이션으로는 구현하지 않았습니다 ㅎㅎ;)
HttpRequest, HttpResponse 파라미터를 받거나
HttpRequest request, HttpResponse response, Model model을 받는 메소드가 있으면
request mapping이 가능하도록 설계했습니다.

2020-12-15 08:53 UTC, dongjoon1251 commented on src/main/java/webserver/request/HttpRequest.java
> +    public String getParam(String key) {
관련해서 Param으로 되어있는 부분 혹은 params 변수등은 모두 Parameter, parameters로 수정했습니다.

2020-12-15 08:55 UTC, dongjoon1251 commented on src/main/java/controller/LoginController.java
> +    private String getCookieValue(boolean loginSuccess) {
https://developer.mozilla.org/ko/docs/Web/HTTP/Cookies
명칭이 어떤지 찾아보니 cookie-value라고 확인되었습니다.
옆에 LOGIN_COOKIE_KEY라고 한 부분은 해당 문서를 참고해서 LOGIN_COOKIE_NAME으로 수정했습니다.

2020-12-15 09:00 UTC, dongjoon1251 commented on src/main/java/controller/UserController.java
> +import static controller.LoginController.LOGIN_COOKIE_KEY;
음 여러군데에서 쓰이지만 사용되는 모든 상수를 한곳에 모으면 constant 클래스는 더 많은 변경에 노출될 위험이 커보입니다. 
말씀해주신대로 LoginController. LOGIN_COOKIE_KEY 로 바꾸려다보니 사용되는 부분이 UserController밖에 없었습니다.
그래서 같은 상수를 사용해야하는 로직이면 합치는게 낫다고 생각이 들어서 UserController로  합치고, LoginController는 삭제했습니다.

2020-12-15 09:11 UTC, dongjoon1251 commented on src/main/java/controller/UserController.java
> +        userService.addUser(new User(request.getParam("userId"), request.getParam("password"), request.getParam("name"), request.getParam("email")));
method로 분리했습니다.

2020-12-15 09:14 UTC, dongjoon1251 commented on src/main/java/controller/UserController.java
> +    private boolean isLogined(HttpRequest request) {
'HTTP 요청/응답 처리 기능은 애플리케이션 개발자가 신경쓰지 않아도 재사용이 가능한 구조가 되도록 한다.'

위와 같은 요구사항이 있어서 애플리케이션 관련 로직은 controller, service 등에 있는게 더 낫다고 생각됩니다.
AuthenticationManager 같은 별도의 서비스 빈 클래스가 isLogined 역할을 담당하는게 더 맞지만 지금은 사용되는 곳이 한곳이라 분리하진 않았습니다.

2020-12-15 09:19 UTC, dongjoon1251 commented on src/main/java/webserver/response/HttpResponse.java
> +        this.header.setLocation("http://" + request.getHeader().getHost() + path);
1단계 미션 설명에 있는 https://en.wikipedia.org/wiki/HTTP_302 를 보고 다 붙였습니다. 
빼는게 더 깔끔하네요 👍

2020-12-15 09:22 UTC, dongjoon1251 commented on src/main/java/controller/UserController.java
> +    }
상수화하였습니다. 
비로그인시 진입되는 이슈는 이전에 로그인 후에 로컬 브라우저의 쿠키가 업데이트 된채로 남아있어서 그런 것 같습니다. 이부분은 3단계 미션에서 세션을 통해 개선될 수 있어 보입니다.

2020-12-15 09:42 UTC, dongjoon1251 commented on src/main/java/exception/ExceptionHandler.java
> +}
output stream이 return되고 나서는 닫히는 것 같네요.. exception handling하는 부분을 따로 메소드로 빼고 거기서 dispatch error를 처리하도록 수정했습니다.

2020-12-15 09:48 UTC, dongjoon1251 commented on src/main/java/webserver/Cookie.java
> +    public static Cookie fromRequest(String line) {
from으로 수정했습니다

2020-12-15 10:23 UTC, dongjoon1251 commented on src/main/java/webserver/Cookie.java
> +        return new Cookie(tokens[0].trim(), tokens[1].trim(), null);
요청으로부터 쿠키 객체를 만들때느 path정보가 없습니다. 응답에서 path 설정하는 부분은 다른 생성자를 사용했습니다.

2020-12-15 10:23 UTC, dongjoon1251 commented on src/main/java/webserver/WebServer.java
> +    private static final int DEFAULT_PORT = 8081;
다시 8080으로 변경했습니다.

2020-12-15 10:25 UTC, dongjoon1251 commented on src/main/java/webserver/request/HttpRequest.java
> +    private Map<String, String> bodyParams;
지금은 body에서 parameter만 받지만 
body를 통해서 처리할 수 있는 방식이 달라질 수 있을 것 같아서 필드로 분리해주는 게 낫다고 판단했습니다.

2020-12-15 10:27 UTC, dongjoon1251 commented on src/main/java/webserver/requestmapping/RequestMapping.java
> +                Arrays.asList("addUser", "addUser")));
메소드별로 다른 로직을 태울 가능성도 있어서 일단 중복으로 넣어놨습니다.

2020-12-15 10:39 UTC, dongjoon1251 commented on src/main/java/utils/template/TemplateUtils.java
> -    private static final String PREFIX = "/templates";
다시 적용했습니다.

2020-12-15 10:46 UTC, dongjoon1251 commented on src/main/java/webserver/Dispatcher.java
> +        if (method.getParameterCount() == 3) {
type도 체크하도록 수정했습니다

2020-12-15 11:19 UTC, dongjoon1251 commented on src/main/java/controller/UserController.java
> +        userService.addUser(new User(request.getParam("userId"), request.getParam("password"), request.getParam("name"), request.getParam("email")));
1글자 이상인지 확인하는 로직을 User 생성자에 추가했습니다.

2020-12-15 11:28 UTC, dongjoon1251 commented on src/main/java/webserver/request/RequestBuilder.java
> +}
Builder로 넣을까 하다가 HttpRequest가 커지기도 했고, 토크나지잉 로직도 있어서 분리시켰습니다. 안티패턴이라기보다는 클래스명을 Builder로 넣어서 그런것 같습니다. 해당 클래스 역할은 parsing에 더 가까워서 RequestParser로 이름을 변경했습니다.

2020-12-15 11:47 UTC, dongjoon1251 commented on src/main/java/webserver/requestmapping/RequestMapping.java
> +    }
enum을 컴파일 하는 시점에 method가 정확히 있는지 체크하는 로직을 추가했습니다. 그리고 말씀해주신 것처럼 enum으로 바꾸고 나니 훨씬 깔끔해졌네요 :)

2020-12-15 12:01 UTC, dongjoon1251 commented on src/test/java/webserver/request/RequestBuilderTest.java
> +
test 폴더에 resource 폴더를 추가해서 말씀해주신 방법으로 테스트 수정했습니다

2020-12-15 12:07 UTC, dongjoon1251 commented on src/main/java/webserver/requestmapping/RequestMapping.java
> +    }
어노테이션 통해서 requestMapping에 추가되도록 하는 부분은 2번째 미션에 있는 것 같아서 추가하진 않았습니다 :)

2020-12-16 09:50 UTC, htrucci commented on src/main/java/controller/LoginController.java
> +    private String getCookieValue(boolean loginSuccess) {
아 그 cookieValue를 셋팅하는 부분이긴하나 login쿠키와 밀접하고 실제 함수의 역할을 고려하여 getLoginCookieValue 등으로 바꿔야하지 않나 생각이 들어 말씀드린 부분이었습니다~!

2020-12-16 10:34 UTC, htrucci commented on src/main/java/controller/UserController.java
> +    }
아 이건 제가 다시 확인해보니 /user/list 로 구현하고 /user/list.html 로 들어가란 요건은 없더라구요 ㅠ
user/list.html은 접근이 안되게 빼야할 것 같습니다.

2020-12-16 10:44 UTC, htrucci commented on src/main/java/webserver/Cookie.java
> +    private final String name;
아! name이 더 올바른 네임이네요! ㅎㅎ

2020-12-16 10:47 UTC, merged