3단계 - 세션 구현하기
NewKrew2021/jwp-was-kakao pull request #18
Opened 2020-12-17 05:44 UTC by dongjoon1251

2020-12-21 21:48 UTC, htrucci requested changes
리뷰가 늦어 죄송합니다 ㅠ_ㅠ 🙏 
마지막 단계인 세션을 잘 구현해주시고 관련 테스트 코드도 꼼꼼히 짜신 것 같습니다.
몇가지 코멘트 남겨놓았고 /user/list 접근시 model 셋팅이 안되고있어 재확인 부탁드릴게요~!

2020-12-21 21:48 UTC, htrucci commented on src/main/java/controller/UserController.java
> +    private boolean isLogined(HttpSession httpSession) {
Controller에 isLogined가 구현되어있는데요.
해당 로직이 Controller에 있는 것은 확장성이 떨어지는 것 같습니다.
값을 묻는것보다 값을 가진 HttpRequest 혹은 HttpSession에게 시키면 어떨까요? 
( TellDontAsk : https://martinfowler.com/bliki/TellDontAsk.html )

2020-12-21 21:48 UTC, htrucci commented on src/main/java/webserver/Dispatcher.java
> +    }
dispatcher가 아닌 HttpRequest에 물어봐야하는 기능 같습니다.

2020-12-21 21:48 UTC, htrucci commented on src/main/java/webserver/Dispatcher.java
> +        }
메서드 필드가 추가되면서 리플렉션 사용으로 인하여 어플리케이션 가독성이 떨어지고 불안정해진 것 같네요! ㅠ
아래 requireRequestAndResponseAndModelAndSession 로 추가된 코드들은 최소한 하나의 메서드로 정리가 되면 좋을 것 같습니다.

혹은 

컨트롤러내 함수 인자중 Model model, HttpSession httpSession 를 제거하고
HttpRequest request, HttpResponse response 만 인자로 선언되도록 공통화 할 수 있을 것 같아요.

2020-12-21 21:48 UTC, htrucci commented on src/main/java/webserver/HttpSession.java
> +    public HttpSession(String id, Map<String, Object> data) {
of를 통해 초기화되므로 생성자는 private이 되어야 하곘네요

2020-12-21 21:48 UTC, htrucci commented on src/test/java/webserver/HttpSessionTest.java
> +}
👍  테스트코드를 잘 짜주셨네요!

2020-12-21 21:48 UTC, htrucci commented on src/main/java/webserver/request/HttpRequest.java
> +                .filter(cookie -> cookie.getName().equals("sessionId"))
"sessionId"가 상수화되지 않고 각각 사용되고 있습니다~!
ResponseHeader, HttpRequest

2020-12-21 21:48 UTC, htrucci commented on src/main/java/webserver/response/HttpResponse.java
> +    }
sessionId를 주입받지않고 HttpRequest에게 직접물어 처리하도록 해도 좋을 것 같아요~!

2020-12-21 21:48 UTC, htrucci commented on src/main/java/webserver/SessionRegistry.java
> +    private Map<String, HttpSession> sessionMap = new HashMap<>();
HttpSession객체의 생성, 삭제, 응답 등을 처리하도록 역할을 주고 SessionManager 라는 명칭을 써도 좋을 것 같아요~!

2020-12-23 02:08 UTC, dongjoon1251 commented
> 리뷰가 늦어 죄송합니다 ㅠ_ㅠ 🙏
> 마지막 단계인 세션을 잘 구현해주시고 관련 테스트 코드도 꼼꼼히 짜신 것 같습니다.
> 몇가지 코멘트 남겨놓았고 /user/list 접근시 model 셋팅이 안되고있어 재확인 부탁드릴게요~!

@htrucci 어떤 환경으로 테스트하셨나요? 저는 잘 동작합니다. 회원가입을 해야 /user/list에 내용이 나오는데 회원가입후에도 리스트가 출력되지 않나요?

2020-12-23 02:18 UTC, dongjoon1251 commented on src/main/java/controller/UserController.java
> +    private boolean isLogined(HttpSession httpSession) {
@htrucci  HttpSession이 값은 가지고 있지만 로그인 여부를 확인시켜주는 역할은 아닌 것 같습니다. 사용자가 HttpSession을 가져다가 사용한다고 했을 때, 세션의 어떤 필드를 기준으로 로그인 여부를 확인할지 체크하는 부분은 세션과는 분리가 되어야 한다고 생각합니다. 이전단계 미션에서도 말씀드렸지만, 인증이 필요한 요청들에 대해서 따로 필터링 하는 AuthenticationFilter를 사용자가 정의해서 사용하는게 더 낫다고 생각합니다.

2020-12-23 03:11 UTC, dongjoon1251 commented on src/main/java/webserver/Dispatcher.java
> +        }
HttpSession을 파라미터로 받던 부분을 삭제했습니다. Model 도 안받게 하려고 수정하다보니 return type이 어떤지 또 분기를 타야해서 이부분은 유지시켰습니다.

2020-12-27 07:28 UTC, htrucci approved these changes
많이 부족한 피드백임에도 적극적으로 반영해주셔서 감사합니다. ^^👏 
3단계 모든 요구사항이 잘 반영되어 동작되는 것 확인하였고 머지하도록 하겠습니다.
고생하셨고 다음 미션도 화이팅입니다~! 🎉  🎉

2020-12-27 07:29 UTC, merged