[step1] HTTP 웹 서버 구현
NewKrew2021/jwp-was-kakao pull request #2
Opened 2020-11-23 12:03 UTC by karian7

[1단계 HTTP 웹 서버 구현](https://edu.nextstep.camp/s/6czWWFk0/ls/3QAg8cs3)을 진행하였습니다.

아래 내용을 참고해서 리뷰해 주시면 감사하겠습니다.
* 커밋을 최대한 분리하였습니다. 커밋단위로 보시면 도움이 되실 수 있을것 같습니다.
* 요구사항을 구현해 나가면서 `RequestHandler` 가 비대해 졌는데 추후에 리펙토링이 있을것을 예상하여 강하게 분리하지 않았습니다.
* 그러나 리펙토링이 용이하도록 각 URI 별로 처리 메소드, Response 공통화등은 진행해 두었습니다.

카카오 리뷰어그릅내의 첫 리뷰네요. 잘 부탁드립니다. 😄 🙇

2020-11-23 12:48 UTC, dongjoon1251 requested changes
저도 같이 미션을 진행하고 있는 입장이라 코드를 보면서 '아 이부분은 이렇게 고쳐봐야겠다'라는 생각이 많이 들었습니다. ㅎㅎ 리뷰하면서도 많이 배우게 되네요. 이전 리뷰어님들의 리뷰를 참고해서 열심히 코멘트를 남겨보았는데요. 한번 확인 부탁드립니다 :)

2020-11-23 12:48 UTC, dongjoon1251 commented on README.md
>  * [텍스트와 이미지로 살펴보는 온라인 코드 리뷰 과정](https://github.com/next-step/nextstep-docs/tree/master/codereview)
요구사항 정리가 깔끔하게 되었네요 💯

2020-11-23 12:48 UTC, dongjoon1251 commented on src/main/java/utils/FileIoUtils.java
>          return Files.readAllBytes(path);
내부가 null일 경우,  NullPointerException이 발생하는데 아래와 같이 적용해서 메시지도 같이 나오게 하면 어떨까요? 
Objects.requireNonNull(str1,  "error message");

2020-11-23 12:48 UTC, dongjoon1251 commented on src/main/java/webserver/HttpRequest.java
> +            cookies = Streams.stream(COOKIE_SPLITTER.split(cookie)) //
오 Splitter를 써서 이렇게 처리할 수도 있군요. 배워갑니다 👍 
보다보니, 해당 코드 중간에 // 주석 없는 주석 표시가 있는데 큰 의미가 없다면 삭제하는게 어떨까요?

2020-11-23 12:48 UTC, dongjoon1251 commented on src/main/java/webserver/HttpRequest.java
> +        return null;
getUser가 필요한 코드라면 null을 리턴하는 대신에 Exception이 나게 하는게 어떨까요? :)

2020-11-23 12:48 UTC, dongjoon1251 commented on src/main/java/webserver/HttpRequest.java
> +            return new User(queryParams.get("userId"), queryParams.get("password"), queryParams.get("name"), queryParams.get("email"));
Map을 받아서 User를 만드는 정적 팩토리 메소드나 새로운 생성자를 추가해보면 어떨까요? :)

2020-11-23 12:48 UTC, dongjoon1251 commented on src/main/java/webserver/RequestHandler.java
> +                Response response = handleUserCreate(httpRequest.getUser());
path를 확인하는 조건문 전체를 메소드로 분리하고 response를 리턴하게 수정해보면 어떨까요? :)

2020-11-23 12:48 UTC, dongjoon1251 commented on src/main/java/webserver/RequestHandler.java
> +
http method, request path 등을 상수로 만들면 어떨까요? :)

2020-11-23 12:48 UTC, dongjoon1251 commented on src/main/java/webserver/RequestHandler.java
> +    private void response302Header(DataOutputStream dos, String location, List<String> headers) {
HttpRequest 만들어주신 것처럼 HttpResponse를 생성해서 전달하게 하면 응답을 쓰는 코드 중복을 줄여볼 수 있지 않을까요? :)

2020-11-23 12:48 UTC, dongjoon1251 commented on src/main/java/webserver/RequestParser.java
> +
혹시 의도적으로 줄바꿈을 하신건가요? 
한줄씩 분리되어 있어서 문의드립니다 :)

2020-11-23 12:48 UTC, dongjoon1251 commented on src/main/java/webserver/RequestParser.java
> +        }
RuntimeException 대신에 커스텀 예외를 만들어서 사용해보면 어떨까요? :)

2020-11-23 12:48 UTC, dongjoon1251 commented on src/main/java/webserver/RequestParser.java
> +                    .entrySet().stream() //
여기도 //가 있는데 ide에서 잘못 입력되어 보이는것 같기도 하네요. 확인 부탁드려요~

2020-11-23 12:48 UTC, dongjoon1251 commented on src/main/resources/templates/user/list.html
> +                  <th scope="row">{{inc @index}}</th> <td>{{userId}}</td> <td>{{name}}</td> <td>{{email}}</td><td><a href="#" class="btn btn-success" role="button">수정</a></td>
inc로 1을 증가시킬수 있었군요! 또 배워갑니다👍

2020-11-23 12:48 UTC, dongjoon1251 commented on src/test/java/utils/HandlebarsTest.java
> +        //@formatter:on
이 주석은 어떤 의미인가요?

2020-11-23 12:48 UTC, dongjoon1251 commented on src/test/java/utils/HandlebarsTest.java
> +    @DisplayName("리스트오 인덱스를 처리할 수 있다.")
리스트로 오타인 것 같습니다 :)

2020-11-24 01:26 UTC, karian7 commented on src/main/java/utils/FileIoUtils.java
>          return Files.readAllBytes(path);
네. IDEA 가 자동으로 고처주는걸로 썼었는데 앞으로 챙겨야 겠네요.
9d5fe0d 에서 반영하였습니다.

2020-11-24 01:30 UTC, karian7 commented on src/main/java/webserver/HttpRequest.java
> +            cookies = Streams.stream(COOKIE_SPLITTER.split(cookie)) //
이전 PR 에서(링크는 안찾아지네요 😓) fluent interface 사용시 한줄에 하나의 구문만 유지해달라는 피드백이 있었어요.
reformat 시에도 이 내용이 유지되도록 하기 위해 추가했던 주석인데요, 사실 저도 이 주석이 그리 맘에 들진 않았어요. 따로 공유하는 formatter 가 없어서 선택한 방법이었는데 그냥 아래 포맷 옵션 켜고 진행하겠습니다 😀 
![Capture 2020-11-24 오전 10 30 22](https://user-images.githubusercontent.com/247208/100034683-10d34d00-2e40-11eb-99d9-985de7d65365.jpg)
e5c809337e1e7ca03a8cf46c60a953be4e65a9bd 에서 반영하였습니다.

2020-11-24 01:31 UTC, karian7 commented on src/main/java/webserver/RequestParser.java
> +                    .entrySet().stream() //
https://github.com/next-step/jwp-was-kakao/pull/2#discussion_r529109806 와 동일한 내용으로 링크 남깁니다. 😀

2020-11-24 01:32 UTC, karian7 commented on src/test/java/utils/HandlebarsTest.java
> +        //@formatter:on
https://github.com/next-step/jwp-was-kakao/pull/2#discussion_r529109806 와 동일한 내용이에요.
intellij 에게 reformat 시 무시하라는 구문입니다. 😉 
![Capture 2020-11-24 오전 10 31 50](https://user-images.githubusercontent.com/247208/100034776-45df9f80-2e40-11eb-97c9-b4b21bff4daf.jpg)

2020-11-24 01:33 UTC, karian7 commented on src/test/java/utils/HandlebarsTest.java
> +    @DisplayName("리스트오 인덱스를 처리할 수 있다.")
웁스! 😔
a5e9b053eebb1f3b691874a2bc50ae5be8994216

2020-11-24 01:34 UTC, karian7 commented on src/main/resources/templates/user/list.html
> +                  <th scope="row">{{inc @index}}</th> <td>{{userId}}</td> <td>{{name}}</td> <td>{{email}}</td><td><a href="#" class="btn btn-success" role="button">수정</a></td>
내장 구문은 아니고 아래와 같이 헬퍼를 등록해줘야 해요. 😏
```java
handlebars.registerHelper("inc", (Helper<Integer>) (context, options) -> context + 1);
```

2020-11-24 01:37 UTC, karian7 commented on src/main/java/webserver/HttpRequest.java
> +        return null;
ed27323152873ae4841e8679c3585e185847150a 에서 반영하였습니다.
참고로, 커스텀 예외를 만들거나 테스트를 추가하는건 f243f9a5ec31c58d5a2741a8f9f3a1844bb00109 에서 기술한 바와 같이 추후 더 나은 구조로 리펙토링할것이 예상되어 아껴(?) 둡니다. 🙄

2020-11-24 01:38 UTC, karian7 commented on src/main/java/webserver/HttpRequest.java
> +            return new User(queryParams.get("userId"), queryParams.get("password"), queryParams.get("name"), queryParams.get("email"));
중복을 줄일 수 있겠네요. 0d2dc303a08819a59bc050d9a5569590aa240ffb 에서 반영하였습니다.

2020-11-24 01:49 UTC, karian7 commented on src/main/java/webserver/RequestParser.java
> +
의도는 아니었고, 리펙토링 하다 보니 그렇게 되었네요. 조금 더 개선해볼 부분이 보여서 897404d4203d6b8a03cd8e1c9e0bd4cc520c8e80 에서 리펙토링 해 보았습니다.

2020-11-24 01:52 UTC, karian7 commented on src/main/java/webserver/RequestHandler.java
> +                Response response = handleUserCreate(httpRequest.getUser());
네, 저도 이부분은 리펙토링할 필요성을 느끼고 있습니다. [다만 다음 스테이지 요구사항](https://edu.nextstep.camp/s/6czWWFk0/ls/ejPoBugH)이랑 겹치는것 같아서요. 다음 단계 PR 에서 좋은모습(?) 으로 찾아뵙겠습니다(?) ㅎㅎㅎ 😏

2020-11-24 02:06 UTC, karian7 commented on src/main/java/webserver/RequestHandler.java
> +
상수화에 대해서 고민할 부분이 조금 있습니다. (비록 리뷰어의 추가 피드백은 못받았지만 😞) https://github.com/next-step/java-lotto/pull/861#discussion_r522827831 에서 언급한 바와 같이 상수화 해야할 대상에 대해 고려하고 싶습니다. 해당 코맨트에서 언급한것 외에 오타를 줄여주는 부분도 나중에 생각했어요.

하지만 여기서 사용하는 `request path` 의 경우 그 자체가 의미를 가지므로 상수로 바꾸는 필요성을 느끼지 못했습니다. 예를 들면 `@GetMapping("/index")` 와 같은 상황에서 `"/index"` 문자열을 를 상수화 시키지 않는것과 같은 이유일 것 같아요. GET / POST 도 같은 이유가 있긴 한데요, 그래도 의견 주셨으니 바꿔봤습니다. 😀 다만 너무 간단한 구현이라 스프링이 만들어둔 걸 사용할께요! 😉 
96385e7ad172ef59594e37327e987ead1ff7b0bb 에서 반영하였습니다.

2020-11-24 02:08 UTC, karian7 commented on src/main/java/webserver/RequestHandler.java
> +    private void response302Header(DataOutputStream dos, String location, List<String> headers) {
이부분도 https://github.com/next-step/jwp-was-kakao/pull/2#discussion_r529120623 와 마찬가지로 애껴(?) 두고 다음 PR 에서 찾아뵙겠습니다. ㅎㅎ

2020-11-24 02:21 UTC, karian7 commented on src/main/java/webserver/RequestParser.java
> +        }
네~ a3be3cdcb6c852ba7327d4dbf6e8b76695a5013c 에서 반영하였습니다.

2020-11-25 04:42 UTC, dongjoon1251 approved these changes
코멘트들에 대해서 커밋링크까지 같이 남겨주신 친절함 덕분에 리뷰 반영을 금방 확인할 수 있었습니다.  👍 
머지하고 다음 단계로 진행하시죠 ㅎㅎ

2020-11-25 04:43 UTC, merged