1단계 - HTTP 웹 서버 구현
NewKrew2021/jwp-was-kakao pull request #21
Opened 2020-12-21 14:29 UTC by findstar

1단계 HTTP 웹 서버 구현입니다.

2020-12-22 14:18 UTC, sehan requested changes
안녕하세요. 니오 입니다. 😉
1단계 요구사항을 잘 구현해주셨습니다. 💯 👍 

모듈구조상 개선하면 좋을 몇가지 코멘트를 남겨두었습니다.  필수수정요청은 아닙니다. ☺️

기능확인을 하다가 한가지 수정해야 할 부분이 있어서 Request changes 드립니다.
* 회원가입시 url encode 되어 전달된 값 ( 한글또는 @ 같은 문자들 ) 이 decode 되지 않은 상태 그대로 저장되고 있습니다. 이 부분만 수정해주시면 될거 같습니다.

2020-12-22 14:18 UTC, sehan commented on src/main/java/model/User.java
> +
domain 과 webserver 모듈 분리를 위해 User model 에 추가된 static factory 매소드를 domain 모듈 외부로 분리 하는것은 어떨까요? 😄

2020-12-22 14:18 UTC, sehan commented on src/main/java/model/User.java
> +
User 를 생성하기 위해 요청받은 parameter 에 대한 검증책임을 User model 에 두기 보다는 request 를 처리하는 객체에게 책임을 주는것은 어떨까요? 😊

2020-12-22 14:18 UTC, sehan commented on src/main/java/webserver/ResponseHandler.java
> +
handle() 매소드에서 request 의 모든 비지니스를 처리하고 있네요.
2단계 리팩토링에서 집중적으로 리팩토링 해주시면 될거 같습니다. 😉

2020-12-24 13:04 UTC, findstar commented
URL decode 추가했습니다. 
나머지 코멘트는 2단계 리팩토링에서 더 고민해보도록 하겠습니다. 
감사합니다. 💯

2020-12-24 13:08 UTC, sehan commented
수정요청 잘 반영해 주셨네요.  👍 

이번 미션은 merge 하겠습니다. 고생하셨습니다. ☺️

2020-12-24 13:08 UTC, merged