[corby.kim] HTTP 웹 서버 구현 step1-2 코드리뷰 요청드립니다.
NewKrew2021/jwp-was-kakao pull request #26
Opened 2021-02-02 09:13 UTC by ddaaac

안녕하세요 크리스! 코비라고 합니다 😀

이번 미션 잘 부탁드립니다 :)

2021-02-03 05:33 UTC, kriery requested changes
안녕하세요 코비, 리뷰를 맡게된 크리스입니다.
요청 및 응답을 처리하는 객체나 해당 객체를 구성하는 서브 객체들의 구성이 적절했네요.
다만 exception의 catch 문제나, 데이터의 흐름에 대해서 몇가지 피드백을 드렸어요.
피드백 확인하시고 다시 뵐게요~

2021-02-03 05:33 UTC, kriery commented on build.gradle
> +    implementation 'org.reflections:reflections:0.9.12'
나중에 쓸려고 넣으신거죠? (아직은 쓰는데가 안보이네요)

2021-02-03 05:33 UTC, kriery commented on src/main/java/utils/FileIoUtils.java
> +            throw new RuntimeException("파일을 읽어올 수 없습니다.");
1. `RuntimeException`을 그냥 이용하기 보단, 새로운 Exception을 정의해서 이용하면 어떨까요?
1. 여기서 runtime exception의 일종인 `NullPointerException`이 발생할 수도 있어요.
(ex: filePath가 존재하지 않는 경로를 포함하고 있으면 `getResource` 부분에서 null이 반환되고 .toURI에서 NPE가 throw됩니다)

대게 없는 경로에 대한 요청은 404를 반환하고,
경로에 해당하는 리소스는 있지만 반환이 안되는 경우에 403, 408 또는 500을 리턴해요.
그러기 위해서는 1번과 2번 상황을 분리할 수 있어야겠죠?

2021-02-03 05:33 UTC, kriery commented on src/main/java/utils/IOUtils.java
> +    public static final String NEW_LINE = System.lineSeparator();
```suggestion
    public static final String NEW_LINE = "\r\n";
```
HTTP request / response 에서 행 구분에 `\r\n`(CR-LF) 대신 `System.lineSeparator()` 를 이용하고 있는데요.
`System.lineSeparator()` 는 OS별 기본 행구분자를 반환하기 때문에 통신 규약에 맞지 않을 수 있습니다.
ex) windows: `\r\n`(CR-LF), linux|Mac(>9): `\n`(LF), Mac(<=9): `\r`(CR)

반면에, HTTP 통신에서는 어떤 OS든 `\r\n`을 써야 합니다 (대체적으로 `\n`을 받아주기는 하지만 표준은 아니예요)
see also: https://tools.ietf.org/html/rfc2616#section-5

2021-02-03 05:33 UTC, kriery commented on src/main/java/utils/IOUtils.java
> +            throw new RuntimeException(e.getMessage());
미션 전반에서 이러한 코드(이름이 있는 `Exception`을 `RuntimeException`으로 변경하는)들이 많이 보이고 있는데요,
이렇게 발생시킨 `RuntimeException`을 받아주는 부분은 보이지가 않아요.
오류 발생시에 위험한 코드가 되지 않을까요?
예를 들어 WAS에 클라가 요청을 보내는 도중 끊고 나갔다면 (모바일 환경에서 충분히 일어날 수 있는 일이죠?),
통상 `bufferedReader.readLine` 에서 IOException - BrokenPipe 또는 IOException - Request timed out 이 발생할텐데요.
원래라면, `RequestHandler`까지 `IOException`이 전파되어 logger에 잡혔을 테지만,
지금은 runtime exception으로 변환되었기 때문에 `catch (IOException)` 에 잡히지 않고 프로그램 중단을 야기하고 있어요

2021-02-03 05:33 UTC, kriery commented on src/main/java/web/HttpHeaders.java
> +    private static final String DELIMITER = ": ";
`key:value` 형태(공백 없음)나, `key:     value` 형태(공백이 다수)는 header 처리가 원활하게 되지 않는군요

2021-02-03 05:33 UTC, kriery commented on src/main/java/db/DataBase.java
>      }
꼭 `Optional`로 반환할 필요가 있었을까요?

2021-02-03 05:33 UTC, kriery commented on src/main/java/utils/DecodeUtils.java
> +            throw new AssertionError();
굳이 `AssertionError`로 변경하신 이유가 있나요? `assert` 없이 `AssertionError`를 throw 하는것이 좀 이례적이라서..
`RuntimeException`과 마찬가지로 `AssertionError`도 catch 하는 부분이 없어서 프로그램 종료를 유발할 수 있습니다.

2021-02-03 05:33 UTC, kriery commented on src/main/java/handler/JsHandler.java
> +        return "text/html;charset=utf-8";
`javascript`의 `Content-Type`은 `application/js` 입니다.
see-also: https://developer.mozilla.org/ko/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

2021-02-03 05:33 UTC, kriery commented on src/main/java/handler/IcoHandler.java
> +        return "text/html;charset=utf-8";
```suggestion
        return "image/x-icon";
```

2021-02-03 05:33 UTC, kriery commented on src/main/java/handler/IcoHandler.java
> +        return FileIoUtils.loadFileFromClasspath("./templates" + httpUrl.getUrl());
`ico` 파일도 binary 형태라서 font 처럼 8859-1 인코딩을 적용해줘야 할것 같아요.
그전에,
`FileIoUtils.loadFileFromClasspath`는 원래 `byte[]`를 반환하게 했는데
이걸 꼭 `String`으로 변경해야 할 필요가 있을까요? 흐름을 살펴보면,
- `Files.readAllBytes`: `byte[]`: **원본**
- `FileIoUtils.loadFileFromClasspath`: `String`
- `FileHandler.getBody`: `String`
- `FileHandler.service`: `String`

`service`에서 반환한 `String`을 `RequestHandler.writeResponse`에서는, 다시 `byte[]`로 변환해서 이용합니다.
이 흐름에서 `String`은 중간 매개체 역할만 하고 있는것 같은데요. 처음부터 `byte[]`를 그대로 이용하면 안되는 걸까요?

2021-02-03 15:29 UTC, ddaaac reviewed
리뷰 감사합니다 👍 
매번 리뷰 받을 때마다 많이 배워가는 것 같아서 좋네요 ㅎㅎ

이거 저거 해보고싶은 건 많지만, 해보다가는 끝도 없을 것 같아서 제출합니다!
구조적으로 고치면 좋을 것 같은 부분도 피드백 주시면 감사하겠습니다 🙇‍♂️

2021-02-03 15:29 UTC, ddaaac commented on build.gradle
> +    implementation 'org.reflections:reflections:0.9.12'
아마 도전 미션에 사용하기 위해 포비가 넣어놓은 것 같습니다 :)

2021-02-03 15:29 UTC, ddaaac commented on src/main/java/db/DataBase.java
>      }
클라이언트쪽에서 null처리를 하는 것보다 Optional로 없을 때의 처리를 강제하고 싶었습니다!
이 편이 DB또는 Repository의 책임에 맞다고 생각하는데 어떻게 생각하시는지 궁금합니다 😀

2021-02-03 15:29 UTC, ddaaac commented on src/main/java/handler/IcoHandler.java
> +        return FileIoUtils.loadFileFromClasspath("./templates" + httpUrl.getUrl());
저도 불필요한 변환이 여러번 일어나는 것 같아 조금 불편했지만, `HttpBody`의 필드 타입이 String이라서 어쩔수 없이 변환했습니다.
그래서 `HttpBody`의 필드 타입을 byte[]로 변환해서 해결했습니다. 처음엔 필드 타입을 제네릭으로 해결하려고 했는데, 코드가 너무 복잡해져서 😓 `BodyMapper`를 따로 둬서 해결하였습니다~

2021-02-03 15:29 UTC, ddaaac commented on src/main/java/utils/DecodeUtils.java
> +            throw new AssertionError();
URLDecoder가 UTF-8 인코딩에 대한 변환을 지원하기 때문에 해당 예외가 발생할 일이 없지만
`UnsupportedEncodingException`은 Checked Exception이라 처리가 반드시 필요하여
 있을 수 없는 예외다 라는 의미에서 `AssertionError`가 어떨까 하고 사용했습니다.

여기도 커스텀 예외를 넣어주는 편이 나을까요?

2021-02-03 15:29 UTC, ddaaac commented on src/main/java/utils/IOUtils.java
> +    public static final String NEW_LINE = System.lineSeparator();
감사합니다! 이런 내용은 처음 봤어요 :)

2021-02-03 15:29 UTC, ddaaac commented on src/main/java/utils/IOUtils.java
> +            throw new RuntimeException(e.getMessage());
ExceptionHandler로 한번 감쌌습니다. 꼼꼼한 리뷰 감사합니다 👍

2021-02-03 15:29 UTC, ddaaac commented on src/main/java/web/HttpHeaders.java
> +    private static final String DELIMITER = ": ";
`key: value` 형태를 반드시 사용해야 되는줄 알았는데, [찾아보니](https://tools.ietf.org/html/rfc2616#section-4.2) 공백이 없어도 되고, 여러개가 있어도 되네요. 감사합니다!

위 문서를 보니깐 헤더 파싱 조건은 좀 더 복잡한 것 같던데, 이번 미션에서는 이정도면 괜찮겠죠? 😅

2021-02-03 15:45 UTC, ddaaac commented on src/main/java/utils/FileIoUtils.java
> +            throw new RuntimeException("파일을 읽어올 수 없습니다.");
이 부분을 인지하지 못하고 있었네요. 감사합니다!

2021-02-04 02:35 UTC, kriery commented on src/main/java/utils/IOUtils.java
> +            throw new RuntimeException(e.getMessage());
전 `RequestHandler`를 고치실거라 생각했는데 신박하네요 ❤️

2021-02-04 02:36 UTC, kriery commented on src/main/java/utils/IOUtils.java
> +    public static final String NEW_LINE = System.lineSeparator();
사실 이 표준안을 다 지키려면... 구현이 골치아파지는 것들이 있어서..
실재 제품으로 나오는 것들도 다 안지키는 경우들이 많아요.. 참고만 하셔도 됩니다 :)

2021-02-04 02:44 UTC, kriery commented on src/main/java/web/HttpHeaders.java
> +    private static final String DELIMITER = ": ";
네 사실 헤더 이용시에는.. 같은 key에 value가 여러개 붙는 경우도 있을 수 있어서.. (Cookie헤더나 Set-Cookie헤더가 그렇지요)
실재 구현에서는 `Map<String, List<String>> headers` 처럼 되어 있어요.
물론 언급하신대로 이번 미션에선 거기까지는 안해도 됩니다 😄

2021-02-04 03:16 UTC, kriery commented on src/main/java/db/DataBase.java
>      }
처리의 강제는.. 
ex) 
- 로그인 된 사용자 정보를 Repository에서 가져오기 => **로그인 된 사용자**는 이미 DB에 들어있어야 하니까 이 요청은 Not null이어여 함
- 가입을 위해 이미 등록된 사용자가 있는지 찾아보기 => DB에 있을 수도 있고 없을 수도 있는 요청을 하기 때문에 Nullable이 맞음

경우에 따라 선택할 수 있는 문제라서 항상 어느쪽에 책임이 있다고 하기는 좀 어려워요.
하지만 Not null로 처리하는게 맞다고 판단될 때 라면,
지금처럼 `Optional`로 하기보단 명시적으로 `Exception`을 던져주는게 더 이해하기 편하다고 생각해요.

2021-02-04 03:25 UTC, kriery commented on src/main/java/utils/DecodeUtils.java
> +            throw new AssertionError();
있을 수 없는 예외라는 부분에 저도 동의합니다.
다만 이미 충분히 고려되었지만 문법적으로 checked exception을 잡아야만 하는 경우에는
보통 block을 비우고 argument 명을 ignored 따위로 씁니다 (IDE에서 warning 날리지 말라고..)
이 부분을 피드백 한 이유는 사실, `Exception`과 `Error`의 차이 때문이었어요.
Java의 `Throwable`은 `Exception`과 `Error`가 있는데, (`AssertionError`는 `Error`입니다)
catch를 해주길 바라는 `Exception`과 달리 `Error`는 catch하지 말라는 의미해요 (잡자면 못잡을것도 아니긴 합니다만..)
의도적으로 `Exception`을 날리고 싶으면, 차라리 `RuntimeExcpetion`을 subclassing 하면 어떨까 합니다.

> The class **Exception** and its subclasses are a form of Throwable that indicates conditions that a reasonable application **might want to catch**.
https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html

> An **Error** is a subclass of Throwable that indicates serious problems that a reasonable application sh**ould not try to catch**. Most such errors are abnormal conditions. 
https://docs.oracle.com/javase/8/docs/api/java/lang/Error.html

2021-02-04 03:27 UTC, kriery approved these changes
안녕하세요 코비, (늦은 밤에 작업을..)
피드백 반영한 내용 잘 봤습니다. 코비의 코멘트에 답글로 달아두신것 확인하셔요
(Resolved conversation은 열어서 확인하셔야 합니다)
이대로 머지할게요, 그럼 다음 스탭에서 봐요~

2021-02-04 03:27 UTC, merged

2021-02-05 06:55 UTC, ddaaac commented on src/main/java/db/DataBase.java
>      }
DB 또는 Repository 입장에서는 사용자의 로그인 여부와 상관없이 값을 찾아주는게 좋지 않을까 싶어서 위와 같이 구현했습니다.

그래서 DB 입장에서는 찾는 값이 없으면 
  1. null을 반환하는 메서드
  2. 예외를 발생시키는 메서드

두가지 메서드를 모두 만들 수 있다고 생각하는데
이 상황에서는 **예외로 로직을 처리하고 싶지 않아서** null을 반환하는 메서드를 사용하는 것이 좀 더 적합하다고 생각했습니다.
[find vs get](https://tuhrig.de/find-vs-get/) 글을 따라서 find라는 메서드명을 사용했구요 😀