[huey.j 전준호] WAS 미션 Step2 코드리뷰 부탁드립니다.
NewKrew2021/jwp-was-kakao pull request #27
Opened 2021-02-02 09:13 UTC by jh280722

안녕하세요 휴이입니다.
was 미션의 피드백을 맡아주셔서 감사합니다.

이번에 was 미션을 진행하면서 스프링 없는 개발의 힘듦을 많이 느꼈습니다.
진행을 하면서 크게 2가지 의문점이 있어서 질문 드립니다.

1. 저번 리뷰를 받으면서 0,1 등도 의미를 갖는 상수처리를 해주라는 피드백을 받고 의미를 갖는 상수처리를 하기위해 노력중에 있습니다.
그런데 이번 미션에서 경로나 requestLine을 split하면서 0, 1 의 중복되는 상수가 많이 나오게 되었는데 이러한 방법이 맞는지, 처리를 어떻게 해야할지 고민이 들었습니다.

2. request에 경로에 따라 FileIoUtils.loadFileFromClasspath의 불러오는 경로가 templates, static으로 나누어지게 되는데 
저희는 확장자를 파싱하고 미리 map에 확장자를 넣어주어서 경로를 설정했습니다.
`        contentType.put("js", "text/javascript");
        contentType.put("css", "text/css");

        contentLocation.put("ico", "./templates/");
        contentLocation.put("html", "./templates/");`
폰트의 많은 확장자나 확장성을 고려할때 맞을까 생각이 들었고 폴더로 파싱을 하자니 폴더안에 확장자가 다를 경우는 어떻게 처리하나 싶어서 결국 확장자를 파싱하고 Optional로 넘겨주었습니다. 
하지만 점점 파일과 폴더가 많아지면 어떻게 처리를 해야하고 현재 사용한 방법이 맞는지가 궁금합니다.

2021-02-03 08:27 UTC, sehan requested changes
안녕하세요. HTTP 웹서버 리뷰를 맡은 니오입니다. ☺️

step1 이후 step2 리팩토링 후 설계가 많이 개선되었습니다. 👍 👍 👍 
그렇지만 아직 아쉬운 부분들이 좀 있습니다. 
application 로직이 was 쪽에 섞여 있는 곳이 많이 있습니다. was 관련 객체에 application 로직이 구현되지 않도록 집중적으로 리팩토링 해주시기 바랍니다. 

추가적인 리팩토링 코멘트를 남겨두었으니 확인 후 좀 더 리팩토링 진행해주세요 

수정요청드립니다.

2021-02-03 08:27 UTC, sehan commented on src/main/java/webserver/RequestHandler.java
> +        controllers.put("default", new DefaultController());
request uri 별 비지니스 로직 처리를 uri - controller 매핑으로 잘 정리 했네요 👍 👍 👍

2021-02-03 08:27 UTC, sehan commented on src/main/java/webserver/RequestHandler.java
> +        return Optional.ofNullable(controllers.get(uri));
Nullable 을 허용하는것 보다는 null 일 경우 DefaultController 를 넘겨주어 getController 가 return 으로 Null 을 하지 않도록 보장하는것이 더 좋은 방법입니다.

2021-02-03 08:27 UTC, sehan commented on src/main/java/controller/AbstractController.java
> +    }
추상 클래스에 추상 매소드가 하나도 없네요.  AbstractController 에 abstract 키워드가 필요가 없어졌습니다. 😊
추상화 과정에서 실수를 한 거 같네요.

service() 매소드 구현코드가 이곳에 있어야 하는데 하위 구현체로 내려가면서 중복구현이 발생했습니다.  하위 구현체에서 service() 메소드 상세구현을 모두 제거 하고 이곳에 추가 해주세요.
doPost, doGet 구현을 하위 상세구현에게 넘겨주려면 abstract 로 선언해야 하고 그렇지 않다면 AbstractController 에서 abstract 키워드를 제거 해주세요.

2021-02-03 08:27 UTC, sehan commented on src/main/java/webserver/Response.java
> +    }
확장자에 따른 contentLocation 이 Response 에 inline code 으로 고정되어 있습니다.  
확장자에 따른 resource 의 위치는 was 가 규정하지 않습니다.  즉, ico 확장자를 가진 파일의 위치는 application 개발시 ico 의 위치를 설정하면 was 는 ico 요청이 들어오면 설정된 ico 위치에서 ico 를 load 하여 response 로 제공하는 것입니다. 
즉, was 에 application 을 추가하여 application 이 서비스 되도록 하기 위해서 was 에게 application 설정정보(uri - servlet 매핑정보...etc) 를 제공해줘야 합니다. tomcat 을 예로 들어 보자면 web.xml 로 application 을 was 를 통해 어떻게 서비스 할지를 설정하게 됩니다. 

ice -> ./templates/  , html -> "./templates/" 와 같은 정보는 application 을 was 에서 서비스하기위한 application 설정정보에 해당합니다. Response 에서 application 의존적인 코드를 제거해 주세요.

2021-02-03 08:27 UTC, sehan commented on src/main/java/webserver/Response.java
> +        contentType.put("css", "text/css");
확장자에 해당하는 mime-type 정보는 enum 으로 추출해 볼 수도 있겠네요

MIME 타입은 아래에서 참고해 볼 수 있습니다.
https://developer.mozilla.org/ko/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

2021-02-03 08:27 UTC, sehan commented on src/main/java/webserver/Response.java
> +    }
1. 매소드가 하는일이 많습니다. 확장자 추출 뿐 아니라 content-type 을 찾아서 header 에 추가하는일 까지 하고 있습니다.  메소드를 분리 해주세요
2. 확장자를 분리하는 역할도 객체로 분리해내면 테스트 작성을 쉽게 만들어 줍니다.

2021-02-03 08:27 UTC, sehan commented on src/main/java/webserver/Response.java
> +    }
1. 사용자 목록을 location 으로 전달하는 기능의 매소드는 application 비지니스 로직 구현에 해당합니다.
Response 의 재사용성을 위해 제거 해주세요

2. Response 가 handlebar 를 직접사용하게 되면 handlebar 에 의존을 가지게 됩니다. 다른 template 엔진을 사용하려고 할때 확장성이 떨어지게 됩니다.  어떤 template 엔진을 사용하지를 결정하는것은 application 쪽 구현에 맡겨두고 was 에서는 application 개발자가 template 엔진을 사용하여 response 를 구성할 수 있도록 설계해야 합니다.

2021-02-03 08:27 UTC, sehan commented on src/main/java/webserver/Request.java
> +    }
Request 내에 InputStream 을 parse 하여 상태(headers, parameters, method, uri ) 를 만드는 기능과 상태를 외부로 제공하는 기능이 함께 구현되어 있습니다.  parse 하는 부분을 분리해서 Request 역할을 나누어 보면 좋겠습니다.

2021-02-03 08:27 UTC, sehan commented on src/main/java/webserver/Request.java
> +    private BufferedReader br;
InputStream 을 Parsing 하고 나면 상태로 유지할 필요가 없는 멤버 입니다.

2021-02-03 08:27 UTC, sehan commented on src/main/java/webserver/Request.java
> +        headers.put("Request-Line", getRequestLine(line));
Request-Line 은 Header 가 아니라 Http request Message 이 한 요소 입니다.
RFC 문서를 참고하면 도움이 될거 같습니다.
https://tools.ietf.org/html/rfc2616#section-5

2021-02-03 08:27 UTC, sehan commented on src/main/java/webserver/Request.java
> +
InputStream 에서 데이터를 parsing 할때 tokenize 방식으로 구현을 하게 되면 index 사용은 피할 수 없는 부분입니다.
0,1 과 같은 상수의 사용빈도는 중요하지 않습니다. Data 를 다룰때 의미있는 단위로 처리를 하는것이 중요합니다.
위에 선언된 상수를 봐서는 어떤 의미인지 전혀 감이 잡히지 않습니다.

getRequestLine() 을 예로 이야기 하겠습니다. 
RFC2616 에 따르면 https://tools.ietf.org/html/rfc2616#section-5.1 
```
# Request-Line 의 스팩은 다음과 같습니다.
Request-Line   = Method SP Request-URI SP HTTP-Version CRLF

정규표현식으로 하면 최대한 간략하게 이렇게 표현할 수 있습니다.
"(GET|POST)\\s(.+)\\s(.+)"
```

패턴매칭으로 처리해보면 다음처럼 표현이 가능합니다.
```java
final int METHOD = 1;
final int URI = 2;
final int HTTP_VERSION = 3;

parse(String line){
        Matcher matcher = requestLinePattern.matcher(requestLineString);
        method = HttpMethod.valueOf(matcher.group(METHOD));
        uri = URI.create(matcher.group(URI));
        httpVersion = matcher.group(HTTP_VERSION);
}
```

Request-Line 하나에만 집중하면 상수의 의미가 좀 더 명확해 집니다.

현재 Request 에는 모든항목(request-line, parameter, header..) 처리를 위한 상수들이 선언되어 있고 그 의미도 RFC 명세에 따른 것이 아니라 parsing 행위에 초점이 맞추어진 상수들입니다. 그래서 REQUEST_LINE_INDEX 와 같이 상수의 이름이 특색이 없고 으미가 모호합니다. 
 데이터 처리범위를 명확히 하고 각 처리역할을 객체로 분리해 내면 상수이름도 그 의미를 갖기 쉬워질 것입니다.

2021-02-03 08:27 UTC, sehan commented on src/main/java/webserver/Request.java
> +    }
k=v&k=v 형태의 queryString 을 parameter 객체로 변환해주는 객체를 만들어 주면 테스트작성도 가능해지고 Request 에서 코드도 분리해 낼 수 있습니다.

2021-02-03 08:35 UTC, sehan commented
> 1. 저번 리뷰를 받으면서 0,1 등도 의미를 갖는 상수처리를 해주라는 피드백을 받고 의미를 갖는 상수처리를 하기위해 노력중에 있습니다.
>    그런데 이번 미션에서 경로나 requestLine을 split하면서 0, 1 의 중복되는 상수가 많이 나오게 되었는데 이러한 방법이 맞는지, 처리를 어떻게 해야할지 고민이 들었습니다.

코멘트 댓글로 답을 드렸습니다.
https://github.com/next-step/jwp-was-kakao/pull/27#discussion_r569212208

> 2. request에 경로에 따라 FileIoUtils.loadFileFromClasspath의 불러오는 경로가 templates, static으로 나누어지게 되는데
>    저희는 확장자를 파싱하고 미리 map에 확장자를 넣어주어서 경로를 설정했습니다.
> 
> ```
>   contentType.put("js", "text/javascript");
>   contentType.put("css", `"text/css");
> 
>   contentLocation.put("ico",` "./templates/");
>   contentLocation.put("html", "./templates/");
> ```
> 
> 폰트의 많은 확장자나 확장성을 고려할때 맞을까 생각이 들었고 폴더로 파싱을 하자니 폴더안에 확장자가 다를 경우는 어떻게 처리하나 싶어서 결국 확장자를 파싱하고 Optional로 넘겨주었습니다.
> 하지만 점점 파일과 폴더가 많아지면 어떻게 처리를 해야하고 현재 사용한 방법이 맞는지가 궁금합니다.

contentType 의 경우 모든 타입을 명세하기에는 이번 미션이 전체 스팩을 구현하는 것은 아니라서 필요한 부분만 해주시면 될거 같습니다. 

request 경로에 따라 file 을 로드하는 부분은 아래 코멘트에 과련 내용을 남겨두었습니다.
https://github.com/next-step/jwp-was-kakao/pull/27/files#r569179859

2021-02-05 02:22 UTC, jh280722 commented on src/main/java/webserver/Response.java
> +    }
네 일단 컨트롤러에 역할을 넘겼는데요. application 설정정보를 어떻게 넘겨주는지를 잘 모르겠습니다.

2021-02-05 13:36 UTC, sehan commented on src/main/java/webserver/Response.java
> +    }
Controller 로 역할을 넘겼다면 이제 RequestHandler 로 그 역할을 넘겨 보면 어떨까요? 
AbstractController 에 추가된 contentLocation 을 보면 uri 에 따라 content 를 읽어오는 경로를 달리 해주고 있습니다. 
즉, "/templetes" 이하 에서 읽어오는경우, "/static" 이하 에서 읽어오는 경우 2가지 입니다. 

basePath 에 따라 resource 를 읽어오는 ResourceLoader(basePath) 객체가 있다고 한다면 이객체를 사용하여 Resource 를 서비스해주는 Controller 를 ResourceController 라고 할 수 있습니다. 
그렇다면 RequestHandler.inializeController() 에서 다음과 같이 할 수 있습니다.
```
    private void initalizeController() {
        ResourceController staticResourceController = new ResourceController(new ResourceLoader("/static"))
        controllers.put("/css/**", staticResourceController);
        controllers.put("/fonts/**", staticResourceController);
        controllers.put("/images/**", staticResourceController);
    }
```

현재는 매핑에서 패턴을 지원하지 않지만 이렇게도 풀 수 있습니다. .ico, .html 파일도 단순 resource 를 읽어들이는 것이라면 동일하게 RequestHandler 까지 역할을 옮겨 올 수 있습니다.

RequestHandler 까지 옮겨 왔다면 이제 WebServer 에서 RequestHandler 를 생성할때 controller mapping 정보를 주입받을 수도 있겠죠?  이제 WebServer 까지 올라오게 되었습니다. WebServer 에서는 이부분을 어떻게 외부로 빼낼 수 있을까요?  WebServer 객체 생성시 config 객체를 정의해서 받을 수도 있을거 같습니다.  

이제 AbstractController 에서 application 설정로직을 제거하고 AbstractController 도 webserver 패키지로 이동시켜 볼까요?

2021-02-06 00:50 UTC, sehan approved these changes
webserver 에서 application 로직(코드) 들을 분리작업을 잘 수행해주셨습니다. 👏👏👏

이전보다 한걸음 더 나아갔다면 그것만으로도 큰 의미가 있는 작업입니다. 이제 다시 또 한걸음 더 나아갈 단계 입니다. 한 호흡 쉬고 다시 또 앞으로 이전보다 더 큰 발걸음으로 나아가 주세요 😊


session 을 사용한 코드들은 controller 에 직접 호출되어 사용되고 있습니다. controller 에서는 HttpSession 이 필요할 뿐입니다. HttpSession 을 얻기 위해 sessionId 가 cookie 에 존재하는지 존재하면 HttpSessionStore 에서 가져오고 아니면 새로 생성하는 로직을 작성할 ( 또는 알아야할 ) 필요가 없어야 합니다. 

이외에 application 관련 로직이 webserver 에 구현되어 있는 부분들을 코멘트에 남겨 두었습니다. 
코멘트 확인 후 리팩토링을 더 진행해주시면 좋겠습니다. 

시간관계상 그리고 제 개인적인 스케줄 상 주말 리뷰가 가능할지 불확실하여 일단 PR 은 merge 하도록 하겠습니다. 하지만 merge 가 되었다고 개발자로써 huey 의 커리어가 끝나는건 아니듯이 리팩토링을 계속진행되어 스스로 만족할 만한 마무리를 지었으면 좋겠습니다. 

긴시간 고생하셨습니다. 앞으로 멋진 개발자로 성장하길 바랍니다. 😊

2021-02-06 00:50 UTC, sehan commented on src/main/java/model/MimeType.java
> +public enum MimeType {
content type 에 필요한 mimetype 을 enum 으로 잘 분리했습니다. 👍

2021-02-06 00:50 UTC, sehan commented on src/main/java/model/User.java
> +    }
도메인 모델에 Map 을 전달하여 parameter.get("userId") 같이 약속된 key 로 속성을 가져와 User 를 생성하는 것은 web 으로 받은 request param 에서 의존적인 코드입니다.  이 static factory method 는 제거 하는것이 좋습니다.

2021-02-06 00:50 UTC, sehan commented on src/main/java/controller/AbstractController.java
> +    }
static resource 를 location 에 따라 제공해주기 위해 작성된 코드. application 관련 설정로직들을 외부로 이동시키는 코멘트를 아래 댓글에 남겨 두었습니다.

https://github.com/next-step/jwp-was-kakao/pull/27#discussion_r570971241

2021-02-06 00:50 UTC, sehan commented on src/main/java/http/HttpResponse.java
> +    }
/user/list 를 처리하기 위한 view 로직(application 로직)이 webserver 모듈에 속하는 HttpResponse 객체에 구현되어 있습니다. 
이 메소드는 제거하는것이 좋습니다. 이 매소드로 인해 HttpResponse 의 재사용성이 떨어지게 됩니다.

userListForward() 에서 구현한 application 관련 로직들을 처리하기 위해 webserver 에서 제공해야 할 것과 application 이 구현해야 할 것의 의존을 제거해주면 webserver 에서 application 로직들을 제거할 수 있습니다. 

객체설계관점에서는 OCP 를 살펴보면 의존관계를 어떻게 제거 할 수 있을지에 대한 아이디어를 얻을 수 있을거 같습니다.

2021-02-06 00:50 UTC, sehan commented on src/main/java/controller/LoginController.java
> +                HttpSessionStorage.createHttpSession() : HttpSessionStorage.getHttpSession(httpSessionId);
HttpSession 을 생성하기 위해 request 에서 Cookie("sessionId") 를 꺼내서 null 체크 후 새로 생성할지 storage 에서 꺼내올지 처리하고 있습니다.  
좀 더 생각해 보면 request 에게 getSession() 해서 HttpSession 을 얻도록 한다면 HttpSession 을 가져오기 위한 로직들은 HttpRequest 에게 넘겨줄수 있습니다. 그럼 getCookie 로 값을 꺼내어 null 체크 하는 로직을  HttpSession 을 생성할때 마다 구현하지 않아도 됩니다.

2021-02-06 00:50 UTC, sehan commented on src/main/java/controller/ListUserController.java
> +        response.sendRedirect("/user/login.html");
session 을 이용한 로그인 체크 로직을 controller 에 직접 구현했습니다. 

로그인체크가 필요한 다른 URL 들이 추가된다면 어떻게 될까요? 지금 구성대로 라면 각 controller 마다 로그인 체크로직을 다 넣어줘야 합니다.  spring 의 interceptor 나 servlet 의 filter 개념을 활용하면 controller 에서 로그인 체크로직을 제거 할 수 있습니다. 

로그인 체크로직을 분리해보는 도전을 해보시겠습니까? 😊

2021-02-06 00:50 UTC, merged