[jamal.park] WAS Step2 리뷰 요청드립니다.
NewKrew2021/jwp-was-kakao pull request #28
Opened 2021-02-02 10:25 UTC by jypark5826

안녕하세요! 뉴크루 자말입니다.
리뷰 부탁드립니다:)

2021-02-03 02:48 UTC, dongjoon1251 requested changes
안녕하세요 이번 미션 리뷰를 맡게된 제노스입니다.
미션 수행을 잘 해주셨네요 👍 
몇가지 코멘트를 드렸으니 확인 부탁드려요 :)
추가로, 로그인 여부를 확인하는 부분을 한곳에서 수행하도록 리팩토링해보시면 좋을 것 같습니다. 새로운 API가 추가되었을 때 기존 코드에 어느정도의 영향이 있을지 같이 체크해주시기 바랍니다.

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/annotation/web/RequestMethod.java
> +
HTTP method가 있는지 찾기 위한 목적이라면 enum의 name() 메소드를 써보면 어떨까요?

2021-02-03 02:48 UTC, dongjoon1251 commented on README.md
> +
1단계 요구사항에 대한 기능을 넣는게 어떨까요?

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/annotation/web/RequestMethod.java
> +                .orElse(RequestMethod.NOTHING);
허용하지 않는 method로 요청온 것은 에러 상황으로 보입니다. 사용자에게 error response로 응답시켜주셔도 좋습니다.

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/controller/Controllers.java
> +public class Controllers {
멤버 변수가 없는 클래스는 전역 util 클래스로 만들어도 좋지 않을까요? 클래스의 이름은 controller의 일급컬렉션처럼 보여서 오해의 소지가 있어 보입니다 :)

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/controller/DispatchInfo.java
> +    public boolean matchWith(HttpRequest request) {
HttpRequest 클래스에서 비교해도 좋을 것 같습니다.

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/controller/Handler.java
> +
Handler 인터페이스를 잘 분리해주셨네요 👍

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/controller/UserController.java
> +        String logined = request.getRequestHeaders().getHeader("Cookie");
쿠키에 들어오는 값들이 여러개일 수 있습니다. 이를 위해 어떻게 처리하는게 좋을까요?
"Cookie", "Set-Cookie"등의 문자열을 controller에서 몰라도 사용이 가능하도록 리팩토링해주시기 바랍니다 :)

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/http/HttpRequest.java
> +
parsing 로직이 parser, HttpRequest, HttpRequestHeader, HttpUtil에 분산되어 있는 것 같습니다. 한쪽에서 처리하도록 리팩토링해주세요:)

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/http/HttpRequestHeaders.java
> +    Map<String, HttpRequestHeader> headers;
Map의 key는 header name, value는 content로 넣어도 될 것 같은데 value에 name, content를 같이 넣으신 이유가 있으실까요?

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/http/HttpRequestHeaders.java
> +            return null;
null 체크가 필요한 로직은 지양해주세요. Optional을 적용해주시거나 Exception을 발생하게 하는 것 등이 대안이 될 수 있습니다 :)

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/http/HttpResponse.java
> +
builder 패턴을 적용해주셨네요 👍 
builder에서 메소드명은 setXXX 보다는 set없이 쓰거나 with 등을 많이 사용합니다.
builder에 대한 예시를 좀더 찾아보셔도 좋습니다 :)

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/utils/IOUtils.java
> +                    } catch (UnsupportedEncodingException e) {
예외를 캐치한 후에 처리하지 않고 지나가지 않도록 주의해주세요:)

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/utils/IOUtils.java
> +
메소드를 구성하는 라인수가 많은데 줄여볼 수 있을까요?

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/utils/IOUtils.java
> +                .orElse(null);
null을 받아서 0으로 리턴하기보다 있으면 int형으로 변환하는 로직을 수행하고 없으면 0으로 만들어서 바로 리턴하면 어떨까요?

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/webserver/RequestHandler.java
> -            // TODO 사용자 요청에 대한 처리는 이 곳에 구현하면 된다.
내부 로직이 정리가 잘 되었네요. 👍 
다만 parser로 parse 한 다음에 parser를 넘겨주기보다 바로 HttpRequest를 만들 수 있는 값을 리턴해주면 어떨까요? 
아니면 HttpRequest를 바로 반환할 수 도 있을 것 같습니다.

2021-02-03 02:48 UTC, dongjoon1251 commented on src/test/java/http/HttpRequestTest.java
> +
테스트를 잘 작성해주셨네요 👍 
Response가 잘 만들어지는지와 Response가 OutputStream으로 잘 만들어지는지에 대한 테스트도 추가해주시기 바랍니다.

2021-02-03 02:48 UTC, dongjoon1251 commented on src/main/java/utils/TemplateUtils.java
> +        TemplateLoader loader = new ClassPathTemplateLoader();
loader, Handlebars를 매번 생성하지 않을 수 있을까요?

2021-02-03 14:37 UTC, jypark5826 commented on src/main/java/http/HttpRequestHeaders.java
> +    Map<String, HttpRequestHeader> headers;
생각이 짧았습니다 ㅎㅎ😅

2021-02-03 16:19 UTC, jypark5826 commented
정말 꼼꼼한 피드백 감사드립니다!
피드백 내용 고려하여 리팩토링 해보았습니다.
리뷰 부탁드립니다☺️

2021-02-04 09:15 UTC, dongjoon1251 approved these changes
피드백을 잘 반영해주셨네요 👍 
몇가지 코멘트를 드렸으니 다음 단계에 반영해주시기 바랍니다. 
이번 단계는 머지하도록 하겠습니다.

2021-02-04 09:15 UTC, dongjoon1251 commented on src/main/java/controller/StaticController.java
> +            .status("HTTP/1.1 200 OK")
status에 HTTP/1.1 부분이 중복으로 보입니다. controller에서는 HttpStatus객체만 알고 적용할수있게 리팩토링해보면 어떨까요?

2021-02-04 09:15 UTC, dongjoon1251 commented on src/main/java/controller/TemplateController.java
> +            .build();
두개의 handler가 중복으로 보입니다. 중복을 어떻게 하면 줄일 수 있을까요?

2021-02-04 09:15 UTC, dongjoon1251 commented on src/main/java/controller/UserController.java
> +        if (user != null && user.getPassword().equals(params.get("password"))) {
null 체크는 지양해주세요 :)

2021-02-04 09:15 UTC, dongjoon1251 commented on src/main/java/http/HttpRequest.java
> +                == RequestMethod.GET && (uri.startsWith("/css") || uri.startsWith("/fonts") || uri.startsWith("/images") || uri.startsWith("/js"));
== 보다는 equals를 사용해주세요 :)
그리고 static 요청을 위한 경로가 늘어나면 해당 코드도 늘어날 것으로 보입니다. 어떻게 개선할 수 있을까요?

2021-02-04 09:15 UTC, dongjoon1251 commented on src/main/java/http/HttpRequest.java
> +        if (isTemplateRequest() && request.isTemplateRequest()) {
이 조건들은 하나로 합쳐볼 수 있을까요?

2021-02-04 09:15 UTC, dongjoon1251 commented on src/main/java/http/HttpRequest.java
> +    private RequestMethod requestMethod;
RequestMethod로 잘 포장해주셨네요 👍 
Map 필드들도 일급 컬렉션으로 적용해보면 어떨까요?

2021-02-04 09:15 UTC, dongjoon1251 commented on src/test/java/utils/DispatcherTest.java
> +        HttpRequest request = new HttpRequestParser("GET /index.html HTTP/1.1\n" +
parsing에 필요한 inpustream 들도 text 파일로 분리해서 적용해보면 어떨까요?
test폴더 아래에 resource 폴더를 만들어서 사용되는 파일들을 저장해주시기 바랍니다.

2021-02-04 09:15 UTC, merged