[ian.lock 양정일] step 1~2단계 PR 요청드립니다
NewKrew2021/jwp-was-kakao pull request #29
Opened 2021-02-02 10:57 UTC by Jjungs7

안녕하세요 이안입니다! 이번 미션을 통해 프레임워크가 얼마나 많은 일을 담당해주고 있는지 다시 한번 깨닫게 되었습니다
최대한 알맞는 객체에게 역할을 위임하려 하였는데 이전 미션들과 프로젝트 구조가 달라서 맞게 한 것인지 헷갈리는 것 같아요
궁금한 사항은 코드 중간에 남겨놓을게요. 리뷰 잘 부탁드립니다!🙏

---

### 기능 목록
- repository 역할을 해줄 DataBase
- controller, service 및 user entity 를 관리하는 user package
  - 유저 생성, 유저 목록 조회, 로그인 기능을 각각의 컨트롤러가 담당
  - 유저 프로필 조회 기능은 현재 작동하지 않음 (세션 정보가 필요한 것 같아서 컨트롤러만 남겨두었습니다)
- webserver의 책임 일부를 위임받을 webserver의 domain 객체(Body, Controllers, HttpRequest, HttpResponse)
- 모든 controller의 부모 클래스가 되는 Controller와 AbstractController
  - 요청받은 method로 실행시켜주는 로직을 담당함
  - 단순 파일 요청에 대해서는 ForwardController가 담당

2021-02-02 11:09 UTC, Jjungs7 commented on src/main/java/webserver/domain/Body.java
> +            body = FileIoUtils.loadFileFromClasspath(getRootDirectory(path) + path);
1. `/index.html` 파일을 요청받았을 때 `./templates/index.html`로 접근해서 파일을 읽어와야하는데 앞에 `./templates` 경로를 어디서 붙여줘야할지 모르겠어요. 혹시 여기보다 더 적절한 위치가 있을까요?
2. `./templates/index.html`로 를 인자로 넘기면 파일을 읽더라구요. test 코드에서는 classpath가 project root인 것 같고 main으로 실행했을 때는 classpath가 `src/resources`인 것 같은데
  - 기본 classpath 설정이 있는 것인가요? 그렇다면 intellij가 해준것인지 아니면 jre 마다 설정이 있는 것인지 궁금합니다
  - main과 test 가 서로 다른 경로로 설정되어 있는 이유가 궁금합니다
혹시 추천해주시는 글이 있다면 읽어보도록 하겠습니다! 감사합니다 😃

2021-02-03 09:04 UTC, ljh131 requested changes
안녕하세요. 커멘트 몇가지 드렸습니다. 확인해보시고 궁금한게 있으시면 질문남겨주세요.

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/ui/AbstractController.java
> +package webserver.ui;
ui보다는 명확하게 컨트롤러의 의미를 나타내면 어떨까요

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/Body.java
> +package webserver.domain;
도메인이라기보다는 더 명확한 패키지 이름을 찾아보면 어떨까요? 그리고 도메인이라는 이름이 추상적이라서 서로 분리할 수 있는 패키지도 묶게된 것 같아요

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/Controllers.java
> +    }
웹서버는 프레임웍이라고 볼 수 있을텐데요. 프레임웍에 이런 비지니스 로직이 들어가지 않는게 좋을 것 같습니다.

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/Body.java
> +    private static final HashMap<String, String> contentTypes = new HashMap<String, String>() {{
static final은 네이밍을 다르게 하면 어떨까요

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/HttpRequest.java
> +        if (token.length < 3) {
상수를 쓰면 좋겠습니다

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/HttpRequest.java
> +    private void checkValidRequest(String[] token) {
이름이 명확하지 않는 것 같은데요. 파라매터의 token이 구체적으로 뭔지, 메서드 이름도 request라면 요청 메시지 전체를 기대하는 느낌이에요.

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/HttpRequest.java
> +            int contentLength = Integer.parseInt(headers.getOrDefault("Content-Length", "0"));
상수를 쓰면 좋겠습니다. 그리고 헤더 이름이 lower case면 어떻게 되나요?

2021-02-03 09:04 UTC, friediceday commented on src/main/java/user/view/UserView.java
> +            String userProfile = template.apply(UserService.findById(userId));
매번 초기화하고 컴파일 할 필요는 없을 것 같아요

2021-02-03 09:04 UTC, friediceday commented on src/test/java/user/view/UserViewTest.java
> +public class UserViewTest {
user 패키지에 대한 integration 테스트를 다양하게(성공, 실패) 추가해보면 좋겠습니다

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/Body.java
> +    private String getRootDirectory(String path) {
파일 확장자에 따라서 디렉토리가 달라지는건 별로 명확하지 않을 것 같아요. 프레임웍 부분이니 서비스가 넘겨주는 명확한 경로를 그대로 사용하는 역할만 하면 될 것 같은데 이렇게 되면 서비스 영역과 엮인다고 볼 수 있지 않을까요.

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/Body.java
> +            body = FileIoUtils.loadFileFromClasspath(getRootDirectory(path) + path);
1 -> 다른 커멘트에서 답변이 되었으리라 봅니다.
2 -> 직접 확인해보시면 좋겠습니다.

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/Controllers.java
> +        controllers.getOrDefault(processedPath(httpRequest.getPath()), controllers.get("*"))
나머지 기타 경로는 forward controller에서 파일을 서빙하게 되어있는데, 보안상 좋지 않을 것 같습니다. 등록된 경로만 하는게 좋을 것 같습니다.

2021-02-03 09:04 UTC, friediceday commented on src/main/java/user/model/User.java
> +    private boolean isInvalidEmail() {
valid를 정의하고 밖에서 !를 하는건 어떤가요?

2021-02-03 09:04 UTC, friediceday commented on src/main/java/user/view/UserView.java
> +    public static byte[] getUserListHtml() {
아래와 많이 중복되는데 공통화 하면 좋겠습니다

2021-02-03 09:04 UTC, friediceday commented on src/main/java/user/model/User.java
> +            throw new IllegalArgumentException("Please check userId");
이렇게 에러가 발생하면 어떻게 되는건가요?
입력을 잘못한 경우 유저는 4xx 에러를 기대할텐데요.

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/HttpRequest.java
> +            throw new IllegalArgumentException(e.getMessage() + "\nError while reading body data");
유저는 메시지를 잘못보낸 경우 4xx를 기대할 것 같습니다.

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/HttpResponse.java
> +            throw new IllegalArgumentException("Body cannot be null");
이런 경우에도 에러 응답을 내보내주면 좋겠습니다.

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/HttpRequest.java
> +            String[] tokens = line.split(":");
참고로 헤더 값에 :도 들어갈 수 있습니다.

2021-02-03 09:04 UTC, friediceday commented on src/main/java/webserver/domain/HttpRequest.java
> +            headers.put(tokens[0].trim(), tokens[1].trim());
참고로 헤더는 중복된 이름으로 여러개가 있을 수 있습니다.

2021-02-04 07:37 UTC, Jjungs7 commented on src/main/java/user/model/User.java
> +            throw new IllegalArgumentException("Please check userId");
모든 controller에 exceptionHandler를 mapping하여 사용하도록 변경하였습니다!

2021-02-04 07:39 UTC, Jjungs7 commented on src/main/java/user/model/User.java
> +    private boolean isInvalidEmail() {
저도 처음에 긍정형으로 메소드를 선언하고 `!` 을 붙이는 식으로 작성했었는데 intellij의 `boolean method is always inverted` 워닝때문에 이렇게 작성하게 된 것 같네요 😂 이런 사소한 워닝은 그냥 무시해도 될까요?

2021-02-04 07:40 UTC, Jjungs7 commented on src/main/java/webserver/domain/Controllers.java
> +        controllers.getOrDefault(processedPath(httpRequest.getPath()), controllers.get("*"))
StaticController, ForwardController, DefaultController 세 가지를 두었는데 괜찮은지 확인 부탁드립니다!

2021-02-04 07:41 UTC, Jjungs7 commented on src/main/java/webserver/domain/Body.java
> +            body = FileIoUtils.loadFileFromClasspath(getRootDirectory(path) + path);
직접 실행하면서 확인해보겠습니다!

2021-02-04 07:45 UTC, Jjungs7 commented on src/main/java/webserver/domain/HttpRequest.java
> +            int contentLength = Integer.parseInt(headers.getOrDefault("Content-Length", "0"));
모든 key를 소문자로 정규화하여 사용하게 변경했습니다

2021-02-04 07:46 UTC, Jjungs7 commented on src/main/java/webserver/domain/Body.java
> +    private String getRootDirectory(String path) {
StaticController / ForwardController 로 나눠서 serving하도록 변경했어요!

2021-02-04 08:19 UTC, Jjungs7 commented on src/test/java/user/view/UserViewTest.java
> +public class UserViewTest {
이번 미션은 꼭 test를 먼저 작성하겠다고 마음은 먹었는데 생각보다 쉽지 않은 것 같아요... 아직 객체의 책임을 바로 떠올리는 연습이 잘 안 된 것 같습니다 ㅠㅠ 인수테스트까지 꼼꼼하게 작성하여 올려보았습니다!

2021-02-05 01:24 UTC, ljh131 commented on src/test/java/user/view/UserViewTest.java
> +public class UserViewTest {
이 미션에서 integration test라는 것은 웹서버를 띄워서 마치 브라우저처럼 http 요청을 보내고 응답을 받아서 확인해보는 테스트입니다. 다소 어려울 수 있습니다. 한번 해보시면 좋겠습니다.

2021-02-05 02:22 UTC, ljh131 requested changes
안녕하세요. 여러가지 커멘트 드렸는데 잘 수정해주셨습니다.
어려울 수도 있지만 추가적으로 더 고민해볼 수 있는 부분들 커멘트 드렸습니다. (프레임웍과 서비스의 분리, 통합 테스트, 예외 처리)

2021-02-05 02:22 UTC, friediceday commented on src/test/java/user/view/UserViewTest.java
> +public class UserViewTest {
이 미션에서 integration test라는 것은 웹서버를 띄워서 마치 브라우저처럼 http 요청을 보내고 응답을 받아서 확인해보는 테스트입니다. 다소 어려울 수 있습니다. 한번 해보시면 좋겠습니다.

2021-02-05 02:22 UTC, friediceday commented on src/main/java/webserver/service/ExceptionHandler.java
> +            controller.service(httpRequest, httpResponse);
다른 컨트롤러들을 래핑하는 방식으로 하셨는데요, 이것도 괜찮은 방법 같습니다. 컨트롤러는 이렇게 처리할 수 있습니다. 그런데 웹서버에서 발생하는 익셉션도 처리가 필요하지 않을까요

2021-02-05 02:22 UTC, friediceday commented on src/main/java/webserver/service/ManualRequestMapping.java
> +
이건 서비스 로직이니 서비스쪽에서 해주면 어떨까요

2021-02-05 02:22 UTC, friediceday commented on src/main/java/webserver/controller/ForwardController.java
> +        return path.endsWith(".html") || path.endsWith("favicon.ico");
프레임웍이 이런 확장자나 특정 파일 이름을 모르면 좋지 않을까요? 이 컨트롤러는 서비스에 있어도 될 것 같아요

2021-02-05 02:22 UTC, friediceday commented on src/main/java/webserver/controller/ForwardController.java
> +public class ForwardController extends AbstractController {
포워드라는 이름의 의미는 무엇인가요?

2021-02-05 02:22 UTC, ljh131 commented on src/main/java/webserver/service/ExceptionHandler.java
> +        } catch (IllegalUserValuesException | IllegalArgumentException e) {
그리고 이렇게 서비스 구현을 알아야 어떤 익셉션을 어떤 응답으로 매핑할지 알아야 하는데 더 좋은 방법은 없을까요. 예를 들어 프레임웍이 처리할 수 있는 익셉션(응답으로 매핑할 수 있는)을 정의해놓으면 서비스는 그 익셉션을 따라서 구현하는 방식은 어떨까요

2021-02-07 15:24 UTC, Jjungs7 commented
피드백을 반영해봤습니다! 최대한 중복되는 코드는 제거하려고 reflections를 사용해보았는데 올바르게 사용한지 확인 부탁드립니다
그 외에 인수 테스트도 추가했습니다

> 다른 컨트롤러들을 래핑하는 방식으로 하셨는데요, 이것도 괜찮은 방법 같습니다. 컨트롤러는 이렇게 처리할 수 있습니다. 그런데 웹서버에서 발생하는 익셉션도 처리가 필요하지 않을까요

위 피드백에서 웹서버에서 발생하는 익셉션이 어떤건지 말씀해주실 수 있을까요? 해당 익셉션이 어떤건지 떠오르지 않아서 아직 반영하지 못했습니다 ㅠㅠ

2021-02-08 05:13 UTC, ljh131 reviewed
마지막까지 수고 많으셨습니다. 커멘트는 참고해보시고요. 머지하겠습니다.

2021-02-08 05:13 UTC, friediceday commented on src/test/java/webserver/AcceptanceTest.java
> +class WebServerThread implements Runnable {
한 파일에 클래스 하나만 두는게 좋지 않을까요? 그리고 이너클래스로 해도 무방할 것 같습니다.

2021-02-08 05:13 UTC, friediceday commented on src/test/java/webserver/AcceptanceTest.java
> +        while (tryCount < MAX_NUMBER_OF_TRY_COUNTS) {
뭔가 문제가 있어서 이렇게 하신 것 같네요

2021-02-08 05:13 UTC, ljh131 commented on src/main/java/webserver/WebServer.java
> +    private static List<? extends RequestMapping> getAllRequestMappings() {
여기서 패키지를 명시하는 것보다는 어노테이션을 사용하면 해당 클래스에 선언가능하니 가독성 측면에서도 좋을 것 같아요

2021-02-08 05:13 UTC, ljh131 commented on src/main/java/webserver/service/TemplateController.java
> +public class TemplateController extends AbstractController {
이런 역할은 서비스가 맞지 않을까요

2021-02-08 05:13 UTC, ljh131 commented on src/main/java/webserver/RequestHandler.java
>          } catch (IOException e) {
예외 발생시 해당 요청에 대해 클라이언트가 응답을 받지 못하기 때문에 가능하면 에러 응답이라도 내려주는게 좋을 것 같습니다.

2021-02-08 05:13 UTC, ljh131 commented on src/main/java/user/view/UserView.java
> +    public static byte[] getUserListHtml() {
템플릿이 수없이 많아질 수 있기 때문에 메서드별로 만들지 않고 보통의 웹 프레임웍처럼 처리할 수 있으면 좋을 것 같습니다.

2021-02-08 05:13 UTC, merged