[step2] HTTP 웹 서버 리팩토링
NewKrew2021/jwp-was-kakao pull request #3
Opened 2020-11-30 06:39 UTC by karian7

[🚀 2단계 - HTTP 웹 서버 리팩토링](https://edu.nextstep.camp/s/6czWWFk0/ls/ejPoBugH)을 구현하였습니다.

힌트를 보지않고 나름 구현하고 나중에 힌트를 보니 일부 디테일이 다른방향으로 되어 있긴 하지만 크게 벗어나진 않는것 같습니다. 😓 
단계별로 리펙토링 해 나가다보니 커밋이 많아졌네요. 그럼 잘 부탁드립니다~ 🙇

2020-12-02 10:40 UTC, dongjoon1251 requested changes
요구사항대로 잘 나누어주셔서 크게 수정할 부분은 없어보입니다. 
같은 요청 URL에 대해서  Get, Post 등의 메소드 종류에 대한 처리가 추가되면 좋을 것 같습니다.
그리고 로그인 요청을 보낼 때, 잘못된 아이디, 패스워드를 입력한 경우 redirection 이 제대로 되고 있지 않습니다. 로그인에 실패하면 login=failed 로 쿠키를 업데이트 해주는게 어떨까요?
회원 가입 요청 후의 리다이렉션도 잘 작동하지 않습니다.
같이 확인 부탁드립니다.

2020-12-02 10:40 UTC, dongjoon1251 commented on src/main/java/webserver/RequestHandler.java
RequestMapping을 RequestHandler가 처음부터 가지고 있어도 되지 않을까요? 
주입받게 하다보니 WebServer에서 Controller까지 알게 되는 것 같습니다.

2020-12-02 10:40 UTC, dongjoon1251 commented on src/main/java/webserver/RequestHandler.java
추가로 ResponseHandler도 주입받지 않고 쓸 수 있지 않을까요? 
내부에 멤버 변수가 없어서 static 하게 메소드에 접근하는 것도 가능해 보입니다.

2020-12-02 10:40 UTC, dongjoon1251 commented on src/main/java/webserver/http/MimeType.java
> +    APPLICATION_JS("application/js", "js"),
Content Type을 거의 다 정의해 주셨네요 👍

2020-12-02 10:40 UTC, dongjoon1251 commented on src/main/java/webserver/http/ResponseStatus.java
> +    SEE_OTHER("302 Found"),
REDIRECT로 표현하는게 어떨까요? :)

2020-12-02 10:40 UTC, dongjoon1251 commented on src/main/java/webserver/ResponseHandler.java
> +    public void response(DataOutputStream dos, Response response) throws IOException {
response를  response한다는 의미가 조금 어색하게 느껴집니다.

2020-12-02 10:40 UTC, dongjoon1251 commented on src/main/java/webserver/RequestParser.java
- hasEntity메소드 내부를 Optional로 구현해보면 어떨까요?
- query parameter가 url에 있을 때는 queryParam으로 저장하고, body에 있을 때는 Entity로 저장하는데 둘다 query parameter로 저장하는게 어떨까요?

2020-12-02 10:40 UTC, dongjoon1251 commented on src/main/java/webserver/http/Response.java
> +    private final List<String> headers = new ArrayList<>();
Controller에서 Response를 만들때의 중복을 줄여보면 어떨까요?

2020-12-06 07:28 UTC, karian7 commented
전반적으로 테스트가 미흡했습니다. 리뷰 코맨트에 해당하는 수정사항은 이곳에 남기고 각 코맨트별 수정사항은 별도로 남기겠습니다.

> 같은 요청 URL에 대해서 Get, Post 등의 메소드 종류에 대한 처리가 추가되면 좋을 것 같습니다.

91c6a43b97b4ac6bc16943720c642f88d9bd3e58 18722d711936270f7ef20003a87137cf8ad02fde f3c182f79108170689550730b759ee018e093c29 289544d47880cedc64fcf0a42b3c02d427720d0e e9c2fae74bb62d8e06792fb980744b8f8977783c 에서 수정하였습니다.

> 그리고 로그인 요청을 보낼 때, 잘못된 아이디, 패스워드를 입력한 경우 redirection 이 제대로 되고 있지 않습니다. 로그인에 실패하면 login=failed 로 쿠키를 업데이트 해주는게 어떨까요?

유저가 존재하지 않는경우에 예외처리가 미흡했습니다.  2a9d07f79823eea40a5f7a560c8fb39e48e77661 에서 수정하였습니다.

> 회원 가입 요청 후의 리다이렉션도 잘 작동하지 않습니다.
회원가입 URI 에 오타가 있었습니다. 5f26720805d4295ac00b5aac927dc3daf1c8cdf5

2020-12-06 07:38 UTC, karian7 commented on src/main/java/webserver/RequestHandler.java
> RequestMapping을 RequestHandler가 처음부터 가지고 있어도 되지 않을까요?
> 주입받게 하다보니 WebServer에서 Controller까지 알게 되는 것 같습니다.

어플리케이션을 조립하는 부분(컨피규레이션)과 구동하는 부분으로 나누었을 때 `WebServer` 는 조립하는 부분이라고 판단하였습니다. 다만 저도 모든 설정을 WebServer 가 알아야 한다는 의미는 아닙니다. 별도의 설정파일을 만들고 설정파일 로더를 만들까도 생각했지만 오버인것 같아서 이곳에서 설정하도록 하였습니다. 반면에 RequestHandler 가 가지도록 하면 RequestHandler 는 모든 컨트롤러를 처리할 수 있는 추상화된 레이어인데, 특정 컨트롤러들을 의존하는 코드가 있게되는 부분은 좋지 않은 것 같습니다. 따라서 현 상태를 유지하고자 하는데요, 혹시 추가로 의견 있으시면 말씀 부탁드립니다. 😀 

> 추가로 ResponseHandler도 주입받지 않고 쓸 수 있지 않을까요?
내부에 멤버 변수가 없어서 static 하게 메소드에 접근하는 것도 가능해 보입니다.

d6eb253671b603b1ed9d9a77b51c278d436f61b8 에서 반영하였습니다.

2020-12-06 07:39 UTC, karian7 commented on src/main/java/webserver/http/ResponseStatus.java
> +    SEE_OTHER("302 Found"),
이부분은 http package 이므로 [http spec 에 따른 네이밍](https://tools.ietf.org/html/rfc2616)을 쓰는게 더 좋을것 같습니다 😀

2020-12-06 07:40 UTC, karian7 commented on src/main/java/webserver/ResponseHandler.java
> +    public void response(DataOutputStream dos, Response response) throws IOException {
그렇네요. 5fed5333da53b6310600dc9e58683ffaf8d5611d 에서 수정하였습니다.

2020-12-06 07:54 UTC, karian7 commented on src/main/java/webserver/RequestParser.java
> hasEntity메소드 내부를 Optional로 구현해보면 어떨까요?

오! 좋은 생각이에요. 076f56304f09174d7cd49dc15ba9a69f4b831518 에서 반영하였습니다. 코드가 훨신 간결해 졌네요 👍 

> query parameter가 url에 있을 때는 queryParam으로 저장하고, body에 있을 때는 Entity로 저장하는데 둘다 query parameter로 저장하는게 어떨까요?

이부분은 API 디자인 의도에 따라 유용성이 달라질 것 같습니다. 저는 둘을 구분하고 싶습니다. 대안으로, `HttpServletRequest` 과 유사하게 `getParameter` 를 추가하는것으로 바꿔 보았습니다. 3d5edf665d2a5d2ba7e599536846a9ac9cfc55a5 에서 반영하였습니다.

2020-12-06 08:10 UTC, karian7 commented on src/main/java/webserver/http/Response.java
> +    private final List<String> headers = new ArrayList<>();
중복이 있긴 합니다. 대안은 반복적으로 생성하는 Response 객체를 외부에서 주입해주는 방법이 있을 것 같습니다. 서블릿이나 Spring MVC 에서도 이런 방법을 사용하긴 하죠. 하지만 결과값을 답는 파라메터를 요구하는 메소드를 만들고 싶지 않았습니다. 클린코드에서도 출력인수는 직관적이지 않다고 말하고 있습니다. 
Controller 객체의 `execute` 함수를 실행한 결과를 Response 로 return 하는 직관성이 중복을 줄이는 것 보다 더 중요하다고 생각하였습니다.

2020-12-07 06:55 UTC, dongjoon1251 approved these changes
코멘트에 대해서 모두 의견을 주셔서 저도 도움이 많이 되었습니다. 
Response 중복은 빌더를 만드는게 어떨까 하고 말씀드린거였습니다. 
한번 검토 부탁드립니다 :)
두번째 미션은 머지하겠습니다.

2020-12-07 06:55 UTC, merged