[yell.ow] WAS 미션 Step2 리뷰 부탁드립니다!
NewKrew2021/jwp-was-kakao pull request #30
Opened 2021-02-02 12:48 UTC by idealgu

안녕하세요! 이번 WAS 미션 리뷰를 부탁드리게 된 옐입니다. 😃
이번 미션을 진행하며 지난 미션에서 써왔던 스프링 부트의 편리함에 대해 많이 느낄 수 있었던 것 같습니다.

미션을 진행하며 의문이 들었던 점은 다음과 같았습니다.
1. Response 의 경로 지정 및 content-type 지정을 위해 map을 이용해 location 및 content-type을 지정하도록 구현했는데, 확장성을 고려할 때 적절하게 구현했는지 의문이 들었습니다. 더 좋은 방법은 당장 떠오르지 않아 개선하지는 못했는데, 더 좋은 방식이 있을까요?
2. Request 에서 데이터를 파싱하며 코드의 가독성을 위해 split 하는 부분의 인덱싱 처리를 모두 상수화 하여 처리하였습니다. 같은 인덱스를 가짐에도 다른 의미로 사용되어 상수화를 하다보니 불필요하게 많아진 것은 아닌가 걱정이 되는데 코드 가독성을 위해 상수 처리가 적절한 방식일까요?

많은 피드백 부탁드립니다!! 감사합니다 😊

2021-02-03 15:01 UTC, limmmee-bonjour requested changes
안녕하세요 yell! 이번 미션을 함께 할 벨입니다 :)
미션 수행 깔끔하게 잘 해주셨습니다 👍  그런데 몇가지 수정하면 좋을 것 같아요 !
의미 없는 추상클래스가 정의되어 있고, was에 비즈니스 로직이 존재합니다.
관련해서 코멘트 드렸으니 확인해주세요! 궁금하신 부분이 있으시면 언제든지 DM 주세요!

2021-02-03 15:01 UTC, limmmee-bonjour commented on README.md
> +## 요구사항
요구사항 정리를 깔끔하게 잘 해주셨어요 👍

2021-02-03 15:01 UTC, limmmee-bonjour commented on src/main/java/utils/PathUtils.java
> +public class PathUtils {
사용되지 않는 클래스라면 지워주세요 :)

2021-02-03 15:01 UTC, limmmee-bonjour commented on src/main/java/webserver/Request.java
> +    }
Q. Request 에서 데이터를 파싱하며 코드의 가독성을 위해 split 하는 부분의 인덱싱 처리를 모두 상수화 하여 처리하였습니다. 
같은 인덱스를 가짐에도 다른 의미로 사용되어 상수화를 하다보니 불필요하게 많아진 것은 아닌가 걱정이 되는데 코드 가독성을 위해 상수 처리가 적절한 방식일까요?

A. 의미가 드러나지 않는 특정한 문자&숫자를 상수화 하는 방법은 좋다고 생각합니다 👍 
그런데 지금 상수화 한 의미가 잘 드러나고 있지 않은 것 같습니다.

Request-Line은 스펙상 Method SP Request-URI SP HTTP-Version CRLF 으로 정의됩니다.
스펙을 매치 패턴으로 정의하고 그에 맞게 Index 의미를 부여해주는건 어떨까요?

2021-02-03 15:01 UTC, limmmee-bonjour commented on src/main/java/webserver/RequestHandler.java
>      }
Optional을 리턴받으면 defaultController를 가져오는 것 같은데, 명확한 의도가 없다면 Optional을 리턴해주는 것 보다 메소드 내에서 처리해주는 게 좋습니다. 기본으로 defaultController을 리턴하게 하거나 exception 처리 해주세요!
[이 글](http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/)이 도움이 될거예요 :)

2021-02-03 15:01 UTC, limmmee-bonjour commented on src/main/java/controller/AbstractController.java
> +    }
구현 클래스 service 메소드에 중복이 있네요. 
아래 코드는 동작의 흐름을 나타내는 것 같은데요. 
해당 부분을 추상 클래스에 정의하여 템플릿 메소드 패턴을 적용해보는게 어떨까요? 
```
if (request.getMethod().equals("GET")) {
    doGet(request, response);
}
if (request.getMethod().equals("POST")) {
    doPost(request, response);
}
```

2021-02-03 15:01 UTC, limmmee-bonjour commented on src/main/java/webserver/Request.java
> +    }
key&value 패턴으로 parameter를 구하는 메소드는 Utils 클래스를 만들어서 사용해도 좋을 것 같아요 :)

2021-02-03 15:01 UTC, limmmee-bonjour commented on src/main/java/webserver/RequestHandler.java
> +        controllers.put("default", new DefaultController());
path와 controller를 초기화하여 잘 구현해주셨네요 👍

2021-02-03 15:01 UTC, limmmee-bonjour commented on src/main/java/webserver/Response.java
> +        contentLocation.put("html", "./templates/");
확장자에 대한 정의를 Enum 정도로 분리할 수 있어보여요 :)
그렇지만 현재 스펙에서는 해당 구조도 괜찮을 것 같습니다 👍

2021-02-03 15:01 UTC, limmmee-bonjour commented on src/main/java/webserver/Response.java
> +    }
Response에 불필요한 행동이 위치해 있는 것 같아요!
확장자 및 location에 따른 path를 만들어주는 것은 Response의 책임일까요? 
Response는 어떤 path인지 전혀 관심이 없을 것 같아요! 해당 부분을 분리해 봅시다!

2021-02-03 15:01 UTC, limmmee-bonjour commented on src/test/java/webserver/RequestTest.java
> +        assertEquals(request.getMethod(), "GET");
assertEquals 사용시 첫번째 param이 expected이고 두번째 param이 actual 입니다 :)

2021-02-03 15:01 UTC, limmmee-bonjour commented on src/main/java/webserver/Response.java
> +        Collection<User> users = DataBase.findAll();
User를 가져오는 부분이 Response에 위치해 있네요! 해당 부분은 비즈니스 로직인데 Resposne에 구현해주신 이유가 있을까요? 해당 부분 수정해주세요 :)

2021-02-04 05:20 UTC, idealgu commented
좋은 피드백 감사드립니다!! 😆
말씀해 주신 내용을 바탕으로 리팩토링을 진행해보았습니다.
알려주신 Optional 링크를 통해 Optional의 사용에 대해서도 정리할 수 있었습니다! 🙇‍♂️🙇‍♂️
다시 한번 많은 피드백 부탁드립니다!!

2021-02-05 01:03 UTC, idealgu commented
피드백을 받기 전에 세션 구현 미션도 함께 진행해서 리팩토링을 해보았는데 이부분도 함께 피드백 받으면 좋겠습니다!!!

2021-02-05 02:59 UTC, limmmee-bonjour requested changes
안녕하세요 yell! 벨입니다.
빠르게 피드백 반영해주셨네요 :) 요청드린 수정사항 아주 잘 반영해주셨어요 👍 👏 
그런데 로그인 후 쿠키셋팅이 정상적으로 이뤄지지 않은것 같은데 이 부분 먼저 확인 부탁드려요!
(코멘트에도 달아두었습니다.) 다른 부분도 의견 드렸으니 확인 해 보시고 수정 부탁드립니다.
궁금하신 부분이 있다면 언제든 DM 주세요.
그럼 좀 더 완벽한 코드를 위해 화이팅 입니다!!

2021-02-05 02:59 UTC, limmmee-bonjour commented on src/main/java/controller/AbstractController.java
> +    }
service에 controller의 흐름을 정리하여 상황에 맞게 동작하도록 반영해주셨네요 👍 💯 

추가로, 해당 미션에는 GET, POST만 구현 사항이지만
httpMethod에는 다양한 메소드들이 존재합니다. 각 method가 추가되었을 때 String으로 관리되는 것 보다는 Enum으로 관리되는게 더 좋겠죠? 😉

2021-02-05 02:59 UTC, limmmee-bonjour commented on src/main/java/controller/AbstractController.java
>      }
contentLocation, getContentLocation은 추상클래스에서 전혀 관심없는 로직일 것 같아요
controller는 url 메소드에 따라 controller를 찾아주는 역할로 보여집니다.
해당 로직은 따로 유틸클래스를 만들거나 적절한 클래스 위치 찾아 처리되는게 더 좋다고 생각하는데, yell은 어떻게 생각하시나요~?

2021-02-05 02:59 UTC, limmmee-bonjour commented on src/main/java/controller/ListUserController.java
>          }
Session으로 잘 처리해주셨어요 👍 
그런데 webserver를 돌려보니 로그인 한 후에도 user/list.html 페이지가 정상적으로 접근되지 않습니다.
session으로 cookie 셋팅이 잘 되었는지 확인 부탁드려요 !

2021-02-05 02:59 UTC, limmmee-bonjour commented on src/main/java/exception/InvalidRequestException.java
> +public class InvalidRequestException extends Exception{
적절한 커스터마이징 Exception 생성 좋습니다 👍

2021-02-05 02:59 UTC, limmmee-bonjour commented on src/main/java/utils/ParseUtils.java
> +public class ParseUtils {
ParseUtils를 생성해주셨네요. 잘 구현해주셨습니다! 👏 👏

2021-02-05 02:59 UTC, limmmee-bonjour commented on src/main/java/webserver/Request.java
>          }
패턴 매치를 사용하여 잘 구현해주셨어요 ! 👍

2021-02-05 02:59 UTC, limmmee-bonjour commented on src/main/java/webserver/Request.java
> +    public Cookie getCookie() { return cookie; }
사용되지 않는 메서드는 지워주세요 :)

2021-02-05 02:59 UTC, limmmee-bonjour commented on src/main/java/webserver/RequestHandler.java
> +        return controllers.getOrDefault(uri, controllers.get("default"));
Optional 제거 후 내부 로직에서 처리해 주는 부분 좋습니다 👍 💯

2021-02-05 02:59 UTC, limmmee-bonjour commented on src/main/java/webserver/Response.java
> +        addHeader("Content-Type", getContentType(ParseUtils.parseExtension(location)) + ";charset=utf-8");
해당 메서드는 User 객체 뿐만 아니라 다른 객체들도 사용할 수 있을 것 같은데요 :)
지금 현재는 Response에 User가 강하게 결합되어 있는 구조 입니다! 
제네릭을 사용하여 User 객체 뿐 아니라 다른 객체도 받아서 body로 사용할 수 있도록 개선해 봅시다!

2021-02-05 02:59 UTC, limmmee-bonjour commented on src/main/java/utils/ParseUtils.java
> +                .SimpleEntry<String, String>(splitLine[KEY_INDEX].trim(), splitLine[VALUE_INDEX].trim());
< String, String > 은 타입추론을 해주기 때문에 지워주셔도 무방합니다 😄

2021-02-05 02:59 UTC, limmmee-bonjour commented on src/test/java/utils/ParseUtilsTest.java
> +        assertThat(results.get("email")).isEqualTo("email@email.com");
assertThat().isEqualTo도 좋지만, 아래와 같이 확인하는 방법도 있습니다 :) 
```
assertThat(results).containsEntry("userId", "1234");
```

2021-02-05 02:59 UTC, limmmee-bonjour commented on src/test/java/utils/ParseUtilsTest.java
> +    @Test
테스트 메소드에 DisplayName을 붙여주는것이 좋습니다!
메소드 네이밍보다 DisplayName을 붙여주는게 가독성이 훨씬 더 좋고 테스트의 의도를 더 잘 나타냅니다 :) 

추가로, 해당 테스트케이스는 @CsvSource을 통해 더 간략하게 개선해볼 수 있을 것 같습니다 :)
Junit5에는 굉장히 다양한 테스트 어노테이션들이 추가되었습니다!
[해당 글](https://www.baeldung.com/parameterized-tests-junit-5)을 읽어보시면 추후 노가다? 없이 (ㅎㅎ) 간결한 테스트 케이스를 작성하실 수 있으실 거예요!

2021-02-05 05:04 UTC, idealgu commented on src/main/java/controller/ListUserController.java
>          }
시크릿 모드로 항상 테스트를 해서 잘 되는 것으로 판단하고 제출을 해버렸네요ㅠㅠ
쿠키에 key=value; key=value; 와 같이 다양한 값들이 들어가는 것을 고려하지 않고 구현을 해서 오류가 뜬 것 같습니다.
Request가 List<Cookie>를 가지도록 하고 필요한 Cookie를 getCookie(string name)으로 찾아 Session을 가져오도록 수정했습니다!

2021-02-05 05:30 UTC, idealgu commented on src/main/java/controller/AbstractController.java
>      }
Controller에서 완전한 location을 request에 넘기는 것에 집중하다보니 추상 클래스에 Location 찾는 기능을 구현했었습니다. 😅
말씀해주신 것 처럼 주어진 파일에 대한 위치만을 반환하는 Util 클래스를 만들어 해결하는 것이 더욱 맞는 것 같아 FileLocationUtils을 만들어 구현했습니다.

2021-02-05 06:17 UTC, idealgu commented
좋은 피드백 정말 감사드립니다!! 😊
피드백을 고려하며 리팩토링을 진행해 보았고, 세션 유지도 해결하여 반영했습니다!

2021-02-05 09:55 UTC, limmmee-bonjour approved these changes
안녕하세요 yell! 벨입니다.
코멘트 드린 부분 빠르게 잘 반영해주셨어요 👍 💯 
리팩토링도 깔끔하게 잘 해주셨네요 👏  더 이상 드릴 코멘트는 없어 여기서 미션 마무리 하도록할게요!
5주동안 미션 진행하시느라 너무 고생 많으셨습니다! 앞으로도 계속 성장하는 좋은 개발자가 되길 바랄게요. 화이팅입니다 :)

2021-02-05 09:55 UTC, limmmee-bonjour commented on src/main/java/webserver/HttpMethod.java
> +}
HttpMethod를 생성해주셨네요 👍

2021-02-05 09:55 UTC, limmmee-bonjour commented on src/main/java/utils/FileLocationUtils.java
> +public class FileLocationUtils {
FileLocationUtils 구현 좋습니다. 책임들이 각자 자리를 잡아가는 것 같네요 👍 💯

2021-02-05 09:55 UTC, limmmee-bonjour commented on src/test/java/utils/FileLocationUtilsTest.java
> +    }
CsvSoruce를 적용해서 테스트케이스 작성 💯

2021-02-05 09:55 UTC, limmmee-bonjour commented on src/main/java/webserver/Response.java
> +    public <T> void templateAndForward(String location, Collection<T> objects) throws IOException {
제네릭을 사용하여 해당 메서드를 유연하게 만들어주셨네요 👍 💯

2021-02-05 09:55 UTC, limmmee-bonjour commented on src/main/java/webserver/Request.java
> +    }
요구사항에 관련하여 cookie 관련 리팩토링도 잘 해주셨어요 👍

2021-02-05 09:55 UTC, merged