[yuni.code] WAS step 1~2 리뷰요청 드립니다.
NewKrew2021/jwp-was-kakao pull request #32
Opened 2021-02-03 01:10 UTC by dsyun96

안녕하세요, jay! yuni입니다.
이번 미션 잘 부탁드립니다 😄

2021-02-03 15:59 UTC, parkjoos requested changes
안녕하세요 
WAS 미션 리뷰를 하게된 jay 입니다. 반갑습니다. 😁

전체적으로 아주 깔끔하고 완벽하게 잘 만들어진것 같습니다. 
특히 매번 필요한 요구사항을 구현할때마다 테스트를 만들어서 구현을 하신 부분이 인상적이었습니다. 👍👍
크게 개선이 필요한 부분은 없었던 것 같구요
추가 기능은 만들어 주신 인터페이스에 맞춰 Handler만 구성해서 등록해 주면 될 것 같네요
아주 미세한 부분 몇가지만 개선되면 좋을것 같은 내용으로 남겼습니다. 
한번 확인해 주세요
수고하셨습니다. 👏👏

2021-02-03 15:59 UTC, parkjoos commented on src/main/java/web/HttpRequest.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(in));
br 이라는 축약어 보다 bufferReader 라고 확실히 변수명을 지어 주면 좋을것 같아요

2021-02-03 15:59 UTC, parkjoos commented on src/main/resources/templates/user/list.html
> +<!--                </tr>-->
이제 필요 없는 주석은 지워주면 좋을 것 같습니다.

2021-02-03 15:59 UTC, parkjoos commented on src/main/java/web/HttpResponse.java
> +    private static final String HTTP_1_1 = "HTTP/1.1 ";
이 상수도 어떻게 보면 httpheader 에 있으면 더 어울릴 것 같네요

2021-02-03 15:59 UTC, parkjoos commented on README.md
> +- [x] URL decoding 기능 추가
요구사항을 단계별로 아주 잘 정리 해 주셨네요
커밋별로 리뷰를 확인할때 아주 보기 편했습니다. 👍👍

2021-02-03 15:59 UTC, parkjoos commented on src/main/java/handler/FileHandler.java
> +}
중복로직을 별도로 분리해 추상화 하는 부분 인상적이었습니다. 👍👍

2021-02-03 15:59 UTC, parkjoos commented on src/main/java/handler/HandlerMapper.java
> +}
디자인 패턴을 아주 딱 필요한 부분에 잘 사용한것 같습니다. 👍

2021-02-03 15:59 UTC, parkjoos commented on src/main/java/utils/IOUtils.java
> +            readUntilEmptyLine(in, texts);
argument 데이터를 변경하는 형태는 사용하는 쪽에서 보면 이 데이터가 바뀌는지 추측 하기가 어렵습니다. 
내부에서 어떻게 데이터가 바뀌는지 모르는 상태에서는 이후 로직에서 실수하거나 히스토리를 파악하기 어렵게 될 수 있습니다. 
단순하게 readUntilEmptyLine 내부에서 texts 를 만들어서 return 하도록 수정되면 좋을것 같습니다.

2021-02-03 15:59 UTC, parkjoos commented on src/main/java/handler/UserListHandler.java
> +        String cookie = httpRequest.getHttpHeaders().get("Cookie");
login cookie 도 원시값을 포장해서 별도의 도메인 클래스로 분리하면 아래 몇가지 로직을 위임할 수 있을 것 같습니다.

2021-02-04 02:11 UTC, dsyun96 commented on src/main/java/web/HttpRequest.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(in));
원래 있던 테스트 코드에도 br을 쓰길래 따라서 썼던 것 같네요 😅 
전부 변경하겠습니다!

2021-02-04 02:22 UTC, dsyun96 commented on src/main/resources/templates/user/list.html
> +<!--                </tr>-->
이걸 깜빡했네요..!

2021-02-04 02:42 UTC, dsyun96 commented on src/main/java/utils/IOUtils.java
> +            readUntilEmptyLine(in, texts);
리팩토링 진행하다보니 따로 private 메소드로 빼서 할 필요는 없을 것 같아서 그냥 try에 바로 해당 로직을 이동하였습니다.

2021-02-04 03:16 UTC, dsyun96 commented on src/main/java/handler/UserListHandler.java
> +        String cookie = httpRequest.getHttpHeaders().get("Cookie");
오.. 그렇네요! 좋은 피드백 감사합니다.

2021-02-04 04:43 UTC, parkjoos approved these changes
안녕하세요 yuni 피드백 반영 잘보았습니다. 😊
더이상 제가 드릴 피드백이 없을것 같네요 아주 완벽한것 같구요 👍👍
LoginCookie 까지 별도 클래스가 만들어 져서 아주 깔끔해 진 것 같습니다. 
이번 스텝은 바로 머지 하도록 하겠습니다. 
수고하셨습니다. 👏👏

2021-02-04 04:43 UTC, merged