[turner.lee] http 미션 step 1~2 리뷰 요청드립니다.
NewKrew2021/jwp-was-kakao pull request #36
Opened 2021-02-03 06:35 UTC by sumniy

안녕하세요 리뷰어님, 터너입니다.

http 미션 step 2단계까지 완료하여 리뷰 요청드립니다.

2021-02-04 08:44 UTC, dongjoon1251 requested changes
안녕하세요. 이번 미션을 맡게된 제노스입니다.
생각해보실 만한 부분들을 위주로 코멘트를 남겼습니다.
기능 구현도 좋지만 그동안 다른 미션을 수행하면서 적용했던 객체지향생활체조 원칙들도 같이 지켜주시면 더 많은 도움이 되실 것 같습니다 :)

2021-02-04 08:44 UTC, dongjoon1251 commented on src/test/resources/Http_Cookie.txt
> +HTTP/1.1 302 Found
파일로 테스트 케이스 분리 👍

2021-02-04 08:44 UTC, dongjoon1251 commented on src/test/java/dto/HttpResponseTest.java
> +        response.forward("/index.html");
테스트에 사용되는 출력을 파일로 잘 분리해주셨네요. 
대신 해당 테스트가 어떤걸 확인하는지 명확하지 않습니다. 
파일로 분리한 응답 결과와 Response를 통해서 만든 응답 결과가 같은지 비교하는 코드들이 추가되면 좋을 것 같습니다.

2021-02-04 08:44 UTC, dongjoon1251 commented on src/test/java/dto/HttpRequestTest.java
> +    public void request_POST2() throws Exception {
단순히 숫자를 붙이기 보다는 어떤점이 다른지 드러나도록 표현해주시면 어떨까요?

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/webserver/RequestHandler.java
> +            if(controller == null){
null 체크는 지양해주세요 :)
Optional등을 적용하거나 다른 방법이 있을지 고민해주시기 바랍니다.

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/webserver/HandlerMapping.java
> +        if (url.endsWith(".html") || url.endsWith(".css") || url.endsWith(".js")) {
확장자가 늘어날수록 해당 조건문의 길이도 길어지게 됩니다. 이점을 고려하여 리팩토링해보면 어떨까요?

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/session/HttpSessions.java
> +    private static final Map<String, HttpSession> sessions = new HashMap<>();
서버 요청마다 새로 생기는 쓰레드들이 같이 접근할 수 있는 데이터입니다. 
동시성과 관련해서 한번 공부해보시면 좋을 것 같습니다. (Lock, thread, ConcurrentHashMap 등등)

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/dto/HttpResponse.java
> +
HTTP/1.1 도 상태로 봐야할까요? 
outputstream에 출력하기 위한 포맷은 따로 정의해서 사용하는게 어떨까요?

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/dto/HttpResponse.java
> +            if (path.endsWith(".html")) {
HandlerMapping의 확장자 문자열과 중복된 데이터로 보여집니다. 데이터를 가지고 있는 한쪽에서 처리하도록 리팩토링해보면 어떨까요?

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/dto/HttpResponse.java
> +    public void setBody(byte[] body, String contentType) {
생성자를 상단에 배치시켜주세요:)

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/dto/HttpResponse.java
> +    public HttpResponse(byte[] body) {
해당 클래스의 모든 필드를 대입할 수 있는 생성자 클래스를 하나 만들고, 다른 생성자에서 이를 호출하도록 해보면 어떨까요?

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/dto/HttpResponse.java
> +    private Map<String, String> headers = new HashMap<>();
headers를 일급 컬렉션으로 다뤄봐도 좋을 것 같습니다.

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/dto/HttpRequest.java
> +
해당 클래스에 아래의 규칙을 적용시켜보면 어떨까요?

규칙3: 모든 원시값과 문자열은 포장한다
규칙8: 일급 콜렉션을 쓴다

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/controller/LoginController.java
> +            response.addHeader("Set-Cookie", "SessionId=" + sessionId + "; Path=/");
세션을 위한 쿠키값을 응답에 추가할 때, "Set-Cookie"등의 문자열은 Controller에서 몰라도 되도록 리팩토링해보면 어떨까요?

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/controller/ListUserController.java
> +            if (httpSession != null) {
null 체크 로직은 지양해주세요 :)

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/controller/ListUserController.java
> +                TemplateLoader loader = new ClassPathTemplateLoader();
해당 객체는 모든 api 요청마다 새로 만들게 되는데요. 한번만 생성해서 사용할 수 있는 방법을 고민해주시기 바랍니다.
더불어서 해당 메소드의 크기를 메소드 분리 등을 통해서 줄여주시기 바랍니다.

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/controller/Controller.java
> +
인터페이스 분리 👍

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/controller/AbstractController.java
> +    public void doPost(HttpRequest request, HttpResponse response){}
정의하지 않은 메소드를 빈 메소드로 만들지 않고 다르게 표현할 수 있을까요?

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/webserver/HandlerMapping.java
> +    private static Map<String, Controller> handlerMapping = new HashMap<>();
static 초기화를 하지 않고 enum으로 만들어보면 어떨까요?

2021-02-04 08:44 UTC, dongjoon1251 commented on src/main/java/utils/SessionUtils.java
> +        return "";
빈문자열을 리턴하기보다 세션아이디가 없는지 더 확실히 전달할 수 있는 방법이 없을까요?

2021-02-04 13:27 UTC, sumniy reviewed
꼼꼼한 리뷰 감사합니다!! 피드백 반영후에 다시 리뷰 요청드리겠습니다!

2021-02-04 13:27 UTC, sumniy commented on src/main/java/controller/AbstractController.java
> +    public void doPost(HttpRequest request, HttpResponse response){}
abstract 키워드를 활용하면 될 것 같습니다.

2021-02-04 13:27 UTC, sumniy commented on src/main/java/controller/ListUserController.java
> +            if (httpSession != null) {
넵 알겠습니다.

2021-02-04 13:27 UTC, sumniy commented on src/main/java/controller/ListUserController.java
> +                TemplateLoader loader = new ClassPathTemplateLoader();
넵 말씀하신대로 수정하겠습니다.

2021-02-04 13:27 UTC, sumniy commented on src/main/java/controller/LoginController.java
> +            response.addHeader("Set-Cookie", "SessionId=" + sessionId + "; Path=/");
response에 쿠키 추가하는 메서드를 만들어보겠습니다. ㅎㅎ

2021-02-04 13:27 UTC, sumniy commented on src/main/java/dto/HttpRequest.java
> +
넵 알려주셔서 감사합니다.

2021-02-04 13:27 UTC, sumniy commented on src/main/java/dto/HttpResponse.java
> +    private Map<String, String> headers = new HashMap<>();
넵 알겠습니다.

2021-02-04 13:27 UTC, sumniy commented on src/main/java/dto/HttpResponse.java
> +    public void setBody(byte[] body, String contentType) {
수정하겠습니다.

2021-02-04 13:27 UTC, sumniy commented on src/main/java/dto/HttpResponse.java
> +    public HttpResponse(byte[] body) {
넵 수정해보겠습니다.

2021-02-04 13:27 UTC, sumniy commented on src/main/java/dto/HttpResponse.java
> +            if (path.endsWith(".html")) {
넵 고민해보고 수정해보겠습니다!

2021-02-04 13:27 UTC, sumniy commented on src/main/java/dto/HttpResponse.java
> +
넵 그게 맞는 것 같습니다. 수정하겠습니다.

2021-02-04 13:27 UTC, sumniy commented on src/main/java/session/HttpSessions.java
> +    private static final Map<String, HttpSession> sessions = new HashMap<>();
넵 감사합니다! 공부하고 수정해보겠습니다.

2021-02-04 13:27 UTC, sumniy commented on src/main/java/utils/SessionUtils.java
> +        return "";
음.. throw 하는 방법이 있을 것 같은데 더 고민해보겠습니다.

2021-02-04 13:27 UTC, sumniy commented on src/main/java/webserver/HandlerMapping.java
> +    private static Map<String, Controller> handlerMapping = new HashMap<>();
넵 반영해보겠습니다.

2021-02-04 13:27 UTC, sumniy commented on src/main/java/webserver/HandlerMapping.java
> +        if (url.endsWith(".html") || url.endsWith(".css") || url.endsWith(".js")) {
넵 수정해보겠습니다.

2021-02-04 13:27 UTC, sumniy commented on src/main/java/webserver/RequestHandler.java
> +            if(controller == null){
넵 감사합니다. 수정하겠습니다.

2021-02-04 13:27 UTC, sumniy commented on src/test/java/dto/HttpRequestTest.java
> +    public void request_POST2() throws Exception {
넵 수정하겠습니다.

2021-02-04 13:27 UTC, sumniy commented on src/test/java/dto/HttpResponseTest.java
> +        response.forward("/index.html");
넵 추가해보겠습니다.

2021-02-05 10:23 UTC, sumniy commented
안녕하세요 제노스. 남겨주신 피드백 반영했습니다. 

미션 마감시간이 지나서 리뷰는 안해주셔도 괜찮습니다. 
다만, 혹시 괜찮으시다면 질문 하나만 답변해주시면 감사하겠습니다. 🙏

```
빈문자열을 리턴하기보다 세션아이디가 없는지 더 확실히 전달할 수 있는 방법이 없을까요?
```
이렇게 의견 남겨주셔서 저는 exception을 throw하고 호출하는 쪽에서 catch해서 처리하도록 했습니다.
혹시 더 좋은 방법이 있을까 궁금해서 질문 드립니다. 

감사합니다.

2021-02-07 07:22 UTC, dongjoon1251 approved these changes
피드백을 잘 반영해주셨네요 👍 
고생하셨습니다. 
다음 단계 미션은 원하시면 추가로 더 리뷰요청해주셔도 됩니다 :)

2021-02-07 07:23 UTC, merged

2021-02-07 07:24 UTC, dongjoon1251 commented
> 안녕하세요 제노스. 남겨주신 피드백 반영했습니다.
> 
> 미션 마감시간이 지나서 리뷰는 안해주셔도 괜찮습니다.
> 다만, 혹시 괜찮으시다면 질문 하나만 답변해주시면 감사하겠습니다. 🙏
> 
> ```
> 빈문자열을 리턴하기보다 세션아이디가 없는지 더 확실히 전달할 수 있는 방법이 없을까요?
> ```
> 
> 이렇게 의견 남겨주셔서 저는 exception을 throw하고 호출하는 쪽에서 catch해서 처리하도록 했습니다.
> 혹시 더 좋은 방법이 있을까 궁금해서 질문 드립니다.
> 
> 감사합니다.

말씀해주신 방법이 저도 좋다고 생각합니다. exception으로 던지면 외부에서 어떤 부분이 잘못될 수 있는지 확인이 가능하니까요 :)

2021-02-08 01:06 UTC, sumniy commented
감사합니다!!