[ellie.klm 김예지] was 미션 step2 리뷰 요청 드립니다.
NewKrew2021/jwp-was-kakao pull request #37
Opened 2021-02-03 06:35 UTC by Ye-Ji-Kim

안녕하세요 엘리입니다 😊
was 미션 2단계까지 구현 후 리뷰 요청 드립니다!

2021-02-04 02:06 UTC, humbledude requested changes
안녕하세요 조슈아 입니다

코드 잘 봤습니다~
개선할 부분에 대해서 코멘트 드렸는데요,
좀 세세한 부분까지 코멘트를 했나 싶긴 하지만~
한번 참고하셔서 개선해보시면 좋을꺼 같습니다 ㅎㅎㅎ

2021-02-04 02:06 UTC, humbledude commented on src/main/java/dto/HttpRequest.java
> +        } catch (Exception e){
Exception 처리를 비워놓는건 안좋은거 같아요~
에러가 났는데 에러가 났는지 모르고 그냥 지나가니까요

2021-02-04 02:06 UTC, humbledude commented on src/main/java/dto/HttpRequest.java
> +            while (!"".equals((line = br.readLine()))) {
여기서 '\n' 으로 묶은거를 위에 setRequest 에서 다시 풀잖아요?
다른 좋은 방법이 없을까요? ㅎㅎ

2021-02-04 02:06 UTC, humbledude commented on src/main/java/dto/HttpRequest.java
> +        return "logined=false";
로그인 관련 로직은 여기 있을게 아니고, 도메인 쪽에 있는게 맞습니다

2021-02-04 02:06 UTC, humbledude commented on src/main/java/dto/HttpRequest.java
> +        return "";
해당하는 헤더가 없을때 빈문자열을 리턴하는군요
빈문자열 또한 값의 일부가 될수 있어요
null 이 싫다면 Optional 처리는 어떨까요?

2021-02-04 02:06 UTC, humbledude commented on src/main/java/dto/HttpResponse.java
> +        this.headers.put("Content-Type", contentType + ";charset=utf-8");
charset 또한 content type 의 일부일 수 있겠어요
그리고 들어오는 body 가 utf-8 이 아닐수 있는데, 여기서 강제 지정하는건 아닌거 같습니다

2021-02-04 02:06 UTC, humbledude commented on src/main/java/dto/HttpResponse.java
> +        setBody(body, "");
content-type 없는 body 괜찮은건가요? ㅎㅎㅎㅎ
요새 브라우저가 넘나 좋아서 알아서 다 하긴 하는데요 ㅎㅎ

https://stackoverflow.com/questions/5661596/do-i-need-a-content-type-header-for-http-get-requests

2021-02-04 02:06 UTC, humbledude commented on src/main/java/dto/HttpResponse.java
> +            internalServerError();
없는 리소스를 요청하는 경우도 있기 때문에, 무조건 internalServerError 는 아닌거 같습니다 ㅎㅎ

2021-02-04 02:06 UTC, humbledude commented on src/main/java/dto/HttpResponse.java
> +            if (path.endsWith(".html")) {
지원하는 확장자가 늘수록 이부분 계속 추가해 줘야 하고, HandlerMapping 에서도 똑같이 업데이트 해줘야 하겠어요
두개가 한번에 업데이트 될 수 있는 좋은 방법이 없을까요?

2021-02-04 02:06 UTC, humbledude commented on src/main/java/dto/HttpResponse.java
> +        this.status = "HTTP/1.1 200 ok";
응답 코드, 메시지는 따로 모아보는거 어떨까요?
정리가 잘 되지 않을까요?

2021-02-04 02:06 UTC, humbledude commented on src/main/java/dto/HttpResponse.java
> +        addHeader("Location", "http://localhost:8080" + path);
여기서 host 의 이름을 강제 지정하는건 좀 아닌거 같습니다  ㅠㅠ
localhost 외에서는 못쓰는 웹서버가 되었어요~~

2021-02-04 02:06 UTC, humbledude commented on src/test/java/dto/HttpRequestTest.java
> +        InputStream in = new FileInputStream(new File(testDirectory + "Http_GET.txt"));
테스트용 request 를 파일로 따로 정리 하셨군요 👍

2021-02-04 02:06 UTC, humbledude commented on src/test/java/dto/HttpResponseTest.java
> +        response.forward("/index.html");
테스트에 assert 가 없는데요~
물론 assert 없는 테스트가 유용할 때가 있습니다만, 여기서는 어떤 것을 의도하고 있는지 잘 모르겠네요 ㅎㅎ

2021-02-04 02:06 UTC, humbledude commented on src/test/java/webserver/HttpRequestTest.java
> +        Runnable thread = new Runnable() {
서버 인수 테스트 격으로 서버를 띄워서 테스트 하는군요 👍

2021-02-04 02:06 UTC, humbledude commented on src/main/java/controller/CreateUserController.java
> +            e.printStackTrace();
실제 서블릿의 힌트를 좀 드리자면 ㅎㅎ
doXXX 로 리퀘스트 처리 중에 exception 이 발생하면, 어떤건 컨트롤러 로직에서 처리해도 되지만,
서버단으로 exception 을 던져서 일괄적으로 exception 을 처리하는 식으로 구현 하기도 합니다~
(마지막 까지 처리가 안되면 internal server error 를 띄운다던지요~)

2021-02-04 02:06 UTC, humbledude commented on src/main/java/controller/ListUserController.java
> +                response.forwardBody(userListPage.getBytes(), "text/html");
이거 괜찮은가요?
forward 한담에 return 안했는데 ㅎㅎㅎㅎ
이 밑에 sendRedirect 동작 따로 안하나 보죠 ㅎㅎ

2021-02-04 02:06 UTC, humbledude commented on src/main/java/controller/LoginController.java
> +        response.addHeader("Set-Cookie", "logined=false; Path=/");
쿠키 처리하는 구체적인 방법을 도메인 단에서 알고 있을 필요는 없을거 같습니다.
이 부분은 서버단에서 처리할수 있도록 수정하는게 어떨까요?

2021-02-04 08:38 UTC, Ye-Ji-Kim commented on src/main/java/controller/LoginController.java
> +        response.addHeader("Set-Cookie", "logined=false; Path=/");
자세한 리뷰 감사드립니다 ㅎㅎ 덕분에 코드 작성 과정에서 놓쳤던 부분들에 대해 더 고민해볼 수 있었습니다 😊
최대한 리뷰 반영하여 수정해보았습니다. 
또한 포피께서 내일까지 미션을 마쳐달라고 하셔서 3단계 session 구현 미션도 이번 단계에서 같이 추가하였습니다.
세션을 다뤄보는 것이 처음이라 session에 대한 객체들과 메소드들은 생성해 놓았지만 정작 컨트롤러에서는 잘 활용하지 못하였는데요.
이에 대한 조언 함께 주시면 감사하겠습니다!!

2021-02-04 08:38 UTC, Ye-Ji-Kim commented
자세한 리뷰 감사드립니다 ㅎㅎ 덕분에 코드 작성 과정에서 놓쳤던 부분들에 대해 더 고민해볼 수 있었습니다 😊
최대한 리뷰 반영하여 수정해보았습니다.
또한 포피께서 내일까지 미션을 마쳐달라고 하셔서 3단계 session 구현 미션도 이번 단계에서 같이 추가하였습니다.
세션을 다뤄보는 것이 처음이라 session에 대한 객체들과 메소드들은 생성해 놓았지만 정작 컨트롤러에서는 잘 활용하지 못하였는데요.
이에 대한 조언 함께 주시면 감사하겠습니다!!

2021-02-04 08:39 UTC, Ye-Ji-Kim commented on src/main/java/controller/ListUserController.java
> +                response.forwardBody(userListPage.getBytes(), "text/html");
return을 하지 않아도 밑의 sendRedirect는 동작하지 않는데 이유는 모르겠습니다ㅠㅠ
return 을 해주는 것이 맞는 것 같아 이 부분은 추가하였습니다.

2021-02-04 08:44 UTC, Ye-Ji-Kim commented on src/test/java/dto/HttpResponseTest.java
> +        response.forward("/index.html");
이부분은 2단계 요구사항에서 주어진 코드였는데요.
코드 실행 시 Http_Forward.txt 파일이 생성되고, forward로 발생한 http response 정보가 해당 파일에 저장됩니다.
txt 파일에 들어가서 정보가 제대로 입력되었는지 확인하는 방법으로 테스트 하였습니다!!

2021-02-04 08:59 UTC, humbledude commented on src/main/java/controller/ListUserController.java
> +                response.forwardBody(userListPage.getBytes(), "text/html");
아 그렇다면 뭐 추측인데요,
forwardBody 를 하면 이미 output stream 에 HTTP 헤더와 응답들을 다 흘려 보내고, 맨뒤에 sendRedirect 의 HTTP 헤더와 응답이 또 append 되어서 client 에 전송되었을꺼 같아요
브라우저는 뒤에 추가된 HTTP 는 무시하는 식으로 구현이 되어있는거 같군요~!
(Contents-Length 만큼만 body 를 읽고 이후 오는 데이터는 무시하거나 그러겠죠?)
아님 말고요~~ ㅎㅎㅎ

2021-02-04 09:31 UTC, humbledude requested changes
피드백도 금방 반영해서 구현하셨네요~

세션은 구현하라고 되어있지만 어디다 쓰라고는 나와있지 않죠? ㅎㅎㅎ
내일까지 시간이 있으니까, 지금 쿠키 기반 로그인을 세션 기반 로그인으로 바꿔보면 어떨까요?
쿠키에 login=true 검사하지 말고, 세션키 검사해서, 로그인 성공하면 login=true 를 세션에 저장해보는거죠 ㅎㅎ
해보시고 쿠키기반과 세션기반 로그인 처리가 장단이 있을텐데, 한번 생각해 보시면 좋을꺼 같아요

시간이 더 ~ 되신다면 Cookie 도 추상화 해서 Cookie 관련 스펙을 추상화 해봐도 좋을꺼 같구요
HTTP 스펙을 좀더 공부하셔서, 지금 구현한 웹서버 기능이 스펙에 맞게 된건지도 한번 보셔도 좋을꺼 같아요~!

2021-02-04 09:31 UTC, humbledude commented on src/main/java/controller/CreateUserController.java
> +            response.badRequest();
ㅎㅎㅎ 여기도 return 없이 끝내셨네요 ㅎㅎㅎ
doPost 라든지 이 메소드가 void return 이라 자주 까먹으시는거 같습니다
client 에 안전장치가 있지않다면 에러가 발생할 수 있는 내용이에요~

2021-02-04 09:31 UTC, humbledude commented on src/main/java/controller/CreateUserController.java
> +        response.sendRedirect("http://" + request.getHost() + "/index.html");
이거 혹시 상대경로 (`/index.html`) 동작 안하나요?
상대경로로 동작하는게 맞는거 같아요~
host 이름이 뭔지 서버가 사실 그렇게까지 알아야 될 필요는 없을꺼 같아서 말이에요~

2021-02-04 09:31 UTC, humbledude commented on src/main/java/controller/ListUserController.java
> +//            String sessionId = cookie.split(";")[1].trim();
개인적으로 쓰지 않는 코드가 주석처리되어 포함된거를 안좋아 하는데요,
왜 주석 처리 되어있는지 알수 없기 때문이에요~
삭제하고 싶은 코드라면 과감히 날리고 (기록은 git 이 갖고 있으니까)
보관하고 싶은 코드라면 왜 보관해야 되는지 사유가 같이 코멘트 되어있어야 할꺼 같습니다

2021-02-04 09:31 UTC, humbledude commented on src/main/java/dto/HttpResponse.java
> +    public void setCookie(String logined, String path, String sessionId) {
logined 는 사실 도메인 영역의 기능이죠 ㅎㅎㅎ
Cookie 는 웹서버가 처리해야 될 내용이고요~
두개가 섞이는것은 좋지 않은 구조라고 생각됩니다~

2021-02-04 09:31 UTC, humbledude commented on src/main/java/model/File.java
> +public class File {
File 이라는 이름은 이미 기본 패키지에서 쓰고 있는데요,
꼭 이거 아니면 안돼~~~ 케이스가 아니라면 가능한 기본 패키지와의 이름 충돌은 피하는게 좋겠습니다 ㅎㅎ

2021-02-04 09:31 UTC, humbledude commented on src/main/java/webserver/HttpServletRequest.java
> +public class HttpServletRequest {
아 ㅎㅎㅎ 이거 이름이 좀 혼미하네요 ㅎㅎㅎ
Session 모아놓은 곳이군요 ㅎㅎ
원래 스프링 하다보면 HttpServletRequest 가 ServletRequest 의 하위 클래스라 혼미했어요 ㅎㅎ

세션 모아놓았으니까 SesseionStorage 라든지 이런 이름 어때요?

2021-02-05 06:05 UTC, Ye-Ji-Kim commented
피드백 반영하여 수정하였습니다!!

2021-02-05 08:51 UTC, humbledude approved these changes
마지막까지 고생 많으셨습니다~
현업 가셔서도 배우신거 이어서 잘 사용하시고, 많이 써보는 만큼 또 성장하시길 바랄께요~

2021-02-05 08:52 UTC, merged