[mark.lim 임상진] WAS  step2 리뷰 요청드립니다.
NewKrew2021/jwp-was-kakao pull request #41
Opened 2021-02-03 08:11 UTC by limdef

안녕하세요 mark입니다!

부족한 부분이 많지만 step2까지 구현하여 리뷰요청드립니다. 
감사합니다.

2021-02-03 16:09 UTC, findstar requested changes
안녕하세요. mark 웹서버 리뷰를 맡은 제임스입니다. 😁
전체적으로 요구사항을 충족하는 기능 구현을 잘 해주셨네요!
몇가지 개선되면 좋을 부분에 코멘트 달아두었습니다. 
확인하시고 궁금한 점은 언제든지 DM 주세요 😄 
그럼 화이팅입니다!

2021-02-03 16:09 UTC, findstar commented on src/main/java/annotation/web/RequestMethod.java
> +    public static RequestMethod stringToRequestMethod(String method){
valueOf 메서드를 사용하면 간결하게 줄일 수 있습니다.
```java
RequestMethod.valueOf(); 
```

2021-02-03 16:09 UTC, findstar commented on README.md
> +
README 에 기능목록을 잘 정리해주셨네요 👍

2021-02-03 16:09 UTC, findstar commented on src/main/java/controller/ControllerMapper.java
> +        controllerMap=new HashMap<>();
controllerMap 의 new 는 선언과 동시에 할 수 있겠네요 
```java
public static Map<String, Controller> controllerMap = new HashMap<>();
```

2021-02-03 16:09 UTC, findstar commented on src/main/java/model/Request.java
> +    public Request(InputStream in) throws IOException {
정적 메서드를 통해서 InputStream 을 parsing 하는 로직을 처리하고
Reuqest 객체의 생성자는 별도로 존재하는 구조로 바꿔보면 어떨까요?

2021-02-03 16:09 UTC, findstar commented on src/main/java/model/Response.java
> +        StringBuilder response=new StringBuilder();
스타일은 한번 더 챙겨주세요 😄 
before 
```java
StringBuilder response=new StringBuilder();
```

after
```java
StringBuilder response = new StringBuilder();
```

2021-02-03 16:09 UTC, findstar commented on src/test/java/webserver/HttpRequestTest.java
> +    public void request_POST2() throws Exception {
테스트 코드가 간결하게 잘 작성된것 같습니다 💯 
다만 reqeust_POST2 와 같은 이름 말고 좀 더 의미있는 이름을 작성해주세요
또는 DisplayName 어노테이션을 추가해서 의미를 더 잘 드러낼 수 있습니다. 
이것 이외에도 테스트 코드 메서드를 한글로 작성하는 방법도 있습니다 😄

2021-02-03 16:09 UTC, findstar commented on src/test/java/webserver/HttpResponseTest.java
> +        // Http_Forward.txt 결과는 응답 body에 index.html이 포함되어 있어야 한다.
이런 주석은 DisplayName 이 더 적당해보이네요 😄

2021-02-03 16:09 UTC, findstar commented on src/main/java/model/Request.java
> +    public Map<String, String> getAllParameter(){
굳이 getAllParameter 로 Map<String, String> 을 반환한다면
일급 컬렉션 객체로써의 Parameter 객체의 의미가 퇴색됩니다.
User 객체를 생성하기 위해서라면
User 객체에 Parameter 를 인자로 하는 static 메서드를 추가하는 방법도 있습니다.

2021-02-03 16:09 UTC, findstar commented on src/main/java/model/Request.java
> +        return cookie.equals("logined=true");
```java
cookie.equals("logined=true");
``` 
위와 같이 로그인 여부를 판단하면 나중에 
```java 
loginged=true&param1=value1
``` 
와 같이 여러개의 값을 판단할 수 없습니다.

2021-02-03 16:09 UTC, findstar commented on src/main/java/controller/CreateUserController.java
> +        response.sendRedirect("/index.html");
1. 회원가입시 아무런 입력값 없이 `회원가입` 버튼을 누르면 에러가 발생합니다.
 예외사항에 대한 처리로직을 추가해주세요.
2. DataBase.addUser 는 직접 DAO 에 접근하는것과 같습니다. 별도로 분리해보면 어떨까요? 
3. ObjectMapper 는 편의를 위해서 사용하신건가요? 좀 더 명시적으로 작성하는 것이 나아보입니다.

2021-02-03 16:09 UTC, findstar commented on src/main/java/controller/LoginController.java
> +                .orElseThrow(NullPointerException::new);
만약 데이터베이스에서 해당 User 를 찾지 못한 경우에 반환하는 exception 이 NullPointException 일까요? 
NotFoundUserException 정도가 더 적당할것 같네요.

2021-02-05 04:33 UTC, limdef commented
안녕하세요 제임스!

먼저 리뷰 감사드립니다.
피드백 주신 부분 최대한 반영해보았습니다..!
혹시 놓친 부분이 있거나, 더 개선하면 좋겠다 싶은 부분 피드백 주시면 감사하겠습니다.

2021-02-05 12:22 UTC, findstar approved these changes
안녕하세요. 리뷰어 제임스입니다.
피드백 잘 반영해주셨네요. 👏 
PR 머지하겠습니다. 
몇가지 추가적으로 남김 코멘트는 참고만 해주세요 😄 
미션 수고하셨습니다.

2021-02-05 12:22 UTC, findstar commented on src/main/java/controller/ControllerMapper.java
> +    }
static block 잘 활용하셨네요 💯

2021-02-05 12:22 UTC, findstar commented on src/main/java/model/Request.java
> +    public static Request of(InputStream in) throws IOException {
정적 메서드 활용 좋습니다 👍

2021-02-05 12:22 UTC, findstar commented on src/main/java/controller/CreateUserController.java
> +    void doPost(Request request, Response response) {
Input 값에 대한 validation 처리가 추가되면 좋겠습니다 😄

2021-02-05 12:22 UTC, findstar commented on src/test/java/webserver/HttpResponseTest.java
> +        return new FileOutputStream(new File(testDirectory + filename));
ByteArrayStream 을 사용하시면 굳이 fileOutputStream 을 사용하지 않아도 테스트 할 수 있습니다.

2021-02-05 12:22 UTC, merged