[teo.kkim 김태홍] WAS 미션 PR입니다.
NewKrew2021/jwp-was-kakao pull request #42
Opened 2021-02-03 08:31 UTC by kth496

안녕하세요! WAS 미션 PR을 드립니다.

얼마 남지 않은 교육 기간동안 피드백을 바탕으로 열심히 공부해보겠습니다.

감사합니다 😃

2021-02-04 07:11 UTC, findstar requested changes
안녕하세요. teo 웹서버 리뷰를 맡은 제임스입니다. 😁
전체적으로 요구사항을 충족하는 기능 구현을 잘 해주셨네요!
아쉽게도 테스트 코드가 정상적으로 동작하지 않습니다. 
일부 파일이 커밋에서 누락된게 아닌가 의심되는데요. 확인 부탁드립니다.
코드상에서 개선되면 좋을 부분도 코멘트 달아두었습니다. 
확인하시고 궁금한 점은 언제든지 DM 주세요 😄 
그럼 계속 화이팅입니다!

2021-02-04 07:11 UTC, findstar commented on README.md
> +## 기능 요구 사항
기능 요구사항 정리 잘 해주셨네요 😄

2021-02-04 07:11 UTC, findstar commented on src/main/java/webserver/WebServer.java
> +    private static final Map<String, Controller> controllers = new HashMap<>();
컨트롤러의 위치가 WebServer 에 있어야 할까요? 다른 곳으로 이동해보면 좋겠습니다.

2021-02-04 07:11 UTC, findstar commented on src/test/java/domain/HttpResponseTest.java
> +        HttpResponse response = new HttpResponse(new DataOutputStream(createOutputStream("Http_Forward.txt")));
test/resources 디렉터리가 커밋에 누락되어 있는것 같습니다. test 가 실패하네요.

2021-02-04 07:11 UTC, findstar commented on src/main/java/application/MainController.java
> +        return TEMPLATES + url;
extension 기반으로 prefix 경로를 구한다면
별도의 String extension 을 구해서 비교하거나
stream 형태로 개선해보면 어떨까요?

2021-02-04 07:11 UTC, findstar commented on src/main/java/domain/ContentType.java
> +public enum ContentType {
contentType enum 좋습니다 💯

2021-02-04 07:11 UTC, findstar commented on src/main/java/domain/ContentType.java
> +    public static ContentType of(String url) {
extension 을 구하는 로직이 반복적으로 나오네요.

2021-02-04 07:11 UTC, findstar commented on src/main/java/domain/ContentType.java
> +        return HTML;
이런 로직은 stream 과 values() 메서드를 사용하면 보다 간결하게 표현할 수 있을것 같습니다.

2021-02-04 07:11 UTC, findstar commented on src/main/java/domain/HttpRequestStartLine.java
> +public class HttpRequestStartLine {
HttpRequestStartLine 클래스로 분리된 부분 좋습니다 👍

2021-02-04 07:11 UTC, findstar commented on src/main/java/domain/HttpRequest.java
> +    private Map<String, String> parameters = new HashMap<>();
header 와 parameter 도 별도의 클래스로 분리해보면 어떨까요?

2021-02-04 07:11 UTC, findstar commented on src/main/java/domain/HttpRequest.java
> +    public HttpRequest(BufferedReader br) throws IOException {
BufferedReader 를 직접 생성자의 인자로 받을 수도 있지만
별도의 parser 를 두거나
정적 메서드를 사용하여 생성하는 방식으로 변경해보는 건 어떨까요?

2021-02-04 07:11 UTC, findstar commented on src/main/java/domain/HttpRequestStartLine.java
> +    public static final String PATH_DELIMITER = "?";
상수처리 좋습니다 💯

2021-02-04 07:11 UTC, findstar commented on src/test/java/webserver/LoginTest.java
> +//            assertThat(request.getHeaders().get("Cookie")).isEqualTo("logined=true");
사용하지 않는 코드는 정리해주세요 😄

2021-02-04 16:36 UTC, kth496 commented on src/main/java/domain/ContentType.java
> +        return HTML;
enum에 대해 어설프게 알고 있었습니다..😭 스트림과 연계해서 훨씬 간결하게 표현할 수 있을 것 같네요!

2021-02-04 17:36 UTC, kth496 commented on src/main/java/webserver/WebServer.java
> +    private static final Map<String, Controller> controllers = new HashMap<>();
`WebServer`가 엔트리포인트라서 이곳에 url과 컨트롤러를 매칭하는 맵을 구현했습니다. 이러한 매핑은 전체 어플리케이션에서 공통적으로 단 하나만 필요하다고 생각했기 때문입니다. `RequestHandler`등의 다른 클래스도 생각해보았는데 아무래도 쓰레드가 생성되기 전에 static으로 컨트롤러의 맵을 만들어야 한다고 생각해서 이곳에 구현했습니다. 다른 곳으로 어떻게 이동시킬지에 대한 추가적인 도움을 받고 싶습니다!

2021-02-04 17:39 UTC, kth496 commented
디테일한 피드백 감사합니다 james!!

특히 enum을 어설프게 알고있었다는 것을 깨달았습니다 😭

피드백 중에서 잘 이해되지 않는 부분에 추가 질문을 남겨보았습니다!

그 외에 피드백들은 최대한 반영해 리팩터링 했습니다 😃

2021-02-05 06:37 UTC, findstar requested changes
안녕하세요. 리뷰 담당하는 제임스입니다.
지난번 피드백 잘 반영해주셨네요 👏 
몇가지 버그가 있어서 코멘트 드렸습니다.
확인부탁드립니다.
궁금한 점은 언제든 DM 주세요~
그럼 계속 화이팅입니다. 😄

2021-02-05 06:37 UTC, findstar commented on src/test/java/webserver/HttpRequestTest.java
> +        System.out.println("asdf : " + request.getHeaders());
이 코드는 오류를 발생시킵니다. 
커밋하기 전에 test 를 꼭 챙겨주세요 😄

2021-02-05 06:37 UTC, findstar commented on src/test/java/domain/HttpResponseTest.java
> +    private OutputStream createOutputStream(String filename) throws FileNotFoundException {
다음과 같이 ByteArrayOutputStream 사용하면 굳이 파일을 생성하지 않아도 됩니다. 

```java
OutputStream outputStream = new ByteArrayOutputStream();
String outputString = outputStream.toString();
```

2021-02-05 06:37 UTC, findstar commented on src/main/java/webserver/WebServer.java
> +    private static final Map<String, Controller> controllers = new HashMap<>();
@kth496 이 객체는 WebServer 객체인데요
WebServer 가 Controller 를 알아야할 필요가 없습니다. 
따라서 말씀하신대로 RequestHandler 에서 static 하게 Controller 를 관리하는 방법도 고려해볼 수 있습니다. 
WebServer => RequestHandler 로 이어지는 연결에서 Controller 가 필수인가를 고민해보시면 어떨까요?

2021-02-05 06:37 UTC, findstar commented on src/main/java/domain/HttpRequest.java
> +    public static HttpRequest from(BufferedReader br) throws IOException {
정적 메서드로 분리되었네요. 💯

2021-02-05 06:37 UTC, findstar commented on src/main/java/webserver/RequestHandler.java
> +            HttpRequest httpRequest = HttpRequest.from(br);
HttpResponse 는 OutputStream 을 전달하는데
HttpRequest 는 BufferedReader 를 전달할 필요가 있을까요?

2021-02-05 06:37 UTC, findstar commented on src/main/java/domain/HttpParameters.java
> +    public static final String NO_KEY = "No Key";
NO_KEY 는 언제 사용되는걸까요? 로그인 페이지에서 아무런 값을 입력하지 않으면 오류가 발생합니다.

2021-02-05 06:37 UTC, findstar commented on src/main/java/domain/ContentType.java
> +                .orElse(PLAIN);
stream 사용 좋습니다 👍

2021-02-05 13:32 UTC, kth496 commented on src/test/java/domain/HttpResponseTest.java
> +    private OutputStream createOutputStream(String filename) throws FileNotFoundException {
`I/O Stream` 에 대한 이해가 부족했음을 알게되었습니다.. 상황에 맞게 적절히 사용할 수 있도록 공부해보겠습니다!

2021-02-05 15:41 UTC, kth496 commented
피드백을 바탕으로 코드를 개선해보았습니다!

테스트를 하다가 궁금한 점이 생겼는데요.

로그인 페이지에서 잘못된 정보를 입력하거나, 아이디와 패스워드 입력칸을 모두 비운채로 요청하면 에러 페이지로 넘어갑니다.

이때, 아이디 혹은 패스워드 둘 중 하나만 채우고 나머지 하나는 비운채로 요청하면 서버로 요청이 오지 않는 것을 발견했습니다.

컨트롤러단에서 요청을 받지 못하던데, 원인이 무엇인지 궁금합니다!

2021-02-09 11:18 UTC, karian7 approved these changes
To 제임스
빠쁘실 것 같아 제가 대신 피드백 남겨요. 😉

To 테오
안녕하세요! 킷이에요.
남겨주신 [질문 코멘트](https://github.com/next-step/jwp-was-kakao/pull/42#issuecomment-774110484)에 대한 답변을 포함하여 몇가지 의견 남기면서 머지하겠습니다. 🤠

고생 많으셨고요, 가능하다면 다음 단계인 [리펙토링 단계](https://edu.nextstep.camp/s/bb4PXLji/ls/dJyo3tAn)도 진행해 보시면 좋을것 같아요. 제임스는 이번에 TF발령이 나서 여유가 없을테니 제가 피드백 대신 남겨 드릴께요. 부담없이 DM 주세요 🚀🚀

2021-02-09 11:18 UTC, karian7 commented on src/main/java/application/ListUserController.java
> +        if (!isLogin(httpRequest.getHeader(COOKIE))) {
쿠키 헤더에는 로그인 플래그 이외에도 클라이언트를 식별하기 위한 여러 정보들이 있을 수 있어요. 이를 고려해서 개선해 보면 좋겠습니다.
https://tools.ietf.org/html/rfc6265#section-4.2.1 를 참고해서 파싱로직을 만들어 보아요~

2021-02-09 11:18 UTC, karian7 commented on src/main/java/application/ListUserController.java
> +            e.printStackTrace();
예외에 대한 로깅은  되도록 로거를 이용하는 습관을 가져보면 좋겠어요 😀

2021-02-09 11:18 UTC, karian7 commented on src/main/java/application/ListUserController.java
> +            httpResponse.forward(url, body);
이부분을 실제로 동작시키면 기대한 화면이 안나오고 있네요. 왜그럴까요? 🤔 
~힌트: 응답헤더~

2021-02-09 11:18 UTC, karian7 commented on src/main/java/utils/KeyValueTokenizer.java
> +            parameters.put(stk.nextToken(), stk.nextToken());
> 이때, 아이디 혹은 패스워드 둘 중 하나만 채우고 나머지 하나는 비운채로 요청하면 서버로 요청이 오지 않는 것을 발견했습니다.

[이 코멘트](https://github.com/next-step/jwp-was-kakao/pull/42#issuecomment-774110484) 의 원인은 여기에 있어요. 어떻게 알았는지 알려드리면 [이곳](https://github.com/next-step/jwp-was-kakao/blob/f1e856f75c29c0d3cbaff1d644189c061bc3ba96/src/main/java/webserver/RequestHandler.java#L50)에서 로그 남기는 방법을 다음과 같이 바꿨어요.
```java
logger.error(e.getMessage(), e);
```

2021-02-09 11:18 UTC, karian7 commented on src/main/java/domain/HttpParameters.java
> +        return params.getOrDefault(key, NO_KEY);
그럴리는 없겠지만 만에하나 클라이언트가 `param=No Key` 형태로 요청을 보낸다면 파라메터가 없는것과 있는것을 어떻게 구분할 수 있을까요? 지금 만드는 WAS 는 톰캣을 만드는 수준은 아니지만 그래도 이런 부분들을 고려해서 구현하면 좋겠어요. 😉

2021-02-09 11:18 UTC, karian7 commented on src/main/java/model/User.java
> +    }
```suggestion
    public User(Map<String, String> parameters) {
        this(parameters.get("userId"), parameters.get("password"), parameters.get("name"), parameters.get("email"));
    }
```

생성자가 여러개 필요할 경우 단 하나의 primary constructor 와 다수의 secondary constructor 를 가지도록 디자인하는것을 추천해요. 이렇게 하면 중복 코드를 방지하고 설계를 더 간결하게 만들수 있기 때문이에요. (예를들어 생성자의 입력값 `userId` 를 검증해야 하는 경우를 생각해보면 좋겠어요.)

2021-02-09 11:18 UTC, karian7 commented on src/test/java/model/UserTest.java
> +        } catch (IOException e) {
테스트 내에선 특별한 이유가 없다면 예외는 throw 해 버려요. 왜나구요? 예외가 있는지 찾아내는게 테스트의 역할이니까요! 🤩

2021-02-09 11:20 UTC, merged

2021-02-09 16:57 UTC, kth496 commented
@karian7 

감사합니다 kit 🙏

짚어주신 피드백을 토대로 추가로 공부해서 적용해보고 DM 드리겠습니다 :)