[kuri.copper] WAS step1 ~ step2 리뷰 요청 드립니다.
NewKrew2021/jwp-was-kakao pull request #44
Opened 2021-02-03 08:46 UTC by D-kuri

초기 RequestHandler 내부에 모든 함수를 구현하고 이를 리팩토링 하는 과정이 오래 걸렸던 것 같습니다.
또한 단위 테스트를 만드는게 이번 미션에서 더욱 힘들었던것 같습니다 ! ㅠ
리뷰 잘 부탁드리겠습니다 :)

2021-02-04 02:57 UTC, humbledude requested changes
안녕하세요 조슈아 입니다

일단 HTTP 스펙에 익숙치 않다는 느낌을 받았어요~
HTTP 스펙은 사실 시간내서 공부해야겠다 라고 생각하기 어려운 부분인데,
서버 개발자라면 한번 다시 시간 내서 정리하시는게 좋을꺼 같습니다 ㅎㅎ

개선할만한 부분이 보여서 코멘트를 좀 달았습니다
확인하시고 한번 개선해보시면 좋을꺼 같아요~

2021-02-04 02:57 UTC, humbledude commented on src/main/java/controller/AbstractController.java
> +        doPost(httpRequest, httpResponse);
물론 이번 미션에는 get 과 post 만 나오지만 ㅎㅎㅎ
다른 http method 가 들어올수도 있는데 잘못 처리 될 여지가 있습니다 ㅎㅎ

2021-02-04 02:57 UTC, humbledude commented on src/main/java/controller/Controller.java
> +    default void service(HttpRequest httpRequest, HttpResponse httpResponse) throws IOException, URISyntaxException {
여기 default 지정하신 이유가 있을까요?

2021-02-04 02:57 UTC, humbledude commented on src/main/java/model/User.java
> +    public boolean hasPassword(String password){
메소드 이름이 직관적이지 않은거 같아요~
패스워드가 있는지 검사하는 메소드 같습니다 ㅎㅎ

2021-02-04 02:57 UTC, humbledude commented on src/main/java/webserver/HttpRequest.java
> +            String[] buf = line.split(": ");
`Content-Type:application/json` 처럼 들어오면 split 이 동작을 안하겠어요~
split 과 trim 을 조합하는게 좋지 않을까요?

2021-02-04 02:57 UTC, humbledude commented on src/main/java/webserver/HttpRequest.java
> +        if (method.equals("POST")) {
https://developer.mozilla.org/ko/docs/Web/HTTP/Methods/POST

POST 의 모든 조건에서 parameter 빌드가 되지는 않겠습니다
POST + application/x-www-form-urlencoded 조합에서 parameter 로 처리 가능할꺼 같아요~

2021-02-04 02:57 UTC, humbledude commented on src/main/java/webserver/RequestHandler.java
> +        return httpRequest.getHeader("Accept").split(",")[0] + ";charset=utf-8";
charset 을 강제로 여기서 넣는것은 이상한거 같아요~
왜 이렇게 처리가 되나요?

2021-02-04 02:57 UTC, humbledude commented on src/test/java/webserver/ControllerTest.java
> +        HttpRequest httpRequest = new HttpRequest(createBufferedReader("/Http_Create.txt"));
꼼꼼한 테스트 👍

2021-02-04 02:57 UTC, humbledude commented on src/main/java/controller/UserListController.java
> +        if(!isLogin(httpRequest.getHeader("Cookie"))){
Cookie 가 어떻게 동작하는지는 도메인에서 알 필요가 없을꺼 같습니다
Cookie 처리를 추상화 할수 있을까요?

2021-02-04 02:57 UTC, humbledude commented on src/main/java/webserver/HttpResponse.java
> +        addHeader("Set-Cookie", "logined=" + cookie + "; Path=/");
cookie 가 login 전용이 되었는데요 ㅎㅎㅎ
좀 더 추상화 하면 좋을꺼 같아요

2021-02-04 02:57 UTC, humbledude commented on src/main/java/webserver/HttpResponse.java
> +        addHeader("Location", "http://localhost:8080" + url);
redirect 가 localhost 전용이 되었네요;;
이래서는 진짜 서버에 올릴수가 없죠 ㅎㅎㅎ

2021-02-04 02:57 UTC, humbledude commented on src/main/java/controller/UserLoginPageController.java
> +        byte[] body = FileIoUtils.loadFileFromClasspath("./templates" + httpRequest.getPath());
LoginPageController 와 LoginFailedController 가 하는일이 똑같네요~
(라고 써놓고 보니, 똑같은게 엄청 많군요~!)

페이지 만들어질때마다 Controller 를 만들 수는 없을꺼 같아요.
공통 코드를 구조화 시킬수 있을꺼 같네요~

2021-02-04 02:57 UTC, humbledude commented on src/main/java/controller/ControllerEntity.java
> +        controllers.put("/css", new CssController());
css 파일이 꼭 /css 아래에 있을꺼라고 생각할수는 없을꺼 같아요

2021-02-04 04:52 UTC, D-kuri commented on src/main/java/controller/Controller.java
> +    default void service(HttpRequest httpRequest, HttpResponse httpResponse) throws IOException, URISyntaxException {
앗 interface method 사용시 기본 접근제어자가 어떻게 설정되는지 궁금해서 이것저것 시도해보다가 디폴트로 해놓은 것 같습니다 ㅠ
인터페이스 선언시 기본 method 선언 방법외에 default, static에 대해 더 공부해보도록 하겠습니다 !!

2021-02-04 05:34 UTC, D-kuri commented on src/main/java/webserver/RequestHandler.java
> +        return httpRequest.getHeader("Accept").split(",")[0] + ";charset=utf-8";
문서 자체에서 해당 문자열로 인코딩을 해준다면 사용해줄 필요가 없다는 것을 모르고 사용한것 같습니다 ㅠ 
다음부터는 무조건 따라하는게 아니라 왜 이렇게 사용했는지 좀 더 생각해보고 사용하도록 하겠습니다 !!

2021-02-04 07:16 UTC, D-kuri commented on src/main/java/controller/UserListController.java
> +        return loginCookie != null && loginCookie.equals(LOGIN_SUCCESS) ;
안녕하세요 조슈아 ! 이번 미션을 진행하면서 요구사항에 따른 내용만 구현하고 http 스펙에 따른 처리를 제대로 하지 못했다는걸 많이 느끼고 있습니다 👍 
이전에 깜빡하고 질문하지 못했던 내용이 있어 물어보려고 합니다 : D
이 부분과 HttpRequest의 makeHeader method에서 lazy evaluation을 통한 null check를 해줬는데 이렇게 null을 처리해줘도 되는지 여쭤보고 싶습니다 !

2021-02-04 08:56 UTC, humbledude requested changes
빠르게 수정 구현해 주셨네요~

Cookie 관련해서만 한번더 수정해 보셨으면 해요~
Cookie 클래스에서 Cookie 스펙 구현과 관련된 부분을 구현하구요,
로그인 처리하는 곳에서는 Cookie 인터페이스만 갖다쓰면  좋을꺼 같아요~!

2021-02-04 08:56 UTC, humbledude commented on src/main/java/controller/UserListController.java
> +        return loginCookie != null && loginCookie.equals(LOGIN_SUCCESS) ;
ㅎㅎㅎ 해도 되나~ 라고 여쭤보시면 당연히 모든건 버그가 없으면 해도 됩니다 ㅎㅎㅎㅎ
하지만 좋은 구조 일지는 한번 생각해 보시면 좋겠구요 ㅎㅎㅎ 저의 의견을 드리지만 정답이 아니라는거~

저는 여기서 null 보다는 isLogin 이 Cookie 와 묶이는게 더 안좋아 보이는데요,
login 여부는 로그인이라는 도메인에 소속된 기능이고요,
Cookie 는 Http 와 웹브라우저에 소속된 기능이죠

여기서는 단순 변수 이름이 loginCookie 다 라고 할수 있겠지만,
login 여부를 알기 위해 HTTP 와 웹 브라우저의 스펙을 알아야 되는 연관성? 이 안좋아 보인다는 의견 드립니다 ㅎㅎ
Cookie 클래스를 구현해서 스펙 구현은 Cookie 클래스에 맡기고 login 여부를 Cookie 에 담을지 말지만 도메인측에서 결정하면 좋겠네요

Cookie 구현에 대해서 힌트가 필요하다면, 기존 서블렛과 같이 구현되어있는 Cookie 구현체를 참조하셔도 좋겠어요~

그리고 null 에 대해서는 저는 가능한 null 은 확실히 값이 없다는 뜻 이외에는 쓰지 않는게 좋다는 기본 취지를 가지고 코딩하는데요 ㅎㅎ
뭐 살다보면 예외가 발생하는 날도 있고... ㅎㅎㅎ 그렇습니다 ㅎㅎ

2021-02-04 08:56 UTC, humbledude commented on src/main/java/controller/UserCreateController.java
> +    private static final String INDEX_URL = "http://localhost:8080/index.html";
이거 앞에 localhost 지정 안하면 동작 잘 안하나요?
이게 hostname 까지 들고 있어야 한다면 리얼 서버에는 배포 못하는 시스템이잖아요? ㅎㅎ

2021-02-05 00:21 UTC, humbledude approved these changes
수고 하셨습니다~ ㅎㅎㅎ

웹서버의 로직과 서버에서 도는 애플리케이션의 로직이 분리되면 더 좋았을꺼에요~
오늘 마지막 날인데 세션 구현까지 한번 해보시죠~!

2021-02-05 00:21 UTC, merged