[sierra.s] step1,2 코드리뷰 요청드립니다.
NewKrew2021/jwp-was-kakao pull request #47
Opened 2021-02-03 12:32 UTC by 32sylee

안녕하세요, 시에라입니다😄
WAS 구현 미션 코드리뷰 요청드립니다.

과제를 진행하면서 궁금했던 점들은 코드에 질문 달아놓겠습니다.
잘부탁드립니다!🙇‍♀️

2021-02-03 12:39 UTC, 32sylee commented on src/main/java/controller/ControllerEntity.java
> +    }
url이 /js, /css, /fonts로 시작하는 요청을 StaticController로 매핑해주기 위해 만든 메서드입니다.
그런데 if문으로 처리하는건 확장성 측면에서 좋지 못한 방법이라는 생각이 듭니다.
이걸 개선할 수 있는 방법이 있을까요?

2021-02-03 12:47 UTC, 32sylee commented on src/main/java/webserver/RequestHandler.java
> +            httpResponse.addHeader("Content-Type", getContentType(httpRequest));
request의 Accept 헤더에 따라 response의 Content-Type을 일괄적으로 설정해주었습니다.
이렇게 일괄적으로 설정해 주는게 맞는지 궁금합니다.
Accept 헤더는 클라이언트가 서버한테 '나는 이런 데이터 형식으로 보내줘'라고 알려주는 것으로 알고 있는데요,
아니면 Accept의 내용에 따라 서버가 뭔가 데이터 처리를 달리 해야 하는 것일까요?

2021-02-04 08:49 UTC, dongjoon1251 commented on src/main/java/webserver/RequestHandler.java
> +            httpResponse.addHeader("Content-Type", getContentType(httpRequest));
Accept의 내용에 따라서 서버가 맞춰주면 좋지만 필수는 아닙니다. 
예를 들어, 클라이언트가 Accept: A를 했고, 서버가 A,B,C 중에 골라서 줄 수 있다면 A를 맞춰주는게 좋습니다.
다만 서버가 B,C 중에서 줘야 한다면 A를 받을 수 있다는 요청을 무시하고 서버가 임의로 B나 C로 응답해도 상관없습니다.

관련해서 'HTTP 완벽 가이드'라는 책에 내용들이 잘 나와있어서 읽어보시길 추천드립니다 :)

2021-02-04 08:50 UTC, dongjoon1251 commented on src/main/java/controller/ControllerEntity.java
> +    }
JS, CSS 등을 가진 enum을 만들어서 해당 enum 클래스 내부에서 values() 메소드를 통해 포함 여부를 확인할 수 도 있을 것 같습니다.

2021-02-04 09:05 UTC, dongjoon1251 requested changes
안녕하세요 리뷰를 맡게된 제노스입니다.
이전 미션에서 경험했던 객체지향생활체조 원칙을 많이 적용해주시고 테스트도 꼼꼼히 잘 작성해주셨네요:)
추가로 몇가지 코멘트를 드렸으니 확인 부탁드립니다.

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/java/controller/AbstractController.java
> +        if (httpRequest.getMethod() == HttpMethod.GET) {
== 보다는 equals를 써보는게 어떨까요? :)

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/java/controller/AbstractController.java
> +        doPost(httpRequest, httpResponse);
HttpMethod의 종류가 Get,Post 이외에도 있는데 다른 메소드들을 추가하는 것을 고려해서 해당 메소드를 작성해보면 어떨까요?

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/java/controller/AbstractController.java
> +    }
메소드내부를 공백으로 표현하지 않는 다른 방법이 있을까요?

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/java/controller/Controller.java
> +    default void service(HttpRequest httpRequest, HttpResponse httpResponse) throws IOException, URISyntaxException {
interface 분리 👍 
여기서 default로 지정하지 않고 구현해볼 수 있을까요?

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/java/controller/ControllerEntity.java
> +        controllers = new HashMap<>();
static 초기화대신 enum을 적용해보면 어떨까요? :)

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/java/utils/TemplateUtils.java
> +
템플릿 사용 로직 분리 👍

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/java/controller/UserListController.java
> +
로그인 여부는 다른 컨트롤러에서도 사용될 수 있을 것 같습니다. 같이 쓸 수 있게 분리시켜보면 어떨까요?

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/java/controller/UserLoginController.java
> +    private static final String FALSE = "false";
문자열 상수화 👍

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/java/controller/UserLoginFailedController.java
> +        byte[] body = FileIoUtils.loadFileFromClasspath("./templates" + httpRequest.getPath());
UserLoginPageController와 중복으로 보입니다. 공통으로 사용되는 부분들을 하나로 합쳐보면 어떨까요?:)

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/java/webserver/HttpMethod.java
> +    public static HttpMethod from(String method) {
enum의 name() 메소드를 사용해보면 어떨까요?

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/java/webserver/HttpRequest.java
> +    private Map<String, String> parameters;
일급 컬렉션을 적용해보면 어떨까요?

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/java/webserver/HttpResponse.java
> +    private Map<String, String> header;
여기도 일급 컬렉션을 적용해볼 수 있어 보입니다. :)

2021-02-04 09:05 UTC, dongjoon1251 commented on src/main/resources/static/css/index.css
> +table {
css 추가 👍

2021-02-04 09:05 UTC, dongjoon1251 commented on src/test/java/webserver/ControllerTest.java
> +package webserver;
테스트를 꼼꼼히 작성해주셨네요 👍 
컨트롤러별로 테스트 클래스를 나눠보면 어떨까요?

2021-02-04 09:05 UTC, dongjoon1251 commented on src/test/java/webserver/HttpResponseTest.java
> +        response.forward(body);
어떤 테스트인지 잘 모르겠습니다.
text file에 있는 response처럼 response가 잘 만들어지는지 체크하는 코드가 추가되면 좋을 것 같습니다.

2021-02-05 01:32 UTC, 32sylee commented on src/main/java/controller/ControllerEntity.java
> +    }
enum으로 하는 방법이 있겠네요..! 감사합니다:)

2021-02-05 01:35 UTC, 32sylee commented on src/main/java/webserver/RequestHandler.java
> +            httpResponse.addHeader("Content-Type", getContentType(httpRequest));
그러면 서버는 일단 자기가 응답해야 될 content-type으로 응답을 하고,
여러 content-type 중 선택해서 응답을 해줄 수 있는 경우에만 클라이언트의 accept의 헤더를 확인해서 응답해주면 되겠네요..!
HTTP에 대해서는 더 공부가 필요할 것 같아요! 추천해주신 책 읽어보겠습니다. 감사합니다:)

2021-02-05 01:41 UTC, 32sylee commented on src/main/java/controller/AbstractController.java
> +        if (httpRequest.getMethod() == HttpMethod.GET) {
enum은 하나의 인스턴스만 생성된다고 알고있어서 ==를 썼는데요! equals를 썼을 때와 ==를 썼을 때의 차이점이 있을까요?

2021-02-05 04:45 UTC, 32sylee commented on src/main/java/controller/AbstractController.java
> +        doPost(httpRequest, httpResponse);
분기로 처리하는 것 말고 다른 방법이 있을까요?🤔 일단 GET, POST가 아닌 다른 메서드가 들어왔을 시에 예외 발생하도록 변경하였습니다!

2021-02-05 04:50 UTC, 32sylee commented on src/main/java/controller/AbstractController.java
> +    }
상속받은 컨트롤러에서 override되지 않았을 때 예외를 발생시킬 수 있도록 AbstractController의 doGet, doPost에서는 예외를 던져주면 좋을 것 같아요! (말씀하신 의도가 이게 맞는지 모르겠네요!)

2021-02-05 04:51 UTC, 32sylee commented on src/main/java/controller/Controller.java
> +    default void service(HttpRequest httpRequest, HttpResponse httpResponse) throws IOException, URISyntaxException {
앗 저게 default로 되어 있었군요! 추상메서드로 변경하겠습니다

2021-02-05 05:00 UTC, 32sylee commented on src/main/java/controller/ControllerEntity.java
> +        controllers = new HashMap<>();
넵! enum 적용해보겠습니다

2021-02-05 08:01 UTC, 32sylee commented on src/main/java/controller/UserListController.java
> +
네:) 로그인 여부 체크하는 기능 분리시키겠습니다!

2021-02-05 08:02 UTC, 32sylee commented on src/main/java/controller/UserLoginFailedController.java
> +        byte[] body = FileIoUtils.loadFileFromClasspath("./templates" + httpRequest.getPath());
똑같은 일을 하는 컨트롤러가 많이 있네요😅 공통부분 하나로 합치겠습니다!

2021-02-05 08:03 UTC, 32sylee commented on src/main/java/webserver/HttpMethod.java
> +    public static HttpMethod from(String method) {
이런 메서드가 있었군요..! name() 메서드 사용해서 수정해보겠습니다.

2021-02-05 08:03 UTC, 32sylee commented on src/main/java/webserver/HttpResponse.java
> +    private Map<String, String> header;
네! headers랑 parameters에 일급컬렉션 적용하겠습니다:)

2021-02-05 08:04 UTC, 32sylee commented on src/test/java/webserver/ControllerTest.java
> +package webserver;
그렇게 하는게 가독성이 더 좋겠네요..! 컨트롤러별로 분리하겠습니다

2021-02-05 08:09 UTC, 32sylee commented on src/test/java/webserver/HttpResponseTest.java
> +        response.forward(body);
넵 검증로직 추가하겠습니다

2021-02-05 09:17 UTC, 32sylee commented
리뷰 감사합니다!! :)
코멘트 주신 사항들을 대부분 반영했는데 아래의 사항들을 해결하지 못했습니다.ㅠㅠ
시간이 얼마 남지 않아 일단 리뷰요청 먼저 드리게 되었습니다!

1. https://github.com/next-step/jwp-was-kakao/pull/47#discussion_r570046759 에서 static을 enum으로 어떻게 바꿔주어야 할지 잘 모르겠습니다. enum이 path와 controller의 매핑 정보를 가지고 있어서 enum을 순회하면서 초기화를 해 주는 것일까요..?
2. HttpHeader, HttpParameter를 일급컬렉션으로 만들어주었는데 컬렉션을 불변 객체로 만들어주지 못했습니다. 불변 객체로 바꾸어주면 다른 로직도 손보아야 할 것 같은데 시간이 좀 걸릴 것 같아요!

2021-02-07 07:20 UTC, dongjoon1251 approved these changes
피드백을 잘 반영해주셨네요 👍 
질문주신 부분중에 ControllerEntity를 enum으로 표현하는 부분은 예시로 아래와 같이 작성할 수 있습니다.
이 방식이 더 좋다기보다는 다양한 구현 방식을 고민해보시도록 제안드린거였습니다. 적용해보시고 더 나아보이는 방식으로 적용해주시면 됩니다. 
고생하셨습니다. 다음 단계 미션은 원하시면 추가로 리뷰요청해주셔도 됩니다 :)

```java
public enum ControllerEntity {

    INDEX("index.html", new TemplateController());
    private final String path;
    private final AbstractController controller;

    ControllerEntity(String path, AbstractController controller) {
        this.path = path;
        this.controller = controller;
    }
  
    ...
```

2021-02-07 07:21 UTC, merged