[pavlo.v 최환] 웹 서버 구현 코드리뷰 부탁드립니다!
NewKrew2021/jwp-was-kakao pull request #48
Opened 2021-02-03 15:16 UTC by choihwan2

안녕하세요 파블로입니다!

미션을 수행하면서 스프링에 감사함을 크게 느낄수 있었네요.. 그리고 인터페이스를 활용해서 마지막에 Controller 를 다양하게 만들고
RequestHandler에 몰려있던 메소드들을 각 컨트롤러에 넘겨주면서 해결하는 과정에서 상당히 기분이 좋았습니다. 부족한 부분이 많을 것 같은데 피드백 잘 부탁드립니다!

2021-02-04 08:00 UTC, humbledude requested changes
안녕하세요 조슈아 입니다

코드 잘 봤습니다 ㅎㅎㅎ
전반적으로 잘 구성이 되어있어서 코드 보기가 편했어요~

몇가지 코멘트를 드렸는데, 한번 검토해보시고 개선 하시면 좋겠어요~
특히 HTTP 스펙은 시간 있으실때 한번 확인해보셔도 좋을꺼 같네요 
이거 한번 구현해보면 스펙이 궁금해질꺼 같아서 ㅎㅎㅎ

2021-02-04 08:00 UTC, humbledude commented on src/main/java/application/ListUserController.java
> +        if (!isLogin(httpRequest.getHeader(COOKIE))) {
쿠키 처리하는 부분을 추상화 해볼수 있을까요?
쿠키가 어떻게 구현되는지 도메인 측에서는 몰라도 될꺼 같습니다~ (쓸줄만 알면 되죠~)

2021-02-04 08:00 UTC, humbledude commented on src/main/java/application/MainController.java
> +        if (url.endsWith(CSS) || url.endsWith(JS) || url.endsWith(ICO) || url.endsWith(TTF) || url.endsWith(WOFF)) {
확장자가 추가될때마다 여기+ContentType 에 동시 업데이트가 되어야 하겠어요
한번에 다 처리되게 개선해보면 어떨까요?

2021-02-04 08:00 UTC, humbledude commented on src/main/java/domain/HttpRequest.java
> +    public static final String HEADER_DELIMITER = ": ";
`Content-Type:xxx` 이렇게 헤더가 들어오면 이거로 파싱이 안되겠어요 ㅎㅎ
split + trim 으로 구현하는게 어떨까요?

2021-02-04 08:00 UTC, humbledude commented on src/main/java/domain/HttpRequest.java
> +            parameters.putAll(KeyValueTokenizer.of(IOUtils.readData(br, Integer.parseInt(headers.get(CONTENT_LENGTH)))));
ㅎㅎㅎ 여기 함수 호출이 너무 줄줄이라서 보기 어려운거 같습니다
클린코드 권장은 한줄에 쩜 한개지만.. 적당히 ㅎㅎㅎ

그리고 Content Length 가 있는 모든 body 가 key-value 형태는 아닐꺼 같은데요~
이부분에 대해 처리가 필요할꺼 같습니다

2021-02-04 08:00 UTC, humbledude commented on src/main/java/domain/HttpRequest.java
> +        return headers.getOrDefault(key, NO_KEY);
없는 헤더를 요청했을때 별다른 에러 없이 NO_KEY 가 나오는군요
받는쪽에서 NO_KEY 검사를 일일이 다 해야 하고, 실제 "No Key" 값이 특별한 의미를 갖는다는것 역시 쓰는쪽에서 (이 서버위에 구현하는 모든 도메인 로직이) 알고 있어야 하겠어요
다른 방법으로 key 없음을 표현해볼수 있을까요?

2021-02-04 08:00 UTC, humbledude commented on src/main/java/domain/HttpRequestStartLine.java
> +        this.method = HttpMethod.resolve(method);
가장 복잡한 첫번쨰 줄을 담당하는 클래스군요 👍 

외부에서 사용될꺼 같지 않은 constructor 는 private 처리해도 될꺼 같습니다

2021-02-04 08:00 UTC, humbledude commented on src/main/java/domain/HttpResponse.java
> +    public static final String CONTENT_TYPE = "Content-Type";
주요 헤더들은 한군데 모아서 관리해도 좋을꺼 같아요

2021-02-04 08:00 UTC, humbledude commented on src/main/java/domain/HttpResponse.java
> +            logger.error(e.getMessage());
응답 처리중 exception 이 나면 에러 로깅후에 별다른 조치가 없는데요~
응답 처리가 실패하면 Internal Server Error 를 뱉어주는건 어떨까요? (잘 될지 모르겠네요 ㅎㅎ)

2021-02-04 08:00 UTC, humbledude commented on src/test/java/domain/HttpResponseTest.java
> +        assertThat(response.getHeaders().get("Content-Type")).isEqualTo("text/html; charset=utf-8");
테스트의 assert 가 중요 부분을 체크 하지 않고있네요~
어떻게 하면 HttpResponse 를 제대로 검증할수 있을까요?

2021-02-04 08:00 UTC, humbledude commented on src/test/java/webserver/LoginTest.java
> +//            assertThat(request.getHeaders().get("Cookie")).isEqualTo("logined=true");
이거 assert 안도나요? 왜 주석처리 되어있죠 ㅎㅎㅎㅎ
이게 있어야 테스트가 정확히 돌꺼 같은데 말이죠~

2021-02-05 07:29 UTC, choihwan2 commented on src/test/java/webserver/LoginTest.java
> +//            assertThat(request.getHeaders().get("Cookie")).isEqualTo("logined=true");
리팩토링하다가 잠시 주석처리해놓은걸 돌리는걸 깜빡했었네요! 다시 돌려놓겠습니다

2021-02-05 07:47 UTC, choihwan2 commented on src/main/java/application/MainController.java
> +        if (url.endsWith(CSS) || url.endsWith(JS) || url.endsWith(ICO) || url.endsWith(TTF) || url.endsWith(WOFF)) {
개선해보겠습니다!

2021-02-05 07:49 UTC, choihwan2 commented on src/main/java/application/ListUserController.java
> +        if (!isLogin(httpRequest.getHeader(COOKIE))) {
쿠키에 들어있는 값에 따라서 redirect로 index.html로 보내주는 것과 forward로 list 화면으로 보내주는것이 성격이 많이 다르다고 생각했는데 이걸 추상화 할 수 있을까요..?

2021-02-05 07:50 UTC, choihwan2 commented on src/main/java/domain/HttpRequest.java
> +    public static final String HEADER_DELIMITER = ": ";
trim을 깜빡하고 있었네요.. 개선해보겠습니다!

2021-02-05 07:52 UTC, choihwan2 commented on src/main/java/domain/HttpRequest.java
> +            parameters.putAll(KeyValueTokenizer.of(IOUtils.readData(br, Integer.parseInt(headers.get(CONTENT_LENGTH)))));
음.. 코드를 짜다보니 `String body` 라는 필드 변수를 하나 더 갖게 될 것 같아서, 그걸 `paramters` 라는 해쉬 맵 변수 안에 키가 'body' 라는 이름으로 집어넣어 준 것인데,`body` 라는 필드 변수를 하나 더만들고 갖게 하는게 좋을까요??

2021-02-15 05:17 UTC, closed without merging