1단계 - HTTP 웹 서버 구현
NewKrew2021/jwp-was-kakao pull request #5
Opened 2020-12-02 01:33 UTC by humbledude

안녕하세요~

1단계 구현해 봤습니다 ㅎㅎ
잘 부탁 드립니다

2020-12-02 13:21 UTC, kriery requested changes
안녕하세요 이번 리뷰를 맡게 된 이종찬입니다.
entity를 쓰임새에 맞게 잘게 나눠놓으셔서 깜짝 놀랬어요.
`ApplicationContext`를 이용하여 controller들을 singleton으로 관리하는 부분이나,
`Request` / `Response` 를 별도 객체로 만들어 기능을 위임하는 등 시야가 한층 높아진것 같습니다.
몇가지 _제 기준_ 에서 아쉽다 하는 내용들 남겨두었어요.
같이 공부하는 입장에서 저도 많은걸 배워갑니다! 😁

2020-12-02 13:21 UTC, kriery commented on src/main/java/webserver/http/HttpMethod.java
> +}
enum 사용 👍

2020-12-02 13:21 UTC, kriery commented on src/main/java/webserver/http/HttpRequest.java
> +            FormUrlencodedBodyParser.parse(body, output);
output을 argument로 받는것은 바람직 하지 않은것 같아요. `Map<String, String>`을 return 하게 하면 어떨까요?

2020-12-02 13:21 UTC, kriery commented on src/main/java/webserver/http/parser/CookieParser.java
> +                    .forEach(p -> output.put(p[0], p[1]));
이왕 stream으로 전개한 김에,
```suggestion
            Stream.of(tokens)
                    .map(param -> param.split("="))
                    .collect(Collectors.toMap(element -> element[0], element -> element[1]);
```
처럼 해서 바로 `Map`으로 반환 할 수 있어요

2020-12-02 13:21 UTC, kriery commented on src/main/java/webserver/http/parser/HttpRequestParser.java
> +        }
`firstLine`이 매 요청에 항상 존재해야 하는 것이라면, 매번 `handleLine` -> `isFirstLine` 을 비교하기 보단
```java
handleFirstLine(inputLine)
while ( read a line() ){
  handle 나머지 line()
}
```
구조도 고려해봄직 할것 같아요

2020-12-02 13:21 UTC, kriery commented on src/main/java/webserver/http/parser/HttpRequestParser.java
> +    public HttpRequestParser() { }
<img width="723" alt="image" src="https://user-images.githubusercontent.com/47452850/100875394-4d124780-34e9-11eb-978c-ffae20679fb0.png">
사용처를 보니, `HttpRequestParser.parse`는 static으로도 만들어 사용할 수 있을것 같아요 🌟

2020-12-02 13:21 UTC, kriery commented on src/main/java/exceptions/NoSuchResource.java
> +}
custom exception 💯

2020-12-02 13:21 UTC, kriery commented on src/main/java/webserver/WebServer.java
> +                Thread thread = new Thread(new RequestHandler(connection, applicationContext));
`ApplicationContext`를 static 으로 만들면 `RequestHandler` 생성때마다 매번 instance를 주입하지 않아도 될것 같아요!

2020-12-03 00:23 UTC, humbledude commented on src/main/java/webserver/http/HttpRequest.java
> +            FormUrlencodedBodyParser.parse(body, output);
그것이 제가 쫌 고민했었는데요,
Map을 반환 하려고 하는게 좀더 낫죠 ㅎㅎㅎㅎ
근데 get 을 할때마다 객체를 매번 생성하게 되어서...
한번 다시 생각해보겠습니다.

2020-12-03 00:24 UTC, humbledude commented on src/main/java/webserver/http/parser/HttpRequestParser.java
> +        }
아 네 맞네요~!!

2020-12-03 00:25 UTC, humbledude commented on src/main/java/webserver/http/parser/HttpRequestParser.java
> +    public HttpRequestParser() { }
네 ㅎㅎㅎ 한번 변경해볼께요~

2020-12-04 00:17 UTC, humbledude commented on src/main/java/webserver/http/HttpRequest.java
> +            FormUrlencodedBodyParser.parse(body, output);
일단 객체 매번 생성에 대해서는~
1. request 에서 map 형태의 body 를 만드는 일을 그닥 여러번 호출할 일이 없다는거, (처음에 한번 하고 말겠죠)
2. 객체 생성과 gc 가 java 에서 최적화가 잘되어있다는 믿음

을 통해서 수정 구현예정입니다 ㅎㅎ

2020-12-04 00:47 UTC, humbledude commented
@kriery  안녕하세요~ ㅎㅎ
말씀하신 부분 수정해 보았습니다~

말씀하신 부분 중에, HttpRequestParser 를 static 으로 만들수 있다는 부분을 수정하다 보니,
static inner class 로 만들게 되었어요~ ㅎㅎ

리뷰 또다시 잘 부탁 드립니다 ㅎㅎ

2020-12-04 00:55 UTC, kriery approved these changes
피드백을 잘 반영 하셨네요 :)
다음 step도 멋지게 진행하시길 바라면서, 이대로 merge 하겠습니다!

2020-12-04 00:55 UTC, kriery commented on src/main/java/webserver/http/HttpRequest.java
> +    }
static inner는 생각치도 못했는데 ❗

2020-12-04 00:55 UTC, merged