[eli.nabro 일라이, 오영민] WAS step1~2 코드리뷰 요청드립니다
NewKrew2021/jwp-was-kakao pull request #54
Opened 2021-02-04 03:37 UTC by maireneu

안녕하세요. 일라이입니다.

WAS 프로젝트 미션 코드리뷰 요청드립니다!

여러가지 WAS 구현 중 더 잘해보고 싶은게 많았고, 시도해보기도 하였으나 시간이 짧고 욕심에 비해 제가 부족한점이 많네요 ㅠㅠ.. 

기능은 모두 구현 하였고, 최대한 리팩토링을 진행하였습니다.
리뷰 부탁드립니다.

감사합니다.

2021-02-04 08:01 UTC, parkjoos requested changes
일라이 안녕하세요😁
WAS 메션 리뷰를 하게된 jay 입니다. 반갑습니다. 😊

전체적으로 테스트 코드를 잘 작성하면서 개발을 진행해주신것 같아서 좋았습니다. 
그리고 사용자의 로직 부분과 was 의 로직 부분을 분리해서 추가 사용자 로직이 필요할때 좀더 쉽게 적용이 되도록 잘 구현이 된 것 같아요 👍👍

다만 was의 로직들 중에 도메인 클래스들을 좀더 분리하고 기능들을 나눌 수 있을것 같아서
관련 내용을 코멘트로 피드백 드렸습니다. 
추가로 몇가지 개선 되면 좋을것 같은 내용들도 함께 남겼으니 한번 확인 부탁드립니다.

2021-02-04 08:01 UTC, parkjoos commented on src/main/java/controller/AbstractController.java
> +    }
빈 내용으로 채워 두는 것 보다는 이 Http method 에 해당하는 url이 없다는 exception 를 발생 시켜 보면 어떨까요?

2021-02-04 08:01 UTC, parkjoos commented on src/main/java/controller/CreateUserController.java
> +        super.doPost(httpRequest, httpResponse);
위에 제가 말한  exception 을 넣고 super 호출을 제거하면 좋을 것 같아요

2021-02-04 08:01 UTC, parkjoos commented on src/main/java/http/HttpBody.java
> +    private Map<String, String> bodyParameters = new HashMap<>();
paramters 도 일급 컬렉션을 하나 만들어 클래스를 분리하며 아래 몇가지 로직을 위임 할 수 있을 것 같습니다.

2021-02-04 08:01 UTC, parkjoos commented on src/main/java/http/HttpHeader.java
> +            httpHeader.put(currentLine[0], URLDecoder.decode(currentLine[1],"UTF-8"));
UTF-8 도 상수화 할 수 있을것 같아요 혹은 이미 제공되는 상수나 enum 타입을 이용해 봐도 좋을것 같습니다.

2021-02-04 08:01 UTC, parkjoos commented on src/main/java/http/HttpRequest.java
> +    private String version;
위에서 잠깐 언급했던 parameters 를 별도의 클래스로 만들었으면 여기에서도 사용할 수 있을 것 같네요 
그리고 path 나 version 도 원시값을 포장하면 몇가지 제약조건이나 관련 로직들을 해당 도메인에 넘길 수 있을 것 같습니다.

2021-02-04 08:01 UTC, parkjoos commented on src/main/java/http/HttpResponse.java
> +    private final static String HTTP = "http://";
위의 상수들중 대부분이 HttpResponse 에서만 사용되는 내용이 아니라 request 에서도 사용될 것 같은데요 
request response 가 모두 가지고 있는 HttpHeader 의 속성으로 보면 좀더 적절한 위치가 아닐까 생각됩니다.

2021-02-04 08:01 UTC, parkjoos commented on src/main/java/http/HttpResponse.java
> +        login = this.httpHeader.getHeaderByKey(SET_COOKIE);
login 이라는 속성도 몇가지 제약조건과 로직들이 좀 있는것 같아요 아래 있는 login() 메소드도 그렇고요
이것도 LoginCookie 같은 클래스로 포장을 해주면 이런 부분들을 위임 할 수 있을 것 같습니다.

2021-02-05 07:05 UTC, maireneu commented on src/main/java/controller/AbstractController.java
> +    }
말씀하신대로 Exception을 추가하였습니다! 
다만, RequestHandler에서 request url에 따라 controller호출을 제어하는데, 해당부분이 어째서 필요한가요??

2021-02-05 07:05 UTC, maireneu commented on src/main/java/controller/CreateUserController.java
> +        super.doPost(httpRequest, httpResponse);
말씀하신대로 바꾸었습니다! 감사합니다.

2021-02-05 07:06 UTC, maireneu commented on src/main/java/http/HttpBody.java
> +    private Map<String, String> bodyParameters = new HashMap<>();
Parameters 를 객체 생성후, request와 response 각각에서 공유하도록 하고, 일부 로직을 위임하였습니다.

2021-02-05 07:06 UTC, maireneu commented on src/main/java/http/HttpHeader.java
> +            httpHeader.put(currentLine[0], URLDecoder.decode(currentLine[1],"UTF-8"));
이미 제공되는 상수를 사용하도록 변경하였습니다.

2021-02-05 07:29 UTC, maireneu commented on src/main/java/http/HttpRequest.java
> +    private String version;
parameter를 request와 response가 공유하도록 수정하였습니다! 또한 path를 PathPage 형태로 포장하였습니다. (version의 경우, 당장 사용이 없어서 일단 내버려두었습니다)

말씀하신대로 바꾸니, 제약조건들을 해당 객체로 위임할 수 있었습니다. 감사합니다.

2021-02-05 07:30 UTC, maireneu commented on src/main/java/http/HttpResponse.java
> +    private final static String HTTP = "http://";
header가 더 적절한 위치라는 생각에, 해당 상수들을 이동하였습니다.

2021-02-05 07:31 UTC, maireneu commented on src/main/java/http/HttpResponse.java
> +        login = this.httpHeader.getHeaderByKey(SET_COOKIE);
Login 또한 말씀하신대로 제약조건과 로직들을 Logic 도메인을 생성하여 그쪽으로 위임하였습니다.

훨씬 코드가 깔끔해졌네요 ㅎㅎ

2021-02-05 07:42 UTC, parkjoos commented on src/main/java/controller/AbstractController.java
> +    }
이 메소드들이 abstract 메소드가 아니라는 것은 구현체 클래스에서 이 메소드를 override 해도 되고 안해도 된다 선택권을 준 것 같은데요
이후에 추가 controller 를 만들때 구현하지 않은 부분이 RequestHandler 에 매핑되거나 하는 실수가 있을때 이런 excepion이 있다면 명시적인 오류를 보여줄 수 있을것 같아요
일반적으로 WAS 에서 매핑이 없는 url 호출을 하게되면 excepion 을 발생시키고 404 에러 페이지를 띄우는게 사용자 에게는 더 친절한 방식이기 때문이죠

2021-02-05 08:01 UTC, parkjoos requested changes
일라이 안녕하세요 피드백 반영된 것 잘 보았습니다. 😁
도메인 분리를 통해서 구조들이 좀더 단순해지고 정리된것 같아요 👍
코멘트중에 한가지 중요한 부분이 있어서 추가로 change request 남깁니다.
확인한번 부탁드립니다.

2021-02-05 08:01 UTC, parkjoos commented on src/main/java/http/HttpResponse.java
> +    private String login;
login 도메인을 만들었다면 여기도 같은 도메인으로 대체 할 수 있을 것 같아요
아래 몇가지 로직도 해당 도메인으로 위임 할 수 있을 것 같구요

2021-02-05 08:01 UTC, parkjoos commented on src/main/java/webserver/RequestHandler.java
> +        controllers.put(new PagePath("/user/list.html") , new ListUserController());
이부분은 지난번 리뷰에서 놓친 부분 같은데요 
WebServer 에서는 각 커넥션이 생성될때마다 RequestHandler 쓰레드 하나를 생성해서 request 데이터를 전달해 주는데요
지금 이 controller 등록 과정은 해당 쓰레드 생성이 될때마다 반복적으로 이루어 질것 같네요 이 부분은 WAS 전체적으로 한번만 이루어지도록 수정이 되면 좋을것 같습니다.

2021-02-05 10:57 UTC, maireneu commented on src/main/java/http/HttpResponse.java
> +    private String login;
해당 부분을 Login 객체로 변경하고, 로직을 Login 의 함수를 재사용하도록 변경하였습니다.

2021-02-05 10:59 UTC, maireneu commented on src/main/java/webserver/RequestHandler.java
> +        controllers.put(new PagePath("/user/list.html") , new ListUserController());
아 그런 문제가 있었네요!

PageUrl enum을 생성해서 page url - controller 등록이 관리되도록 변경하였습니다.
controller가 매 request마다 하나의 객체로 유지되므로, controller의 맴버변수 Login 객체를 제거하였습니다.

피드백 정말 감사합니다!

2021-02-05 11:06 UTC, parkjoos approved these changes
고생 많으셨습니다
바로 머지 해도 될것 같네요 😀

2021-02-05 11:06 UTC, merged