[pharrell.mp3 정원식] step2 PR 리뷰 요청드립니다.
NewKrew2021/jwp-was-kakao pull request #56
Opened 2021-02-04 09:32 UTC by pilgyumin

안녕하세요
pharrell(퍼렐_민필규)입니다.

이번 미션은 교육 기간 중에서 제일 난이도가 있었던 프로젝트였습니다.
그래서 페어와 프로젝트를 구현하는 데 있어, 다른 프로젝트에 비해
더 힘들게 느꼈던 것 같습니다.

진행하면서 궁금한 점이 생겼습니다.

HttpRequest와 HttpResponse가 File I/O(InputStream, OutputStream)를 생성자 파리미터로
받는 것이 적절한 설계인지 궁금합니다.
왜냐하면 웹 요청과 File I/O는 각각 독립성을 가져야 한다고 생각했기 때문입니다.
이 부분 답변 부탁드리겠습니다.

그럼 이번 리뷰 요청 잘 부탁드리겠습니다.
감사합니다.

2021-02-04 14:46 UTC, kriery commented
`InputStream`과 `OutputStream`/`DataOutputStream`은 말 그대로 Stream을 추상화 합니다.
Stream: 데이터의 흐름; 순서가 있고, 흐름이 끝날 때 까지 앞으로 얼마나 남은지 모름
이 Stream이 꼭 File I/O라고 단정하는 것은 곤란합니다. 특히 이 경우에는 Network I/O 이기 때문이죠.
* `WebServer.main`에서 `ServerSocket`은 `accept`에서 연결된 클라이언트 `Socket`을 반환하고,
* `RequestHandler`로 넘겨받은 `connection`은 연결된 각 클라이언트 `Socket`이기 때문에
* `RequestHandler.run`의 `connection.getInputStream()` 및 `connection.getOutputStream()`은
각각
    * socket으로 부터 data를 read하기 위한 stream과
    * socket에 data를 write하기 위한 stream을 반환합니다.

흔히 웹 요청이 어떤 포장된 데이터의 집합이라고 생각하기 쉽지만, 대량의 파일을 업로드 하는 경우를 고려해보면 꼭 그렇지도 않죠.
(이 때는 header가 전달된 직후 어마어마한 양의 data가 stream을 통해 넘어갑니다)
웹 응답(;response)도 마찬가지예요. 

이렇듯 `HttpRequest` / `HttpResponse`야 말로 `InputStream`과 `OutputStream`과 밀접한 관계를 갖고 있어야 합니다.

2021-02-04 14:48 UTC, kriery requested changes
안녕하세요 퍼렐, 리뷰를 맡은 크리스입니다.
제일 난이도가 있다고 하신데에 비해 훌륭히 잘 해내셨군요 😄 
다소 의미에 맞지 않는 부분과, 몇가지 군더더기를 피드백 드립니다.
피드백 수정해서 다시 만나요 🎈

2021-02-04 14:48 UTC, kriery commented on src/main/java/webserver/RequestHandler.java
> +    public synchronized void run() {
`RequestHandler`는 thread마다 별도의 instance가 할당될텐데 `run`을 `synchronized`로 할 필요가 있을까요?

2021-02-04 14:48 UTC, kriery commented on src/main/java/response/Response200Status.java
> +    }
step2 까지 진행하면서, 모든 `ResponseXXXStatus`클래스에 `writeStatus`의 모양이 동일하게 되었어요.
이 부분을 조금 더 리펙토링 해보면 어떨까요?

2021-02-04 14:48 UTC, kriery commented on src/main/java/request/HttpMethod.java
> +    }
`of`를 위한 value cache 👍 
static block을 없애고 싶으면 stream을 이용할 수 있습니다.
```suggestion
    private static final Map<String, HttpMethod> mappings = Arrays.stream(values())
            .collect(Collectors.toMap(HttpMethod::name, Function.identity()));
```

2021-02-04 14:48 UTC, kriery commented on src/main/java/response/FileExtension.java
> +        return Optional.of(fileExtensions.get(extension)).orElse(HTML);
`Optional.of`는 not-null로만 취급 되기 때문에 `fileExtensions.get`이 null을 반환할 때,
`NullPointerException`이 발생해서 `orElse` 부분이 무시됩니다.
```suggestion
        return Optional.ofNullable(fileExtensions.get(extension)).orElse(HTML);
```
이 더 맞는 용법일것 같아요.
하지만 이 경우에는 Optional 없이도 간단히 이용할 수 있겠네요
```suggestion
        return fileExtensions.getOrDefault(extension, HTML);
```

2021-02-04 14:48 UTC, kriery commented on src/main/java/utils/ParseUtils.java
> +    }
이 두 method는 항상 같은 인자를 넣고 쌍으로만 이용되는데, 합칠 수 있는 방법은 없을까요?

2021-02-04 14:48 UTC, kriery commented on src/main/java/response/HttpResponse.java
> +        } catch (FileSystemNotFoundException | NullPointerException fsnfe) {
두 Exception 다 이 상황에선 발생하지 않을것 같은데요. 그렇지 않나요?

2021-02-04 14:48 UTC, kriery commented on src/main/java/request/HttpRequest.java
> +            return new HashMap<>();
body parsing 시에 발생하는 IOException이 무시되게 처리하셨어요
만약 header content-length를 제대로 안써서 실 stream보다 더 많은 데이터를 읽으려 할 때,
`IOUtils.readData`에서 예외가 발생할텐데, 로그만 남기고 문제 없이 `request` 처리를 진행하는 것은 좋은 생각이 아닌것 같아요.
차라리 이 때는 `IOException`을 caller에 전파하여 예외를 알려주는 편이 더 좋을 것 같습니다.

2021-02-04 15:43 UTC, pilgyumin commented on src/main/java/webserver/RequestHandler.java
> +    public synchronized void run() {
이 부분은 테스트하다가 미처 지우지 못한 키워드였습니다. 바로 삭제하겠습니다!

2021-02-04 16:03 UTC, pilgyumin commented on src/main/java/request/HttpMethod.java
> +    }
오 넵 감사합니다 identity 메소드에 대해 배울 수 있었습니다!😄

2021-02-04 16:21 UTC, pilgyumin commented on src/main/java/response/FileExtension.java
> +        return Optional.of(fileExtensions.get(extension)).orElse(HTML);
넵 알겠습니다 해당 부분 반영하겠습니다!

2021-02-04 16:54 UTC, pilgyumin commented on src/main/java/response/HttpResponse.java
> +        } catch (FileSystemNotFoundException | NullPointerException fsnfe) {
네 맞습니다 해당 부분 수정하겠습니다!

2021-02-04 16:59 UTC, pilgyumin commented on src/main/java/request/HttpRequest.java
> +            return new HashMap<>();
네 알겠습니다. HttpRequest 만드는 생성자까지 IOException을 던져서, 실제 호출하는 부분에서 해당 Exception을 받을 수 있도록 구현하겠습니다!

2021-02-05 02:08 UTC, pilgyumin commented on src/main/java/response/Response200Status.java
> +    }
넵 해당 부분 수정 진행하겠습니다!

2021-02-05 02:09 UTC, pilgyumin commented on src/main/java/response/Response200Status.java
> +    }
혹시 이 부분에 대해서 제가 구현한 방법과 생각이 다르셨다면, 추가 코멘트 부탁드리겠습니다!🙏

2021-02-05 02:18 UTC, pilgyumin commented on src/main/java/utils/ParseUtils.java
> +    }
header를 통해서 HeaderPair로 파싱하는 방법으로 진행하겠습니다. 혹시 이 부분도 저랑 생각이 다르셨다면, 추가 코멘트 부탁드리겠습니다!

2021-02-05 12:07 UTC, pilgyumin commented
2단계와 3단계는 
       docs(readme.md) : 3단계 기능 요구 사항 목록 작성 

위 커밋으로 구분 된다는 점 전달 드리겠습니다.
감사합니다!

2021-02-07 12:58 UTC, kriery approved these changes
안녕하세요 퍼렐, 마지막 미션이네요.
간단한 개선 사항들 몇가지 남겼으니 읽어보시고,
미션은 이대로 마무리 할게요. 고생했어요.

2021-02-07 12:58 UTC, kriery commented on src/main/java/utils/ParseUtils.java
>      }
`String[]`을 반환 하는걸 염두해 두고 피드백을 드린거지만, 의미 있는 객체로 하는 것이 더욱 좋네요 👍

2021-02-07 12:58 UTC, kriery commented on src/main/java/request/HttpSessions.java
> +    }
생성자에서 static 변수를 초기화 하는 것은 좋은 생각이 아니예요.
차라리 `HttpSessions`의 method들을 모두 static으로 이용하면 어떤가요?

2021-02-07 12:58 UTC, kriery commented on src/main/java/response/Response200Status.java
> +    }
음.. `MESSAGE`가 `HTTP/1.1 {XXX} {YYY}\r\n` 형태로 일정한데요.
이대로라면 Http Status가 추가될 때 마다 새로운 class를 만들어야 하겠지요.
https://developer.mozilla.org/ko/docs/Web/HTTP/Status

```java
response(new ResponseXXXStatus())
```
보다는
```java
response(ResponseStatus.OK) 
```
처럼 되는 것이 더 좋을것 같아 피드백 드렸어요

2021-02-07 12:58 UTC, merged

2021-02-08 06:23 UTC, pilgyumin commented on src/main/java/response/Response200Status.java
> +    }
아 넵 알겠습니다 해당 방법도 고려해서 리팩토링 하겠습니다!

2021-02-08 06:24 UTC, pilgyumin commented on src/main/java/utils/ParseUtils.java
>      }
넵 감사합니다!!