[brody.kim_김현우] was 미션 step2 리뷰 요청 드립니다.
NewKrew2021/jwp-was-kakao pull request #57
Opened 2021-02-04 09:35 UTC by briron

안녕하세요. 브로디입니다.

was 미션 관련하여 간략히 구조를 설명드리면 아래와 같습니다.

HttpRequest : 사용자의 요청을 처리하는 클래스로, 헤더와 파라미터 등을 저장하고 있습니다.
 - HttpMethod라는 enum을 별도로 만들어 http method 들을 관리하고 있습니다)

HttpResponse : 서버 응답을 처리하는 클래스로, 
 - ResponseStatus라는 인터페이스와 디폴트 메서드를 만들어 개별 status code들은 상속받아 사용하고 있습니다.
 - FileExtension이라는 enum을 만들어 확장자와 content-type 등을 구분하고 있습니다.

controller : URL에 따른 서버 처리를 분기하는 클래스로, 하위에 구체 클래스를 만들어 로직들을 분리하였습니다.

utils : 헤더, 파라미터, 확장자 분리와 같은 기능들을 분리하였으며 테스트 코드를 작성하였습니다.

common/HttpHeaders : request, response 에 공통적으로 사용되는 header를 별도의 enum으로 만들었습니다.

이번 미션을 웹서버를 처음부터 구현하는 거라 어려웠습니다.

다만 웹서버를 이해하는데 많은 도움이 되었고, 또 상속이나 다형성을 이용해서 코드가 간결해지는 것을 느낄 수 있었습니다.

많은 조언 부탁드립니다.

2021-02-05 01:20 UTC, ljh131 requested changes
안녕하세요.
프레임웍으로 볼 수 있는 웹서버와 서비스를 다른 패키지로 구분하고 각자의 역할에 맞는 일만 하도록하면 좋겠습니다. (특히 프레임웍에서 서비스 로직과 관련된 일을 조금이라도 하지 않도록요)
그리고 서비스의 각종 회원 로직에 대한 integration 테스트 추가도 해보시면 좋겠습니다.

2021-02-05 01:20 UTC, friediceday commented on src/test/java/utils/ParseUtilsTest.java
> +class ParseUtilsTest {
서비스에 대한 integration test가 없는 것 같습니다. 추가해보시면 좋겠습니다.

2021-02-05 01:20 UTC, friediceday commented on src/main/java/webserver/RequestHandler.java
> +    public synchronized void run() {
이건 왜 synchronized 인가요?

2021-02-05 01:20 UTC, friediceday commented on src/main/java/controller/AbstractController.java
> +public abstract class AbstractController implements Controller {
프레임웍으로 볼 수 있는 웹서버와 서비스를 다른 패키지로 구분하면 어떨까요

2021-02-05 01:20 UTC, friediceday commented on src/main/java/response/Response200Status.java
> +public class Response200Status implements ResponseStatus {
응답마다 클래스가 하나씩 있으면 좋아보이지 않습니다...

2021-02-05 01:20 UTC, ljh131 commented on src/main/java/response/HttpResponse.java
> +    public void forward(String path) throws IOException, URISyntaxException {
응답객체가 파일전송까지 해주면 너무 많은 일을 하는것 같습니다. 그리고 이름도 forward보다 더 명확한 이름이면 좋겠습니다.

2021-02-05 01:20 UTC, ljh131 commented on src/main/java/response/HttpResponse.java
> +        } catch (FileSystemNotFoundException | NullPointerException fsnfe) {
file system not found는 어느 상황에서 발생하는건가요? 그리고 익셉션 2개만 처리하면 되나요?

2021-02-05 01:20 UTC, ljh131 commented on src/main/java/response/HttpResponse.java
> +            response(new Response404Status());
이 상황에서 404 에러가 맞는지 궁금해요

2021-02-05 01:20 UTC, ljh131 commented on src/main/java/request/HttpRequest.java
> +    private Map<String, String> makeBodies(BufferedReader reader) {
이름이 body면 보통 body는 메시지 마디를 생각할 것 같은데 더 명확한 이름이 필요하겠습니다. 게다가 url의 query param을 쓰는 경우도 있는데요

2021-02-05 01:20 UTC, ljh131 commented on src/main/java/controller/DefaultController.java
> +    protected void doGet(HttpRequest request, HttpResponse response) throws IOException, URISyntaxException {
이 컨트롤러는 등록된 url이 아닌 모든 경우에 대해 수행되는건가요?

2021-02-05 01:20 UTC, ljh131 commented on src/main/java/controller/Controller.java
> +    Map<String, Controller> controllers = UrlPath.getControllers();
인터페이스가 멤버를 갖고있으면 적절치 않을 것 같은데요. 게다가 public이 되니까요

2021-02-05 01:20 UTC, ljh131 commented on src/main/java/controller/Controller.java
> +    static Controller of(String path) {
이것도 물론 static이긴 하지만 인터페이스에 굳이 있어야 하는지도 의문입니다.

2021-02-05 01:20 UTC, ljh131 commented on src/main/java/controller/ListUserController.java
> +        Handlebars handlebars = new Handlebars(loader);
템플릿엔진은 여기서만 쓸게 아니니 공통으로 빼면 어떨까요

2021-02-05 01:20 UTC, ljh131 commented on src/main/java/response/FileExtension.java
> +    CSS(".css", "text/css", Constants.STATIC),
파일 확장자와 디렉토리가 서로 엮여있는데요 별로 유연해보이지 않습니다

2021-02-05 07:18 UTC, briron commented on src/main/java/webserver/RequestHandler.java
> +    public synchronized void run() {
중간에 디버깅 중에 넣었던 것을 지우지 못했습니다. 수정하였습니다.

2021-02-05 07:18 UTC, briron commented on src/main/java/controller/AbstractController.java
> +public abstract class AbstractController implements Controller {
framework 와 service 패키지로 구분하여 웹서버 기능과 서비스 로직을 분리하였습니다.

2021-02-05 07:19 UTC, briron commented on src/main/java/response/Response200Status.java
> +public class Response200Status implements ResponseStatus {
ResponseStatus라는 enum으로 변경하였고, response에 저장하여 사용할 수 있도록 변경하였습니다.

2021-02-05 07:20 UTC, briron commented on src/main/java/response/HttpResponse.java
> +    public void forward(String path) throws IOException, URISyntaxException {
응답객체에서 파일전송을 하지 않도록 forward 메서드를 제거하였으며, 서비스 로직에서 FileController를 만들어 FileController가 파일을 읽은 후 response에 읽은 내용을 전달하도록 변경하였습니다.

2021-02-05 07:22 UTC, briron commented on src/main/java/response/HttpResponse.java
> +        } catch (FileSystemNotFoundException | NullPointerException fsnfe) {
file system not found 는 파일이 없는 경우에 발생해야 하는데, 확인해보니 파일이 없으면 그 전에 NullPointerException가 발생하여 사실상 불필요한 Exception 입니다. 이에 이 예외를 제거하였으며 URISyntaxException 을 추가로 확인하여 Bad Request를 반환토록 변경하였습니다 (FileController)

2021-02-05 07:23 UTC, briron commented on src/main/java/response/HttpResponse.java
> +            response(new Response404Status());
redirect인 경우 위 두 예외가 발생할 수 없어 제거하였습니다.

2021-02-05 07:25 UTC, briron commented on src/main/java/request/HttpRequest.java
> +    private Map<String, String> makeBodies(BufferedReader reader) {
네 의미를 명확히 하기 위해 변수와 메서드명을 모두 parameters로 변경하였습니다.

2021-02-05 07:47 UTC, briron commented on src/main/java/controller/DefaultController.java
> +    protected void doGet(HttpRequest request, HttpResponse response) throws IOException, URISyntaxException {
네. 등록되지 않은 url에 대해서 파일을 반환토록 의도된 Controller인데 의도를 명확히 하기 위해 이를 FileController로 변경하였습니다.

2021-02-05 07:48 UTC, briron commented on src/main/java/controller/Controller.java
> +    Map<String, Controller> controllers = UrlPath.getControllers();
구체적인 Mapping 정보에 대해서는 AbstractController가 가지도록 변경하였습니다.

2021-02-05 07:48 UTC, briron commented on src/main/java/controller/ListUserController.java
> +        Handlebars handlebars = new Handlebars(loader);
TemplateEngine이라는 클래스를 별도로 만들었습니다.

2021-02-05 07:51 UTC, briron commented on src/main/java/response/FileExtension.java
> +    CSS(".css", "text/css", Constants.STATIC),
이 문제에 대해 많이 고민했는데요, service/controller 패키지 안에  FileExtension이라는 enum을 만들어 확장자, content-type을 매칭하고, ResouceType을 지정해주었습니다. 그리고 FileController 내에 ResourceType에 따른 경로를 찾을 수 있도록 메서드를 만들었습니다.
어떤 것이 더 좋은 설계일지 리뷰어님의 의견이 궁금합니다.

2021-02-05 07:55 UTC, briron commented on src/test/java/utils/ParseUtilsTest.java
> +class ParseUtilsTest {
HttpRequest와 HttpResponse 테스트를 통해 요청과 응답에 대한 테스트를 추가했습니다!

2021-02-05 08:02 UTC, briron commented
안녕하세요. 브로디입니다.
주신 피드백을 바탕으로 수정하였습니다.
수정 내용을 간략히 설명드리면 아래와 같습니다.

1. service 패키지와 framework 패키지를 분리하여 웹서버와 서비스 로직을 분리하였습니다
2. 통합 테스트를 추가하였습니다.
3. 클래스로 나눠져있던 ResponseStatus를 Enum으로 변경하였습니다
4. 예외 처리에 따라 올바른 응답을 반환하도록 변경하였습니다. IOException만 RequestHandler에서 처리하도록 변경하였습니다.
5. Interface Controller에 저장되어있던 멤버변수와 매핑정보는 모두 서비스 패키지 이하의 AbstractController로 이동하였습니다. 또한 FileController를 새로 만들어 File 전송에 대한 처리를 담당하도록 하였습니다.
6. FileExtension에 함께있던 디렉토리 정보를 FileController로 분리하였습니다.
7. 그 외 지적해주신 피드백 등을 수정하였습니다.

피드백을 반영하면서 가장 고민이었던 부분은 파일 전송을 처리하는 방법과 파일의 형식에 따른 분기를 어디에서 처리할지였습니다.
현재는 FileController 부분에서 담당하고 있는데 더 좋은 설계방법이 있는지 궁금합니다.

많은 조언 부탁드립니다.

2021-02-05 10:39 UTC, ljh131 requested changes
안녕하세요. 여러가지 커멘트 드렸는데 잘 수정해주셨습니다.
어려울 수도 있지만 추가로 더 고민해볼 수 있는 부분들 커멘트 드렸습니다. (프레임웍과 서비스의 분리, 통합 테스트, 예외 처리)

2021-02-05 10:39 UTC, ljh131 commented on src/test/java/framework/request/HttpRequestTest.java
> +class HttpRequestTest {
http요청을 보내고 응답을 검증하는 integration 테스트도 만들어보시면 좋겠습니다.

2021-02-05 10:39 UTC, ljh131 commented on src/main/java/framework/common/TemplateEngine.java
> +        Handlebars handlebars = new Handlebars(loader);
매번 초기화할 필요는 없을 것 같아요

2021-02-05 10:39 UTC, ljh131 commented on src/main/java/service/controller/FileController.java
> +    private static final String static_path = "./static";
이름을 upper case로 해야 할 것 같네요

2021-02-05 10:39 UTC, ljh131 commented on src/main/java/webserver/RequestHandler.java
> +            Controller controller = AbstractController.of(httpRequest.getPath());
여기서 서비스 코드를 바로 호출하게 되는데 서비스가 프레임웍에 처리할 컨트롤러들을 등록하는 방식이면 더 좋지 않을까요

2021-02-05 10:39 UTC, ljh131 commented on src/main/java/service/controller/AbstractController.java
> +    public void service(HttpRequest request, HttpResponse response) throws IOException {
프레임웍도 마찬가지지만 서비스에서 익셉션이 발생하면 어떻게 처리할지에 대해 고려해보시면 좋겠습니다. (특히 unchecked)

2021-02-06 05:30 UTC, briron commented on src/test/java/framework/request/HttpRequestTest.java
> +class HttpRequestTest {
네 웹요청을 보내는 통합테스트를 추가하였습니다.

2021-02-06 05:30 UTC, briron commented on src/main/java/framework/common/TemplateEngine.java
> +        Handlebars handlebars = new Handlebars(loader);
네 클래스 생성 시에 초기화하도록 변경하였습니다.

2021-02-06 05:32 UTC, briron commented on src/main/java/service/controller/AbstractController.java
> +    public void service(HttpRequest request, HttpResponse response) throws IOException {
이 부분이 정확히 이해가 가지는 않는데, Controller에서 unchecked 된 예외도 모두 throw 하고 requestHandler에서 catch할 수 있도록 변경하였습니다!

2021-02-06 05:37 UTC, briron commented on src/main/java/webserver/RequestHandler.java
> +            Controller controller = AbstractController.of(httpRequest.getPath());
현재는 서비스 내의 AbstractController에서 생성 초기에 컨트롤러들을 등록하는 방식으로 되어 있는데, RequestHandler에서 등록하도록 변경하였습니다. 말씀하신 의도대로 변경된 것인지는 잘 모르겠습니다.

2021-02-08 04:33 UTC, ljh131 reviewed
마지막까지 수고하셨습니다. 커멘트 남겼으니 참고해보시면 좋겠습니다. 그럼 머지하겠습니다.

2021-02-08 04:33 UTC, ljh131 commented on src/main/java/webserver/RequestHandler.java
> +        } catch (Exception e) {
에러 발생시 아무 응답없이 커넥션이 종료될 것이기 때문에 되도록 에러 응답을 보내고 종료하는게 좋을 것 같습니다.

2021-02-08 04:33 UTC, ljh131 commented on src/main/java/webserver/RequestHandler.java
> +            AbstractController.enroll("/user/list", new ListUserController());
매번 등록할 필요 없이 1회만 해주면 될 것 같습니다. 그리고 프레암웍이 아닌 외부 서비스가 등록해주는게 좋을 것 같습니다.

2021-02-08 04:33 UTC, merged