[hendo.park] step3 리뷰 요청 드립니다!
NewKrew2021/jwp-was-kakao pull request #60
Opened 2021-02-04 19:12 UTC by Chaeoon-Park

안녕하세요 adel!! 
저번 리뷰 때 질문과 리뷰를 정말 정성스럽게 해주셔서 감사합니다!! 
주신 리뷰를 읽어보고, 또 리팩토링에 욕심을 조금 내다가 보니까 시간이 오래 지나서.. 그런가 집중력이 많이 떨어져서 예외처리와 테스트 코드 작성은 부족한 것 같기는 한데, 미션 종료 시간을 생각해서 지금 리뷰를 드리게되었어요..!!  
특히 패턴에 대해 조언해주신점이 너무나 도움이 되었던 것 같습니다..! 앞으로 팀에 가게 되면 패턴에 대해서도 항상 생각을 해봐야겠어요..! 
무기(?)가 하나 늘어난 기분이라 너무 감사합니다 ㅎㅎ

이번에 드리고 싶은질문은 두개 있는데요..!

1. 리팩토링 과정에서 컨트롤러에 
`private static final String LOGIN_PAGE = "http://localhost:8080/user/login.html";`
와 같은 형식으로, 페이지 주소들을 지정해 놓았는데요. 
보통은 페이지주소 같은 경우 컨트롤러 안에서 처리를 하지 않는편인가요..?
그게 아니라면 enum을 통해서 페이지를 저장해놓는 클래스를 만드는것은 어떨까요? 웹에서 사용될 페이지들만 따로 모아놓는 enum 클래스요..!

2. 세션을 구현 한 뒤에, 세션을 통해 로그인 조회를 하도록 하고 쿠키가 새로 들어올 경우 세션에 다시 집어 놓도록 구현하였는데, 제가 제대로 이해한것이 맞는지 잘 모르겠네요..! 이 질문은 그냥 제가 완전 틀리게 구현한 것이면 답변 주셨으면 좋겠어요..!

항상 정성스러운 리뷰 감사드립니다.

그리고..! 그냥 TMI를 주저리 주저리 하자면..! 이번 페어가 echo여서 대화를 나누다 adel이 카페 서버 개발 셀장이신걸 알게 되었는데요..!! 
중학교때부터 다음 카페를 정말 많이했고, 지금도 2만명정도 되는 카페를 운영하고 있어서 다음 카페에 애정이 정말 깊은 하드 유저여서 그런가,
카페 서버 개발짱님께 리뷰를 받고있다고 생각하니 덕업일치를 한거같고  카카오 오길 너무 잘한거같고 굉장히 설레는 하루였던거같아요 ..!!! ㅎㅎㅎ
(코드도 부디.. 실망스러운 코드가 아니길 빌면서... ㅠㅠㅠㅋㅋㅋㅋㅋ)
adel이 말씀하신 20년정도 된 서비스가 다음 카페였다니,,ㅎㅎㅎ ㅠㅠ  그냥 이 기회에 팬심 노출(?) 한번 해보고 싶었습니다..! ㅎㅎ 
리뷰와 별개로 카페 개발해주시는분들께 너무 감사하다는 말씀을 드리고 싶어서 주저리 주저리 하게되었네요.... ㅎㅎㅎㅎ

2021-02-05 03:39 UTC, Chaeoon-Park commented
오 세션id를 주고받지 않게 구현해서 빠르게 수정하겠습니다 ㅠㅠㅠㅠ pr날려놓고 이제야 발견해서 죄송합니다

2021-02-05 04:07 UTC, adeldel commented
@Chaeoon-Park 수정하시는 김에 `http://localhost:8080`  페이지주소마다 추가하셨는데 기존처럼 없어도 잘 동작합니다.
`HttpResponseUtils.finePath` 로 정상적으로 리소스를 찾아 로드하도록 구현해주셨기 때문에 없어도 무방하구요.
나중에 아마 웹서비스에서 스프링과 빠질수 없는 다양한 템플릿 엔진 (여기서는 handlebar )을 쓰실건데요. 
템플릿엔진을 잘 설정만 해주면 템플릿들을 잘 찾아주기 때문에 편하게 쓸수 있습니다.
잠깐 열어봤다가 위 부분이 제일 눈에 띄어서 먼저 말씀드려요.  😅  되도록 오늘 리뷰완료할께요. 

그리고 우리 고객님이 여기도 계셨네요 😄 😄  저 또한 반갑습니다.
오래된 서비스지만 많은 분들이 카페서비스에 애정을 가지고 계시기에 이렇게  저희가 일할 힘이 생기는 것 같아요!!  
(저 또한 우리 서비스 애정합니다 😍)
저희셀에 합류예정이신 에코와 친하시다니 에코를 통해 voc(voice of customer) 주셔도 됩니다. 🤘🏻🤘🏻🤘🏻

2021-02-05 04:30 UTC, Chaeoon-Park commented
두부분 모두 수정 완료했습니다..! 

저희 코멘트가 일할힘을 드렸다니 너무 뿌듯하네요 ㅠㅠ 저 말고도 제 주변에 너무 감사하게 생각하시는 분들이 많은거같아요 ㅎㅎ
에코 통해서 종종 voc를 한번 내보도록 하겠습니다!!

리뷰는 주실수있으시면 편하실 때 언제든 주셔도 감사하겠습니다!! ㅎㅎㅎ

2021-02-05 12:09 UTC, adeldel requested changes
안녕하세요 hendo! 기능테스트를 해보면 로그인시  정상적으로 세션기능이 동작하지 않고 있습니다.  😭 
(유종의 미를 거두시길 바라는 마음으로)  버그수정해서 다시 요청 부탁드려요 🙏

2021-02-05 12:09 UTC, adeldel commented on src/main/java/request/Cookie.java
> +        return new Cookie(splitLine[0].trim(), splitLine[1].trim(), null);
path는 null로 항상 채워지므로 불필요해 보입니다.

2021-02-05 12:09 UTC, adeldel commented on src/main/java/controller/CreateUserController.java
>                  httpRequest.getParameter(NAME), httpRequest.getParameter(EMAIL));
메소드인자가 많다면 DTO 객체를 만들어 값을 바인딩 후 createUser 에게 전달해도 좋습니다.

2021-02-05 12:33 UTC, Chaeoon-Park commented
adel! 일단 피드 주신내용은 빠르게 수정해보았고요..!!
혹시 어떤 오류가 뜨시는지 알려주실 수 있을까요? 저는 아래와같이 세션아이디를 주고 받고 세션아이디를 통해서 로그인을 확인 하고, 로그인 기능이 제대로 작동하고 있는거같은데 
제가 혹시 이해를 잘못한 부분이 있는걸까요?

21:30:31.447 [DEBUG] [Thread-60] [webserver.RequestHandler] - header: Cookie: sessionId=fd0edcb0-4893-458e-913a-fa2a28fbefd1

2021-02-07 08:14 UTC, Chaeoon-Park commented
사이드 이펙트를 제거해서 다시 제출합니다.. !

2021-02-07 08:15 UTC, Chaeoon-Park commented
사이드 이펙트를 제거해서 다시 제출합니다..!
[refactor : UserDto 객체 생성를 조금 더 활용] 후에 테스트를 똑바로 해보지 않고 제출했던거같네요.
정말 죄송합니다.. ㅠㅠ 바쁘신 와중에 리뷰와 디엠 받아주셔서 정말 감사합니다!!

2021-02-07 10:38 UTC, adeldel commented on src/main/java/request/HttpRequest.java
> +        return null;
개인적으로는 null보단 "" (엠티스트링)이 어떨까 해요.

2021-02-07 10:41 UTC, adeldel approved these changes
안녕하세요 hendo!! 마지막까지 요청드린 부분을 잘 수정해주셔서 감사합니다.
해당 미션은 approve&merge 해둘께요.
앞으로 조직에 가셔서 잘 적응하시고, 성장하는 개발자가 되길 바라겠습니다. 
교육기간동안 정말 수고 많으셨습니다. 👏🏻👏🏻👏🏻👏🏻

2021-02-07 10:41 UTC, merged