[Http 웹 서버 구현] 1단계
NewKrew2021/jwp-was-kakao pull request #7
Opened 2020-12-03 14:23 UTC by limmmee-bonjour

안녕하세요 리뷰어님!
Http 웹 서버 구현 1단계 리뷰요청 드립니다.
(리팩토링 해야할 부분이 많아보이지만..) 시간이 너무 길어질것 같아 1단계는 이 정도에서 리뷰 요청 드립니다.
수정해야할 부분이나 잘못된 부분이 있다면 리뷰 주셔요. 감사합니다 :)

2020-12-07 11:37 UTC, parkjoos requested changes
@limmmee-bonjour  벨 안녕하세요 리뷰어로 지정된 제이 입니다.
너무 늦게 피드백 드려 죄송합니다 😂
 1단계 구현해 주신 부분 잘 보았습니다. 
요구사항 5에 로그인 실패시 login_failed.html 페이지 이동
요구사항 6에 미로그인시 로그인 페이지로 이동 부분이 요구사항에 맞게 되지 않은 부분이 있습니다.
이부분 먼저 확인 부탁드리고요 
리팩토링 의견들 드린것은 2단계에서 개선이 가능 할것 같으니 추후 수정해 주셔도 좋을 것 같아요!

2020-12-07 11:37 UTC, parkjoos commented on src/main/java/dto/RequestValue.java
> +    }
RequstValue 가 주로 하는 일이 InputStream 을 parsing  하는 걸로 보이네요 
실제 데이터를 가지는 부분은 Request 클래스 에서 하고 있고요
header 나 body 등의 데이터는 Request 클래스 쪽으로 모으고 
(header 나 body 도 클래스로 분리해서 request 에서 가지는 방법도 있을것 같아요)
이 클래스는 유틸성 역할로 제한 하는 것이 좋아 보입니다.

2020-12-07 11:37 UTC, parkjoos commented on src/main/java/dto/RequestValue.java
> +    }
각 부위(?)를 각각을 나타내는 정규표현식으로 파싱하고 있는데요
첫번째 라인에 대해 정규표현식 캡쳐 그룹 을 이용하여 한번에 결과를 만드는 방법을 사용하면 좀 더 간결할것 같습니다.
맨위에 상수 나열된 부분도 줄일 수 있을 것 같고요

2020-12-07 11:37 UTC, parkjoos commented on src/main/java/model/User.java
> +    private static void validate(String value) {
이 메소드가 실제 하는 일은 string의 empty 여부만 체크하는것 같네요.
메소드 이름만으로 하는일을 예측하기 쉽지 않은것 같아요
하고자 하는일이 각 프로퍼티의 empty 체크 라면 그냥 validate 메소드에서 각 프로퍼티를 전체 다 체크 하는 방법도 좋은 방법인것 같습니다.

2020-12-07 11:37 UTC, parkjoos commented on src/main/java/model/factory/UserFactory.java
> +                .collect(Collectors.toList());
이부분 좋은 방법 같은데요!
다만 ParamValue 로 기능을 위임하고 class 를 전달 받아 처리하면 더 좋을 것 같습니다.

2020-12-07 11:37 UTC, parkjoos commented on src/main/java/webserver/Cookie.java
> +    public static Cookie of(String header) {
메소드 시그니처만 봤을때에는 header 를 받아서 Cookie 를 만들 것으로 예상 했는데요 
실제로는 cookie 를 파싱이 이미 완료 된 상태에서 사용해야 하는것으로 보이네요 해당 valid 를 이부분에서 체크 하도록 하거나 아니면 String 대신 RequestHeader 를 전달받고 실제 파싱까지 이 클래스에서 하면 역할 분리가 잘 될 것 같습니다.

2020-12-07 11:37 UTC, parkjoos commented on src/main/java/webserver/ResponseHandler.java
> +        return "./templates" + path + "";
path 가 파싱이 완료된 url path 여야 한다는 가정이 있는데요
이 메소드에서 해당 valid 를 체크 하거나 혹은 확실히 그 validation 이 보장이 되는 객체로 parameter 를 전달받으면 어떨까요?

2020-12-07 12:53 UTC, limmmee-bonjour commented on src/main/java/dto/RequestValue.java
> +    }
@parkjoos 
넵넵 ! 안그래도 지저분한 느낌이 있었는데! 다음 스텝에서 반영해보도록 할게요 :)

2020-12-07 12:56 UTC, limmmee-bonjour commented on src/main/java/dto/RequestValue.java
> +    }
@parkjoos 
넵 RequestValue가 생각보다 커진 느낌이 없잖아 있네요~
스텝 2에서 좀 더 고민해보고 의견 주신부분 반영해볼게요!

2020-12-07 12:59 UTC, limmmee-bonjour commented on src/main/java/model/User.java
> +    private static void validate(String value) {
@parkjoos 
약간 이부분은 개취일수도 있을 것 같긴한데요~
저는 보통 프로퍼티를 명시적으로 다 validate시켜준다는 의미로 각 value들을 체크하는 것 같아요!
validate 라는 메소드명이 조금 불분명하니 validateEmpty로 변경하도록 하겠습니다!

2020-12-07 12:59 UTC, limmmee-bonjour commented on src/main/java/model/factory/UserFactory.java
> +                .collect(Collectors.toList());
@parkjoos 
오 좋네요! 네네 다음 스텝2에서 반영할게요~

2020-12-07 13:00 UTC, limmmee-bonjour commented on src/main/java/webserver/Cookie.java
> +    public static Cookie of(String header) {
@parkjoos 
넵넵! 요 부분도 고민했던 부분인데~
전체적으로 스텝2에서 RequestValue, Cookie, Request 요 각 model 및 DTO 정의를 다시 한번 해보도록할게요!

2020-12-07 13:01 UTC, limmmee-bonjour commented on src/main/java/webserver/ResponseHandler.java
> +        return "./templates" + path + "";
@parkjoos 
그럴수 있겠네요! 네네 요부분도 스텝2에서 추가해서 반영하도록할게요~

2020-12-07 13:03 UTC, limmmee-bonjour commented
@parkjoos 
제이 안녕하세요 :) 좋은 의견들 많이 주셔서 감사합니다!
요구사항 5,6번은 제가 index.html으로 모두 보내버렸네요^^;;;;ㅎㅎ (이런이런 ㅎㅎㅋㅋ)
의견 주신대로 일단 요부분만 수정하였고요, 리팩토링에 관련된 부분들 특히 경계에 대한 부분을 스텝2에서 반영해보도록하겠습니다~
감사합니다 👍

2020-12-08 01:30 UTC, parkjoos approved these changes
수정사항 잘 반영된것 확인 하였습니다. 다음 스텝 화이팅 입니다!👍🏻

2020-12-08 01:30 UTC, merged